package me.hd.wauxv.obf;

import android.view.ViewGroup;
import java.util.Arrays;
import java.util.HashMap;

/* JADX INFO: compiled from: r8-map-id-b9de5da7d0413052737328a4e696e1bcc3145db8f6a41e1e318485e124198cd6 */
/* JADX INFO: loaded from: classes.dex */
public final class adk {
    public int a;
    public final adn b;
    public final adm c;
    public final adl d;
    public final ado e;
    public HashMap f;

    public adk() {
        adn adnVar = new adn();
        adnVar.a = 0;
        adnVar.b = 0;
        adnVar.c = 1.0f;
        adnVar.d = Float.NaN;
        this.b = adnVar;
        adm admVar = new adm();
        admVar.b = -1;
        admVar.c = 0;
        admVar.d = -1;
        admVar.e = Float.NaN;
        admVar.f = Float.NaN;
        admVar.g = Float.NaN;
        admVar.h = -1;
        admVar.i = null;
        admVar.j = -1;
        this.c = admVar;
        adl adlVar = new adl();
        adlVar.b = false;
        adlVar.e = -1;
        adlVar.f = -1;
        adlVar.g = -1.0f;
        adlVar.h = true;
        adlVar.i = -1;
        adlVar.j = -1;
        adlVar.k = -1;
        adlVar.l = -1;
        adlVar.m = -1;
        adlVar.n = -1;
        adlVar.o = -1;
        adlVar.p = -1;
        adlVar.q = -1;
        adlVar.r = -1;
        adlVar.s = -1;
        adlVar.t = -1;
        adlVar.u = -1;
        adlVar.v = -1;
        adlVar.w = -1;
        adlVar.x = 0.5f;
        adlVar.y = 0.5f;
        adlVar.z = null;
        adlVar.aa = -1;
        adlVar.ab = 0;
        adlVar.ac = 0.0f;
        adlVar.ad = -1;
        adlVar.ae = -1;
        adlVar.af = -1;
        adlVar.ag = 0;
        adlVar.ah = 0;
        adlVar.ai = 0;
        adlVar.aj = 0;
        adlVar.ak = 0;
        adlVar.al = 0;
        adlVar.am = 0;
        adlVar.an = Integer.MIN_VALUE;
        adlVar.ao = Integer.MIN_VALUE;
        adlVar.ap = Integer.MIN_VALUE;
        adlVar.aq = Integer.MIN_VALUE;
        adlVar.ar = Integer.MIN_VALUE;
        adlVar.as = Integer.MIN_VALUE;
        adlVar.at = Integer.MIN_VALUE;
        adlVar.au = -1.0f;
        adlVar.av = -1.0f;
        adlVar.aw = 0;
        adlVar.ax = 0;
        adlVar.ay = 0;
        adlVar.az = 0;
        adlVar.ba = 0;
        adlVar.bb = 0;
        adlVar.bc = 0;
        adlVar.bd = 0;
        adlVar.be = 1.0f;
        adlVar.bf = 1.0f;
        adlVar.bg = -1;
        adlVar.bh = 0;
        adlVar.bi = -1;
        adlVar.bm = false;
        adlVar.bn = false;
        adlVar.bo = true;
        adlVar.bp = 0;
        this.d = adlVar;
        ado adoVar = new ado();
        adoVar.b = 0.0f;
        adoVar.c = 0.0f;
        adoVar.d = 0.0f;
        adoVar.e = 1.0f;
        adoVar.f = 1.0f;
        adoVar.g = Float.NaN;
        adoVar.h = Float.NaN;
        adoVar.i = -1;
        adoVar.j = 0.0f;
        adoVar.k = 0.0f;
        adoVar.l = 0.0f;
        adoVar.m = false;
        adoVar.n = 0.0f;
        this.e = adoVar;
        this.f = new HashMap();
    }

    public final Object clone() {
        adk adkVar = new adk();
        adl adlVar = adkVar.d;
        adlVar.getClass();
        adl adlVar2 = this.d;
        adlVar.b = adlVar2.b;
        adlVar.c = adlVar2.c;
        adlVar.d = adlVar2.d;
        adlVar.e = adlVar2.e;
        adlVar.f = adlVar2.f;
        adlVar.g = adlVar2.g;
        adlVar.h = adlVar2.h;
        adlVar.i = adlVar2.i;
        adlVar.j = adlVar2.j;
        adlVar.k = adlVar2.k;
        adlVar.l = adlVar2.l;
        adlVar.m = adlVar2.m;
        adlVar.n = adlVar2.n;
        adlVar.o = adlVar2.o;
        adlVar.p = adlVar2.p;
        adlVar.q = adlVar2.q;
        adlVar.r = adlVar2.r;
        adlVar.s = adlVar2.s;
        adlVar.t = adlVar2.t;
        adlVar.u = adlVar2.u;
        adlVar.v = adlVar2.v;
        adlVar.w = adlVar2.w;
        adlVar.x = adlVar2.x;
        adlVar.y = adlVar2.y;
        adlVar.z = adlVar2.z;
        adlVar.aa = adlVar2.aa;
        adlVar.ab = adlVar2.ab;
        adlVar.ac = adlVar2.ac;
        adlVar.ad = adlVar2.ad;
        adlVar.ae = adlVar2.ae;
        adlVar.af = adlVar2.af;
        adlVar.ag = adlVar2.ag;
        adlVar.ah = adlVar2.ah;
        adlVar.ai = adlVar2.ai;
        adlVar.aj = adlVar2.aj;
        adlVar.ak = adlVar2.ak;
        adlVar.al = adlVar2.al;
        adlVar.am = adlVar2.am;
        adlVar.an = adlVar2.an;
        adlVar.ao = adlVar2.ao;
        adlVar.ap = adlVar2.ap;
        adlVar.aq = adlVar2.aq;
        adlVar.ar = adlVar2.ar;
        adlVar.as = adlVar2.as;
        adlVar.at = adlVar2.at;
        adlVar.au = adlVar2.au;
        adlVar.av = adlVar2.av;
        adlVar.aw = adlVar2.aw;
        adlVar.ax = adlVar2.ax;
        adlVar.ay = adlVar2.ay;
        adlVar.az = adlVar2.az;
        adlVar.ba = adlVar2.ba;
        adlVar.bb = adlVar2.bb;
        adlVar.bc = adlVar2.bc;
        adlVar.bd = adlVar2.bd;
        adlVar.be = adlVar2.be;
        adlVar.bf = adlVar2.bf;
        adlVar.bg = adlVar2.bg;
        adlVar.bh = adlVar2.bh;
        adlVar.bi = adlVar2.bi;
        adlVar.bl = adlVar2.bl;
        int[] iArr = adlVar2.bj;
        if (iArr == null || adlVar2.bk != null) {
            adlVar.bj = null;
        } else {
            adlVar.bj = Arrays.copyOf(iArr, iArr.length);
        }
        adlVar.bk = adlVar2.bk;
        adlVar.bm = adlVar2.bm;
        adlVar.bn = adlVar2.bn;
        adlVar.bo = adlVar2.bo;
        adlVar.bp = adlVar2.bp;
        adm admVar = adkVar.c;
        admVar.getClass();
        adm admVar2 = this.c;
        admVar2.getClass();
        admVar.b = admVar2.b;
        admVar.d = admVar2.d;
        admVar.f = admVar2.f;
        admVar.e = admVar2.e;
        adn adnVar = this.b;
        int i = adnVar.a;
        adn adnVar2 = adkVar.b;
        adnVar2.a = i;
        adnVar2.c = adnVar.c;
        adnVar2.d = adnVar.d;
        adnVar2.b = adnVar.b;
        ado adoVar = adkVar.e;
        adoVar.getClass();
        ado adoVar2 = this.e;
        adoVar2.getClass();
        adoVar.b = adoVar2.b;
        adoVar.c = adoVar2.c;
        adoVar.d = adoVar2.d;
        adoVar.e = adoVar2.e;
        adoVar.f = adoVar2.f;
        adoVar.g = adoVar2.g;
        adoVar.h = adoVar2.h;
        adoVar.i = adoVar2.i;
        adoVar.j = adoVar2.j;
        adoVar.k = adoVar2.k;
        adoVar.l = adoVar2.l;
        adoVar.m = adoVar2.m;
        adoVar.n = adoVar2.n;
        adkVar.a = this.a;
        return adkVar;
    }

    public final void g(adf adfVar) {
        adl adlVar = this.d;
        adfVar.e = adlVar.i;
        adfVar.f = adlVar.j;
        adfVar.g = adlVar.k;
        adfVar.h = adlVar.l;
        adfVar.i = adlVar.m;
        adfVar.j = adlVar.n;
        adfVar.k = adlVar.o;
        adfVar.l = adlVar.p;
        adfVar.m = adlVar.q;
        adfVar.n = adlVar.r;
        adfVar.o = adlVar.s;
        adfVar.s = adlVar.t;
        adfVar.t = adlVar.u;
        adfVar.u = adlVar.v;
        adfVar.v = adlVar.w;
        ((ViewGroup.MarginLayoutParams) adfVar).leftMargin = adlVar.ag;
        ((ViewGroup.MarginLayoutParams) adfVar).rightMargin = adlVar.ah;
        ((ViewGroup.MarginLayoutParams) adfVar).topMargin = adlVar.ai;
        ((ViewGroup.MarginLayoutParams) adfVar).bottomMargin = adlVar.aj;
        adfVar.aa = adlVar.as;
        adfVar.ab = adlVar.ar;
        adfVar.x = adlVar.ao;
        adfVar.z = adlVar.aq;
        adfVar.ae = adlVar.x;
        adfVar.af = adlVar.y;
        adfVar.p = adlVar.aa;
        adfVar.q = adlVar.ab;
        adfVar.r = adlVar.ac;
        adfVar.ag = adlVar.z;
        adfVar.at = adlVar.ad;
        adfVar.au = adlVar.ae;
        adfVar.ai = adlVar.au;
        adfVar.ah = adlVar.av;
        adfVar.ak = adlVar.ax;
        adfVar.aj = adlVar.aw;
        adfVar.aw = adlVar.bm;
        adfVar.ax = adlVar.bn;
        adfVar.al = adlVar.ay;
        adfVar.am = adlVar.az;
        adfVar.ap = adlVar.ba;
        adfVar.aq = adlVar.bb;
        adfVar.an = adlVar.bc;
        adfVar.ao = adlVar.bd;
        adfVar.ar = adlVar.be;
        adfVar.as = adlVar.bf;
        adfVar.av = adlVar.af;
        adfVar.c = adlVar.g;
        adfVar.a = adlVar.e;
        adfVar.b = adlVar.f;
        ((ViewGroup.MarginLayoutParams) adfVar).width = adlVar.c;
        ((ViewGroup.MarginLayoutParams) adfVar).height = adlVar.d;
        String str = adlVar.bl;
        if (str != null) {
            adfVar.ay = str;
        }
        adfVar.az = adlVar.bp;
        adfVar.setMarginStart(adlVar.al);
        adfVar.setMarginEnd(adlVar.ak);
        adfVar.bq();
    }
}
