package me.hd.wauxv.obf;

import net.bytebuddy.jar.asm.Opcodes;
import okhttp3.internal.http2.Http2Connection;

/* JADX INFO: compiled from: r8-map-id-b9de5da7d0413052737328a4e696e1bcc3145db8f6a41e1e318485e124198cd6 */
/* JADX INFO: loaded from: classes.dex */
public final /* synthetic */ class cdp implements bgx {
    public static final cdp b;
    private static final dfx descriptor;

    static {
        cdp cdpVar = new cdp();
        b = cdpVar;
        cuc cucVar = new cuc("me.hd.wauxv.hook.micromsg.core.protobuf.proto.ModUserInfo" /* "me.hd.wauxv.hook.micromsg.core.protobuf.proto.ModUserInfo" /* "me.hd.wauxv.hook.micromsg.core.protobuf.proto.ModUserInfo" /* cnb.z(-341677533297450L)  */, cdpVar, 38);
        bjs.u(-340895849249578L, cucVar, false, 1);
        bjs.u(-340861489511210L, cucVar, false, 2);
        bjs.u(-341389770488618L, cucVar, false, 3);
        bjs.u(-341351115782954L, cucVar, false, 4);
        bjs.u(-341316756044586L, cucVar, false, 5);
        bjs.u(-341290986240810L, cucVar, false, 6);
        bjs.u(-341209381862186L, cucVar, false, 7);
        bjs.u(-341162137221930L, cucVar, false, 8);
        bjs.u(-341132072450858L, cucVar, false, 9);
        bjs.u(-341153547287338L, cucVar, false, 10);
        bjs.u(-342751275121450L, cucVar, false, 11);
        bjs.u(-342729800284970L, cucVar, false, 12);
        bjs.u(-342673965710122L, cucVar, false, 13);
        bjs.u(-342648195906346L, cucVar, false, 14);
        bjs.u(-342575181462314L, cucVar, false, 15);
        bjs.u(-342562296560426L, cucVar, false, 16);
        bjs.u(-343030447995690L, cucVar, false, 17);
        bjs.u(-343000383224618L, cucVar, false, 18);
        bjs.u(-342918778845994L, cucVar, false, 19);
        bjs.u(-342944548649770L, cucVar, false, 20);
        bjs.u(-342845764401962L, cucVar, false, 21);
        bjs.u(-342871534205738L, cucVar, false, 22);
        bjs.u(-342785634859818L, cucVar, false, 23);
        bjs.u(-342162864601898L, cucVar, false, 24);
        bjs.u(-342188634405674L, cucVar, false, 25);
        bjs.u(-342098440092458L, cucVar, false, 26);
        bjs.u(-342072670288682L, cucVar, false, 27);
        bjs.u(-342029720615722L, cucVar, false, 28);
        bjs.u(-341952411204394L, cucVar, false, 29);
        bjs.u(-342476397214506L, cucVar, false, 30);
        bjs.u(-342403382770474L, cucVar, false, 31);
        bjs.u(-342364728064810L, cucVar, false, 32);
        bjs.u(-342351843162922L, cucVar, false, 33);
        bjs.u(-342321778391850L, cucVar, false, 34);
        bjs.u(-342227289111338L, cucVar, false, 35);
        bjs.u(-339474215074602L, cucVar, false, 36);
        bjs.u(-339392610695978L, cucVar, false, 37);
        bjs.u(-339358250957610L, cucVar, false, 38);
        descriptor = cucVar;
    }

    @Override // me.hd.wauxv.obf.btd
    public final Object a(ajt ajtVar) {
        String str;
        String str2;
        String str3;
        ddz ddzVar;
        String str4;
        Integer num;
        String str5;
        Integer num2;
        Integer num3;
        Integer num4;
        Integer num5;
        Long l;
        Integer num6;
        String str6;
        Integer num7;
        Integer num8;
        String str7;
        Integer num9;
        String str8;
        byte[] bArr;
        Integer num10;
        Integer num11;
        Integer num12;
        Integer num13;
        String str9;
        Integer num14;
        Integer num15;
        Integer num16;
        Integer num17;
        Long l2;
        Integer num18;
        String str10;
        Integer num19;
        ddz ddzVar2;
        Integer num20;
        String str11;
        Integer num21;
        Integer num22;
        String str12;
        Integer num23;
        String str13;
        byte[] bArr2;
        Integer num24;
        Integer num25;
        Integer num26;
        Integer num27;
        Integer num28;
        String str14;
        Integer num29;
        Long l3;
        Integer num30;
        Integer num31;
        String str15;
        Integer num32;
        Integer num33;
        String str16;
        Integer num34;
        String str17;
        String str18;
        bip bipVar;
        int i;
        int i2;
        dfx dfxVar = descriptor;
        acm acmVarP = ajtVar.p(dfxVar);
        acmVarP.getClass();
        String str19 = null;
        String str20 = null;
        Integer num35 = null;
        Integer num36 = null;
        String str21 = null;
        bip bipVar2 = null;
        String str22 = null;
        Integer num37 = null;
        Integer num38 = null;
        Long l4 = null;
        String str23 = null;
        Integer num39 = null;
        Integer num40 = null;
        String str24 = null;
        boolean z = true;
        int i3 = 0;
        Integer num41 = null;
        ddz ddzVar3 = null;
        ddz ddzVar4 = null;
        Integer num42 = null;
        ddz ddzVar5 = null;
        ddz ddzVar6 = null;
        Integer num43 = null;
        Integer num44 = null;
        byte[] bArr3 = null;
        Integer num45 = null;
        String str25 = null;
        String str26 = null;
        String str27 = null;
        Integer num46 = null;
        int i4 = 0;
        apc apcVar = null;
        Integer num47 = null;
        Integer num48 = null;
        String str28 = null;
        Integer num49 = null;
        Integer num50 = null;
        Integer num51 = null;
        Integer num52 = null;
        Integer num53 = null;
        String str29 = null;
        while (z) {
            Integer num54 = num36;
            int iF = acmVarP.f(dfxVar);
            switch (iF) {
                case -1:
                    str = str19;
                    str2 = str20;
                    String str30 = str26;
                    String str31 = str27;
                    Integer num55 = num52;
                    Integer num56 = num53;
                    Integer num57 = num39;
                    Integer num58 = num40;
                    Integer num59 = num45;
                    String str32 = str25;
                    Integer num60 = num50;
                    Integer num61 = num51;
                    Long l5 = l4;
                    String str33 = str23;
                    Integer num62 = num44;
                    byte[] bArr4 = bArr3;
                    String str34 = str28;
                    Integer num63 = num49;
                    Integer num64 = num37;
                    Integer num65 = num38;
                    ddz ddzVar7 = ddzVar6;
                    Integer num66 = num43;
                    Integer num67 = num47;
                    String str35 = str22;
                    Integer num68 = num42;
                    Integer num69 = num46;
                    String str36 = str29;
                    str3 = str24;
                    ddzVar = ddzVar3;
                    num36 = num54;
                    apcVar = apcVar;
                    ddzVar5 = ddzVar5;
                    str21 = str21;
                    num48 = num48;
                    num43 = num66;
                    num38 = num65;
                    num49 = num63;
                    bArr3 = bArr4;
                    str23 = str33;
                    num51 = num61;
                    str25 = str32;
                    num40 = num58;
                    num53 = num56;
                    str27 = str31;
                    str4 = str36;
                    num46 = num69;
                    num42 = num68;
                    str22 = str35;
                    num47 = num67;
                    ddzVar6 = ddzVar7;
                    num37 = num64;
                    str28 = str34;
                    num44 = num62;
                    l4 = l5;
                    num50 = num60;
                    num45 = num59;
                    num39 = num57;
                    num52 = num55;
                    str26 = str30;
                    i4 = i4;
                    bipVar2 = bipVar2;
                    z = false;
                    num35 = num35;
                    str20 = str2;
                    str19 = str;
                    ddzVar3 = ddzVar;
                    str24 = str3;
                    str29 = str4;
                    break;
                case 0:
                    Integer num70 = num47;
                    String str37 = str22;
                    Integer num71 = num42;
                    Integer num72 = num46;
                    String str38 = str29;
                    str3 = str24;
                    String str39 = str26;
                    Integer num73 = num52;
                    Integer num74 = num39;
                    Integer num75 = num45;
                    Integer num76 = num50;
                    Long l6 = l4;
                    String str40 = str27;
                    Integer num77 = num53;
                    Integer num78 = num40;
                    String str41 = str25;
                    Integer num79 = num51;
                    String str42 = str23;
                    byte[] bArr5 = bArr3;
                    Integer num80 = num49;
                    Integer num81 = num38;
                    Integer num82 = num43;
                    num = num35;
                    ddzVar = ddzVar3;
                    num36 = num54;
                    apcVar = apcVar;
                    ddzVar5 = ddzVar5;
                    str21 = str21;
                    num48 = num48;
                    num43 = num82;
                    num38 = num81;
                    num49 = num80;
                    bArr3 = bArr5;
                    str23 = str42;
                    num51 = num79;
                    str25 = str41;
                    num40 = num78;
                    num53 = num77;
                    str27 = str40;
                    str4 = str38;
                    num46 = num72;
                    num42 = num71;
                    str22 = str37;
                    num47 = num70;
                    ddzVar6 = ddzVar6;
                    num37 = num37;
                    str28 = str28;
                    num44 = num44;
                    l4 = l6;
                    num50 = num76;
                    num45 = num75;
                    num39 = num74;
                    num52 = num73;
                    str26 = str39;
                    num41 = (Integer) acmVarP.i(dfxVar, 0, bqj.b, num41);
                    bipVar2 = bipVar2;
                    str20 = str20;
                    str19 = str19;
                    i4 |= 1;
                    num35 = num;
                    ddzVar3 = ddzVar;
                    str24 = str3;
                    str29 = str4;
                    break;
                case 1:
                    Integer num83 = num35;
                    String str43 = str27;
                    Integer num84 = num53;
                    Integer num85 = num40;
                    String str44 = str25;
                    Integer num86 = num51;
                    String str45 = str23;
                    byte[] bArr6 = bArr3;
                    Integer num87 = num49;
                    Integer num88 = num38;
                    Integer num89 = num43;
                    Integer num90 = num47;
                    String str46 = str22;
                    Integer num91 = num42;
                    Integer num92 = num46;
                    String str47 = str29;
                    str3 = str24;
                    str5 = str26;
                    num2 = num52;
                    num3 = num39;
                    num4 = num45;
                    num5 = num50;
                    l = l4;
                    ddzVar = (ddz) acmVarP.i(dfxVar, 1, ddx.b, ddzVar3);
                    bipVar2 = bipVar2;
                    num35 = num83;
                    str20 = str20;
                    str19 = str19;
                    i4 |= 2;
                    num36 = num54;
                    apcVar = apcVar;
                    ddzVar5 = ddzVar5;
                    str21 = str21;
                    num48 = num48;
                    num43 = num89;
                    num38 = num88;
                    num49 = num87;
                    bArr3 = bArr6;
                    str23 = str45;
                    num51 = num86;
                    str25 = str44;
                    num40 = num85;
                    num53 = num84;
                    str27 = str43;
                    str4 = str47;
                    num46 = num92;
                    num42 = num91;
                    str22 = str46;
                    num47 = num90;
                    ddzVar6 = ddzVar6;
                    num37 = num37;
                    str28 = str28;
                    num44 = num44;
                    l4 = l;
                    num50 = num5;
                    num45 = num4;
                    num39 = num3;
                    num52 = num2;
                    str26 = str5;
                    ddzVar3 = ddzVar;
                    str24 = str3;
                    str29 = str4;
                    break;
                case 2:
                    num6 = num35;
                    str6 = str27;
                    num7 = num53;
                    num8 = num40;
                    str7 = str25;
                    num9 = num51;
                    str8 = str23;
                    bArr = bArr3;
                    num10 = num49;
                    num11 = num38;
                    num12 = num43;
                    num13 = num48;
                    String str48 = str20;
                    Integer num93 = num46;
                    String str49 = str29;
                    str3 = str24;
                    str9 = str26;
                    num14 = num52;
                    num15 = num39;
                    num16 = num45;
                    num17 = num50;
                    l2 = l4;
                    num18 = num44;
                    str10 = str28;
                    num19 = num37;
                    ddzVar2 = ddzVar6;
                    num20 = num47;
                    ddzVar4 = (ddz) acmVarP.i(dfxVar, 2, ddx.b, ddzVar4);
                    ddzVar = ddzVar3;
                    str4 = str49;
                    bipVar2 = bipVar2;
                    num36 = num54;
                    str19 = str19;
                    i4 |= 4;
                    num46 = num93;
                    apcVar = apcVar;
                    str20 = str48;
                    ddzVar5 = ddzVar5;
                    num42 = num42;
                    str22 = str22;
                    str21 = str21;
                    num47 = num20;
                    num48 = num13;
                    ddzVar6 = ddzVar2;
                    num43 = num12;
                    num37 = num19;
                    num38 = num11;
                    str28 = str10;
                    num49 = num10;
                    num44 = num18;
                    bArr3 = bArr;
                    l4 = l2;
                    str23 = str8;
                    num50 = num17;
                    num51 = num9;
                    num45 = num16;
                    str25 = str7;
                    num39 = num15;
                    num40 = num8;
                    num52 = num14;
                    num53 = num7;
                    str27 = str6;
                    str26 = str9;
                    num35 = num6;
                    ddzVar3 = ddzVar;
                    str24 = str3;
                    str29 = str4;
                    break;
                case 3:
                    String str50 = str20;
                    Integer num94 = num46;
                    String str51 = str29;
                    str3 = str24;
                    String str52 = str26;
                    Integer num95 = num52;
                    Integer num96 = num39;
                    Integer num97 = num45;
                    Integer num98 = num50;
                    Long l7 = l4;
                    Integer num99 = num44;
                    String str53 = str28;
                    Integer num100 = num37;
                    num = num35;
                    str11 = str27;
                    num21 = num53;
                    num22 = num40;
                    str12 = str25;
                    Integer num101 = num51;
                    String str54 = str23;
                    byte[] bArr7 = bArr3;
                    Integer num102 = num49;
                    Integer num103 = num38;
                    num42 = (Integer) acmVarP.i(dfxVar, 3, bqj.b, num42);
                    ddzVar = ddzVar3;
                    str4 = str51;
                    bipVar2 = bipVar2;
                    str22 = str22;
                    str19 = str19;
                    num46 = num94;
                    i4 |= 8;
                    num47 = num47;
                    num36 = num54;
                    str20 = str50;
                    ddzVar6 = ddzVar6;
                    apcVar = apcVar;
                    num37 = num100;
                    ddzVar5 = ddzVar5;
                    str28 = str53;
                    str21 = str21;
                    num44 = num99;
                    num48 = num48;
                    l4 = l7;
                    num43 = num43;
                    num50 = num98;
                    num38 = num103;
                    num45 = num97;
                    num49 = num102;
                    num39 = num96;
                    bArr3 = bArr7;
                    num52 = num95;
                    str23 = str54;
                    str26 = str52;
                    num51 = num101;
                    str25 = str12;
                    num40 = num22;
                    num53 = num21;
                    str27 = str11;
                    num35 = num;
                    ddzVar3 = ddzVar;
                    str24 = str3;
                    str29 = str4;
                    break;
                case 4:
                    num6 = num35;
                    str6 = str27;
                    num7 = num53;
                    num8 = num40;
                    str7 = str25;
                    num9 = num51;
                    str8 = str23;
                    bArr = bArr3;
                    num10 = num49;
                    num11 = num38;
                    num12 = num43;
                    num13 = num48;
                    String str55 = str20;
                    Integer num104 = num46;
                    String str56 = str29;
                    str3 = str24;
                    str9 = str26;
                    num14 = num52;
                    num15 = num39;
                    num16 = num45;
                    num17 = num50;
                    l2 = l4;
                    num18 = num44;
                    str10 = str28;
                    num19 = num37;
                    ddzVar2 = ddzVar6;
                    num20 = num47;
                    ddzVar5 = (ddz) acmVarP.i(dfxVar, 4, ddx.b, ddzVar5);
                    ddzVar = ddzVar3;
                    str4 = str56;
                    bipVar2 = bipVar2;
                    num36 = num54;
                    str19 = str19;
                    num46 = num104;
                    i4 |= 16;
                    apcVar = apcVar;
                    str22 = str22;
                    str21 = str21;
                    str20 = str55;
                    num47 = num20;
                    num48 = num13;
                    ddzVar6 = ddzVar2;
                    num43 = num12;
                    num37 = num19;
                    num38 = num11;
                    str28 = str10;
                    num49 = num10;
                    num44 = num18;
                    bArr3 = bArr;
                    l4 = l2;
                    str23 = str8;
                    num50 = num17;
                    num51 = num9;
                    num45 = num16;
                    str25 = str7;
                    num39 = num15;
                    num40 = num8;
                    num52 = num14;
                    num53 = num7;
                    str27 = str6;
                    str26 = str9;
                    num35 = num6;
                    ddzVar3 = ddzVar;
                    str24 = str3;
                    str29 = str4;
                    break;
                case 5:
                    String str57 = str20;
                    Integer num105 = num46;
                    String str58 = str29;
                    str3 = str24;
                    String str59 = str26;
                    Integer num106 = num52;
                    Integer num107 = num39;
                    Integer num108 = num45;
                    Integer num109 = num50;
                    Long l8 = l4;
                    Integer num110 = num44;
                    String str60 = str28;
                    Integer num111 = num37;
                    Integer num112 = num48;
                    num = num35;
                    str11 = str27;
                    num21 = num53;
                    num22 = num40;
                    str12 = str25;
                    num23 = num51;
                    str13 = str23;
                    bArr2 = bArr3;
                    ddzVar6 = (ddz) acmVarP.i(dfxVar, 5, ddx.b, ddzVar6);
                    ddzVar = ddzVar3;
                    str4 = str58;
                    bipVar2 = bipVar2;
                    num37 = num111;
                    str19 = str19;
                    num46 = num105;
                    i4 |= 32;
                    str28 = str60;
                    num36 = num54;
                    str20 = str57;
                    apcVar = apcVar;
                    num44 = num110;
                    str22 = str22;
                    l4 = l8;
                    num47 = num47;
                    num50 = num109;
                    str21 = str21;
                    num45 = num108;
                    num48 = num112;
                    num39 = num107;
                    num43 = num43;
                    num52 = num106;
                    num38 = num38;
                    str26 = str59;
                    num49 = num49;
                    bArr3 = bArr2;
                    str23 = str13;
                    num51 = num23;
                    str25 = str12;
                    num40 = num22;
                    num53 = num21;
                    str27 = str11;
                    num35 = num;
                    ddzVar3 = ddzVar;
                    str24 = str3;
                    str29 = str4;
                    break;
                case 6:
                    Integer num113 = num35;
                    String str61 = str27;
                    Integer num114 = num53;
                    Integer num115 = num40;
                    String str62 = str25;
                    Integer num116 = num51;
                    String str63 = str23;
                    byte[] bArr8 = bArr3;
                    Integer num117 = num49;
                    Integer num118 = num38;
                    String str64 = str28;
                    Integer num119 = num37;
                    Integer num120 = num48;
                    String str65 = str20;
                    Integer num121 = num46;
                    String str66 = str29;
                    str3 = str24;
                    str5 = str26;
                    num2 = num52;
                    num3 = num39;
                    num4 = num45;
                    num5 = num50;
                    num43 = (Integer) acmVarP.i(dfxVar, 6, bqj.b, num43);
                    ddzVar = ddzVar3;
                    str4 = str66;
                    bipVar2 = bipVar2;
                    num38 = num118;
                    str19 = str19;
                    num46 = num121;
                    i4 |= 64;
                    num49 = num117;
                    num36 = num54;
                    str20 = str65;
                    apcVar = apcVar;
                    bArr3 = bArr8;
                    str22 = str22;
                    str23 = str63;
                    num47 = num47;
                    num51 = num116;
                    str21 = str21;
                    num48 = num120;
                    str25 = str62;
                    num37 = num119;
                    num40 = num115;
                    str28 = str64;
                    num53 = num114;
                    str27 = str61;
                    num44 = num44;
                    l4 = l4;
                    num35 = num113;
                    num50 = num5;
                    num45 = num4;
                    num39 = num3;
                    num52 = num2;
                    str26 = str5;
                    ddzVar3 = ddzVar;
                    str24 = str3;
                    str29 = str4;
                    break;
                case 7:
                    String str67 = str20;
                    Integer num122 = num46;
                    String str68 = str29;
                    str3 = str24;
                    String str69 = str26;
                    Integer num123 = num52;
                    Integer num124 = num39;
                    Integer num125 = num45;
                    Integer num126 = num50;
                    Long l9 = l4;
                    Integer num127 = num49;
                    Integer num128 = num38;
                    String str70 = str28;
                    Integer num129 = num37;
                    Integer num130 = num48;
                    num = num35;
                    str11 = str27;
                    num21 = num53;
                    num22 = num40;
                    str12 = str25;
                    num23 = num51;
                    str13 = str23;
                    bArr2 = bArr3;
                    num44 = (Integer) acmVarP.i(dfxVar, 7, bqj.b, num44);
                    ddzVar = ddzVar3;
                    str4 = str68;
                    bipVar2 = bipVar2;
                    l4 = l9;
                    str19 = str19;
                    num46 = num122;
                    i4 |= 128;
                    num50 = num126;
                    num36 = num54;
                    str20 = str67;
                    apcVar = apcVar;
                    num45 = num125;
                    str22 = str22;
                    num39 = num124;
                    num47 = num47;
                    num52 = num123;
                    str21 = str21;
                    num48 = num130;
                    str26 = str69;
                    num37 = num129;
                    str28 = str70;
                    num38 = num128;
                    num49 = num127;
                    bArr3 = bArr2;
                    str23 = str13;
                    num51 = num23;
                    str25 = str12;
                    num40 = num22;
                    num53 = num21;
                    str27 = str11;
                    num35 = num;
                    ddzVar3 = ddzVar;
                    str24 = str3;
                    str29 = str4;
                    break;
                case 8:
                    Integer num131 = num35;
                    String str71 = str27;
                    Integer num132 = num53;
                    Integer num133 = num40;
                    String str72 = str25;
                    Integer num134 = num51;
                    String str73 = str23;
                    Integer num135 = num50;
                    l = l4;
                    Integer num136 = num49;
                    Integer num137 = num38;
                    String str74 = str28;
                    Integer num138 = num37;
                    Integer num139 = num48;
                    String str75 = str20;
                    Integer num140 = num46;
                    String str76 = str29;
                    str3 = str24;
                    str5 = str26;
                    num2 = num52;
                    num3 = num39;
                    num4 = num45;
                    num5 = num135;
                    bArr3 = (byte[]) acmVarP.i(dfxVar, 8, rx.j, bArr3);
                    ddzVar = ddzVar3;
                    str4 = str76;
                    bipVar2 = bipVar2;
                    str23 = str73;
                    str19 = str19;
                    num46 = num140;
                    i4 |= 256;
                    num51 = num134;
                    num36 = num54;
                    str20 = str75;
                    apcVar = apcVar;
                    str25 = str72;
                    str22 = str22;
                    num40 = num133;
                    num47 = num47;
                    num53 = num132;
                    str21 = str21;
                    str27 = str71;
                    num48 = num139;
                    num37 = num138;
                    num35 = num131;
                    str28 = str74;
                    num38 = num137;
                    num49 = num136;
                    l4 = l;
                    num50 = num5;
                    num45 = num4;
                    num39 = num3;
                    num52 = num2;
                    str26 = str5;
                    ddzVar3 = ddzVar;
                    str24 = str3;
                    str29 = str4;
                    break;
                case 9:
                    String str77 = str20;
                    Integer num141 = num46;
                    String str78 = str29;
                    str3 = str24;
                    String str79 = str26;
                    Integer num142 = num52;
                    Integer num143 = num39;
                    Integer num144 = num51;
                    str13 = str23;
                    Integer num145 = num50;
                    Long l10 = l4;
                    Integer num146 = num49;
                    Integer num147 = num38;
                    String str80 = str28;
                    Integer num148 = num37;
                    Integer num149 = num48;
                    num = num35;
                    str11 = str27;
                    num21 = num53;
                    num22 = num40;
                    str12 = str25;
                    num23 = num144;
                    num45 = (Integer) acmVarP.i(dfxVar, 9, bqj.b, num45);
                    ddzVar = ddzVar3;
                    str4 = str78;
                    bipVar2 = bipVar2;
                    num39 = num143;
                    str19 = str19;
                    num46 = num141;
                    i4 |= 512;
                    num52 = num142;
                    num36 = num54;
                    str20 = str77;
                    apcVar = apcVar;
                    str26 = str79;
                    str22 = str22;
                    num47 = num47;
                    str21 = str21;
                    num48 = num149;
                    num37 = num148;
                    str28 = str80;
                    num38 = num147;
                    num49 = num146;
                    l4 = l10;
                    num50 = num145;
                    str23 = str13;
                    num51 = num23;
                    str25 = str12;
                    num40 = num22;
                    num53 = num21;
                    str27 = str11;
                    num35 = num;
                    ddzVar3 = ddzVar;
                    str24 = str3;
                    str29 = str4;
                    break;
                case 10:
                    Integer num150 = num35;
                    String str81 = str27;
                    Integer num151 = num53;
                    Integer num152 = num40;
                    Integer num153 = num52;
                    num3 = num39;
                    Integer num154 = num51;
                    String str82 = str23;
                    Integer num155 = num50;
                    Long l11 = l4;
                    Integer num156 = num49;
                    Integer num157 = num38;
                    String str83 = str28;
                    Integer num158 = num37;
                    Integer num159 = num48;
                    String str84 = str20;
                    Integer num160 = num46;
                    String str85 = str29;
                    str3 = str24;
                    str5 = str26;
                    num2 = num153;
                    str25 = (String) acmVarP.i(dfxVar, 10, dnh.b, str25);
                    ddzVar = ddzVar3;
                    str4 = str85;
                    bipVar2 = bipVar2;
                    num40 = num152;
                    str19 = str19;
                    num46 = num160;
                    i4 |= 1024;
                    num53 = num151;
                    num36 = num54;
                    str20 = str84;
                    str27 = str81;
                    apcVar = apcVar;
                    str22 = str22;
                    num35 = num150;
                    num47 = num47;
                    str21 = str21;
                    num48 = num159;
                    num37 = num158;
                    str28 = str83;
                    num38 = num157;
                    num49 = num156;
                    l4 = l11;
                    num50 = num155;
                    str23 = str82;
                    num51 = num154;
                    num39 = num3;
                    num52 = num2;
                    str26 = str5;
                    ddzVar3 = ddzVar;
                    str24 = str3;
                    str29 = str4;
                    break;
                case 11:
                    String str86 = str20;
                    Integer num161 = num46;
                    String str87 = str29;
                    str3 = str24;
                    Integer num162 = num53;
                    num22 = num40;
                    Integer num163 = num52;
                    Integer num164 = num39;
                    Integer num165 = num51;
                    String str88 = str23;
                    Integer num166 = num50;
                    Long l12 = l4;
                    Integer num167 = num49;
                    Integer num168 = num38;
                    String str89 = str28;
                    Integer num169 = num37;
                    Integer num170 = num48;
                    num = num35;
                    str11 = str27;
                    num21 = num162;
                    str26 = (String) acmVarP.i(dfxVar, 11, dnh.b, str26);
                    ddzVar = ddzVar3;
                    str4 = str87;
                    bipVar2 = bipVar2;
                    num36 = num54;
                    i4 |= 2048;
                    num46 = num161;
                    apcVar = apcVar;
                    str22 = str22;
                    str20 = str86;
                    str19 = str19;
                    num47 = num47;
                    str21 = str21;
                    num48 = num170;
                    num37 = num169;
                    str28 = str89;
                    num38 = num168;
                    num49 = num167;
                    l4 = l12;
                    num50 = num166;
                    str23 = str88;
                    num51 = num165;
                    num39 = num164;
                    num52 = num163;
                    num40 = num22;
                    num53 = num21;
                    str27 = str11;
                    num35 = num;
                    ddzVar3 = ddzVar;
                    str24 = str3;
                    str29 = str4;
                    break;
                case 12:
                    Integer num171 = num35;
                    String str90 = str29;
                    str3 = str24;
                    num24 = num53;
                    num25 = num40;
                    num26 = num52;
                    num27 = num39;
                    num28 = num51;
                    str14 = str23;
                    num29 = num50;
                    l3 = l4;
                    num30 = num49;
                    num31 = num38;
                    str15 = str28;
                    num32 = num37;
                    num33 = num48;
                    str16 = str21;
                    num34 = num47;
                    str17 = str20;
                    str27 = (String) acmVarP.i(dfxVar, 12, dnh.b, str27);
                    ddzVar = ddzVar3;
                    str4 = str90;
                    bipVar2 = bipVar2;
                    num36 = num54;
                    str19 = str19;
                    num46 = num46;
                    i4 |= 4096;
                    apcVar = apcVar;
                    str22 = str22;
                    num35 = num171;
                    str20 = str17;
                    num47 = num34;
                    str21 = str16;
                    num48 = num33;
                    num37 = num32;
                    str28 = str15;
                    num38 = num31;
                    num49 = num30;
                    l4 = l3;
                    num50 = num29;
                    str23 = str14;
                    num51 = num28;
                    num39 = num27;
                    num52 = num26;
                    num40 = num25;
                    num53 = num24;
                    ddzVar3 = ddzVar;
                    str24 = str3;
                    str29 = str4;
                    break;
                case 13:
                    str17 = str20;
                    Integer num172 = num35;
                    String str91 = str29;
                    str3 = str24;
                    num24 = num53;
                    num25 = num40;
                    num26 = num52;
                    num27 = num39;
                    num28 = num51;
                    str14 = str23;
                    num29 = num50;
                    l3 = l4;
                    num30 = num49;
                    num31 = num38;
                    str15 = str28;
                    num32 = num37;
                    num33 = num48;
                    str16 = str21;
                    num34 = num47;
                    num46 = (Integer) acmVarP.i(dfxVar, 13, bqj.b, num46);
                    str4 = str91;
                    ddzVar = ddzVar3;
                    bipVar2 = bipVar2;
                    num36 = num54;
                    num35 = num172;
                    str19 = str19;
                    i4 |= 8192;
                    apcVar = apcVar;
                    str22 = str22;
                    str20 = str17;
                    num47 = num34;
                    str21 = str16;
                    num48 = num33;
                    num37 = num32;
                    str28 = str15;
                    num38 = num31;
                    num49 = num30;
                    l4 = l3;
                    num50 = num29;
                    str23 = str14;
                    num51 = num28;
                    num39 = num27;
                    num52 = num26;
                    num40 = num25;
                    num53 = num24;
                    ddzVar3 = ddzVar;
                    str24 = str3;
                    str29 = str4;
                    break;
                case 14:
                    Integer num173 = num35;
                    String str92 = str29;
                    str3 = str24;
                    num24 = num53;
                    num25 = num40;
                    num26 = num52;
                    num27 = num39;
                    num28 = num51;
                    str14 = str23;
                    num29 = num50;
                    l3 = l4;
                    num30 = num49;
                    num31 = num38;
                    str15 = str28;
                    num32 = num37;
                    num33 = num48;
                    str4 = str92;
                    apcVar = (apc) acmVarP.i(dfxVar, 14, apa.b, apcVar);
                    i4 |= 16384;
                    ddzVar = ddzVar3;
                    str22 = str22;
                    num35 = num173;
                    bipVar2 = bipVar2;
                    num36 = num54;
                    num47 = num47;
                    str21 = str21;
                    str20 = str20;
                    str19 = str19;
                    num48 = num33;
                    num37 = num32;
                    str28 = str15;
                    num38 = num31;
                    num49 = num30;
                    l4 = l3;
                    num50 = num29;
                    str23 = str14;
                    num51 = num28;
                    num39 = num27;
                    num52 = num26;
                    num40 = num25;
                    num53 = num24;
                    ddzVar3 = ddzVar;
                    str24 = str3;
                    str29 = str4;
                    break;
                case 15:
                    Integer num174 = num35;
                    String str93 = str29;
                    str3 = str24;
                    num24 = num53;
                    num25 = num40;
                    num26 = num52;
                    num27 = num39;
                    num28 = num51;
                    str14 = str23;
                    num29 = num50;
                    l3 = l4;
                    num30 = num49;
                    num31 = num38;
                    str15 = str28;
                    bipVar2 = bipVar2;
                    str4 = str93;
                    num47 = (Integer) acmVarP.i(dfxVar, 15, bqj.b, num47);
                    i4 |= 32768;
                    ddzVar = ddzVar3;
                    str21 = str21;
                    num35 = num174;
                    str19 = str19;
                    num36 = num54;
                    num48 = num48;
                    num37 = num37;
                    str20 = str20;
                    str28 = str15;
                    num38 = num31;
                    num49 = num30;
                    l4 = l3;
                    num50 = num29;
                    str23 = str14;
                    num51 = num28;
                    num39 = num27;
                    num52 = num26;
                    num40 = num25;
                    num53 = num24;
                    ddzVar3 = ddzVar;
                    str24 = str3;
                    str29 = str4;
                    break;
                case 16:
                    Integer num175 = num35;
                    String str94 = str29;
                    str3 = str24;
                    num24 = num53;
                    num25 = num40;
                    num26 = num52;
                    num27 = num39;
                    num28 = num51;
                    str14 = str23;
                    num29 = num50;
                    l3 = l4;
                    num30 = num49;
                    str4 = str94;
                    num48 = (Integer) acmVarP.i(dfxVar, 16, bqj.b, num48);
                    i4 |= 65536;
                    ddzVar = ddzVar3;
                    num37 = num37;
                    num35 = num175;
                    bipVar2 = bipVar2;
                    num36 = num54;
                    str28 = str28;
                    num38 = num38;
                    str20 = str20;
                    str19 = str19;
                    num49 = num30;
                    l4 = l3;
                    num50 = num29;
                    str23 = str14;
                    num51 = num28;
                    num39 = num27;
                    num52 = num26;
                    num40 = num25;
                    num53 = num24;
                    ddzVar3 = ddzVar;
                    str24 = str3;
                    str29 = str4;
                    break;
                case 17:
                    Integer num176 = num35;
                    String str95 = str29;
                    str3 = str24;
                    num24 = num53;
                    num25 = num40;
                    num26 = num52;
                    num27 = num39;
                    num28 = num51;
                    str14 = str23;
                    num29 = num50;
                    str4 = str95;
                    str28 = (String) acmVarP.i(dfxVar, 17, dnh.b, str28);
                    i4 |= 131072;
                    ddzVar = ddzVar3;
                    num38 = num38;
                    num35 = num176;
                    bipVar2 = bipVar2;
                    num36 = num54;
                    num49 = num49;
                    l4 = l4;
                    str20 = str20;
                    str19 = str19;
                    num50 = num29;
                    str23 = str14;
                    num51 = num28;
                    num39 = num27;
                    num52 = num26;
                    num40 = num25;
                    num53 = num24;
                    ddzVar3 = ddzVar;
                    str24 = str3;
                    str29 = str4;
                    break;
                case 18:
                    Integer num177 = num35;
                    String str96 = str29;
                    str3 = str24;
                    num24 = num53;
                    num25 = num40;
                    num26 = num52;
                    num27 = num39;
                    num28 = num51;
                    str4 = str96;
                    num49 = (Integer) acmVarP.i(dfxVar, 18, bqj.b, num49);
                    i4 |= 262144;
                    ddzVar = ddzVar3;
                    l4 = l4;
                    num35 = num177;
                    bipVar2 = bipVar2;
                    num36 = num54;
                    num50 = num50;
                    str23 = str23;
                    str20 = str20;
                    str19 = str19;
                    num51 = num28;
                    num39 = num27;
                    num52 = num26;
                    num40 = num25;
                    num53 = num24;
                    ddzVar3 = ddzVar;
                    str24 = str3;
                    str29 = str4;
                    break;
                case 19:
                    Integer num178 = num35;
                    String str97 = str29;
                    str3 = str24;
                    num24 = num53;
                    num25 = num40;
                    num26 = num52;
                    str4 = str97;
                    num50 = (Integer) acmVarP.i(dfxVar, 19, bqj.b, num50);
                    i4 |= Opcodes.ASM8;
                    ddzVar = ddzVar3;
                    str23 = str23;
                    num35 = num178;
                    bipVar2 = bipVar2;
                    num36 = num54;
                    num51 = num51;
                    num39 = num39;
                    str20 = str20;
                    str19 = str19;
                    num52 = num26;
                    num40 = num25;
                    num53 = num24;
                    ddzVar3 = ddzVar;
                    str24 = str3;
                    str29 = str4;
                    break;
                case 20:
                    Integer num179 = num35;
                    String str98 = str29;
                    str3 = str24;
                    num24 = num53;
                    str4 = str98;
                    num51 = (Integer) acmVarP.i(dfxVar, 20, bqj.b, num51);
                    i4 |= 1048576;
                    ddzVar = ddzVar3;
                    num39 = num39;
                    num35 = num179;
                    bipVar2 = bipVar2;
                    num36 = num54;
                    num52 = num52;
                    num40 = num40;
                    str20 = str20;
                    str19 = str19;
                    num53 = num24;
                    ddzVar3 = ddzVar;
                    str24 = str3;
                    str29 = str4;
                    break;
                case 21:
                    Integer num180 = num35;
                    String str99 = str29;
                    str3 = str24;
                    str4 = str99;
                    num52 = (Integer) acmVarP.i(dfxVar, 21, bqj.b, num52);
                    i4 |= 2097152;
                    ddzVar = ddzVar3;
                    num40 = num40;
                    num35 = num180;
                    bipVar2 = bipVar2;
                    num36 = num54;
                    num53 = num53;
                    str20 = str20;
                    str19 = str19;
                    ddzVar3 = ddzVar;
                    str24 = str3;
                    str29 = str4;
                    break;
                case 22:
                    str = str19;
                    str2 = str20;
                    Integer num181 = num35;
                    String str100 = str29;
                    str3 = str24;
                    str4 = str100;
                    num53 = (Integer) acmVarP.i(dfxVar, 22, bqj.b, num53);
                    i4 |= 4194304;
                    ddzVar = ddzVar3;
                    num35 = num181;
                    bipVar2 = bipVar2;
                    num36 = num54;
                    str20 = str2;
                    str19 = str;
                    ddzVar3 = ddzVar;
                    str24 = str3;
                    str29 = str4;
                    break;
                case 23:
                    bipVar2 = bipVar2;
                    str4 = (String) acmVarP.i(dfxVar, 23, dnh.b, str29);
                    i4 |= 8388608;
                    str3 = str24;
                    ddzVar = ddzVar3;
                    num35 = num35;
                    str19 = str19;
                    num36 = num54;
                    str20 = str20;
                    ddzVar3 = ddzVar;
                    str24 = str3;
                    str29 = str4;
                    break;
                case 24:
                    str18 = str19;
                    num36 = (Integer) acmVarP.i(dfxVar, 24, bqj.b, num54);
                    bipVar2 = bipVar2;
                    i4 |= Http2Connection.OKHTTP_CLIENT_WINDOW_SIZE;
                    ddzVar = ddzVar3;
                    str4 = str29;
                    str20 = str20;
                    str19 = str18;
                    str3 = str24;
                    ddzVar3 = ddzVar;
                    str24 = str3;
                    str29 = str4;
                    break;
                case 25:
                    str18 = str19;
                    bipVar2 = (bip) acmVarP.i(dfxVar, 25, bin.b, bipVar2);
                    i4 |= 33554432;
                    ddzVar = ddzVar3;
                    str4 = str29;
                    num36 = num54;
                    str19 = str18;
                    str3 = str24;
                    ddzVar3 = ddzVar;
                    str24 = str3;
                    str29 = str4;
                    break;
                case 26:
                    bipVar = bipVar2;
                    str22 = (String) acmVarP.i(dfxVar, 26, dnh.b, str22);
                    i = 67108864;
                    i4 |= i;
                    ddzVar = ddzVar3;
                    str4 = str29;
                    num36 = num54;
                    bipVar2 = bipVar;
                    str3 = str24;
                    ddzVar3 = ddzVar;
                    str24 = str3;
                    str29 = str4;
                    break;
                case 27:
                    bipVar = bipVar2;
                    str21 = (String) acmVarP.i(dfxVar, 27, dnh.b, str21);
                    i = 134217728;
                    i4 |= i;
                    ddzVar = ddzVar3;
                    str4 = str29;
                    num36 = num54;
                    bipVar2 = bipVar;
                    str3 = str24;
                    ddzVar3 = ddzVar;
                    str24 = str3;
                    str29 = str4;
                    break;
                case 28:
                    bipVar = bipVar2;
                    num37 = (Integer) acmVarP.i(dfxVar, 28, bqj.b, num37);
                    i = 268435456;
                    i4 |= i;
                    ddzVar = ddzVar3;
                    str4 = str29;
                    num36 = num54;
                    bipVar2 = bipVar;
                    str3 = str24;
                    ddzVar3 = ddzVar;
                    str24 = str3;
                    str29 = str4;
                    break;
                case 29:
                    bipVar = bipVar2;
                    num38 = (Integer) acmVarP.i(dfxVar, 29, bqj.b, num38);
                    i = 536870912;
                    i4 |= i;
                    ddzVar = ddzVar3;
                    str4 = str29;
                    num36 = num54;
                    bipVar2 = bipVar;
                    str3 = str24;
                    ddzVar3 = ddzVar;
                    str24 = str3;
                    str29 = str4;
                    break;
                case 30:
                    bipVar = bipVar2;
                    l4 = (Long) acmVarP.i(dfxVar, 30, bya.b, l4);
                    i = 1073741824;
                    i4 |= i;
                    ddzVar = ddzVar3;
                    str4 = str29;
                    num36 = num54;
                    bipVar2 = bipVar;
                    str3 = str24;
                    ddzVar3 = ddzVar;
                    str24 = str3;
                    str29 = str4;
                    break;
                case 31:
                    bipVar = bipVar2;
                    str23 = (String) acmVarP.i(dfxVar, 31, dnh.b, str23);
                    i = Integer.MIN_VALUE;
                    i4 |= i;
                    ddzVar = ddzVar3;
                    str4 = str29;
                    num36 = num54;
                    bipVar2 = bipVar;
                    str3 = str24;
                    ddzVar3 = ddzVar;
                    str24 = str3;
                    str29 = str4;
                    break;
                case 32:
                    bipVar = bipVar2;
                    num39 = (Integer) acmVarP.i(dfxVar, 32, bqj.b, num39);
                    i2 = i3 | 1;
                    i3 = i2;
                    ddzVar = ddzVar3;
                    str4 = str29;
                    num36 = num54;
                    bipVar2 = bipVar;
                    str3 = str24;
                    ddzVar3 = ddzVar;
                    str24 = str3;
                    str29 = str4;
                    break;
                case 33:
                    bipVar = bipVar2;
                    num40 = (Integer) acmVarP.i(dfxVar, 33, bqj.b, num40);
                    i2 = i3 | 2;
                    i3 = i2;
                    ddzVar = ddzVar3;
                    str4 = str29;
                    num36 = num54;
                    bipVar2 = bipVar;
                    str3 = str24;
                    ddzVar3 = ddzVar;
                    str24 = str3;
                    str29 = str4;
                    break;
                case 34:
                    bipVar = bipVar2;
                    str24 = (String) acmVarP.i(dfxVar, 34, dnh.b, str24);
                    i2 = i3 | 4;
                    i3 = i2;
                    ddzVar = ddzVar3;
                    str4 = str29;
                    num36 = num54;
                    bipVar2 = bipVar;
                    str3 = str24;
                    ddzVar3 = ddzVar;
                    str24 = str3;
                    str29 = str4;
                    break;
                case 35:
                    bipVar = bipVar2;
                    num35 = (Integer) acmVarP.i(dfxVar, 35, bqj.b, num35);
                    i2 = i3 | 8;
                    i3 = i2;
                    ddzVar = ddzVar3;
                    str4 = str29;
                    num36 = num54;
                    bipVar2 = bipVar;
                    str3 = str24;
                    ddzVar3 = ddzVar;
                    str24 = str3;
                    str29 = str4;
                    break;
                case 36:
                    bipVar = bipVar2;
                    str20 = (String) acmVarP.i(dfxVar, 36, dnh.b, str20);
                    i2 = i3 | 16;
                    i3 = i2;
                    ddzVar = ddzVar3;
                    str4 = str29;
                    num36 = num54;
                    bipVar2 = bipVar;
                    str3 = str24;
                    ddzVar3 = ddzVar;
                    str24 = str3;
                    str29 = str4;
                    break;
                case 37:
                    bipVar = bipVar2;
                    str19 = (String) acmVarP.i(dfxVar, 37, dnh.b, str19);
                    i2 = i3 | 32;
                    i3 = i2;
                    ddzVar = ddzVar3;
                    str4 = str29;
                    num36 = num54;
                    bipVar2 = bipVar;
                    str3 = str24;
                    ddzVar3 = ddzVar;
                    str24 = str3;
                    str29 = str4;
                    break;
                default:
                    throw new bsd(iF);
            }
        }
        int i5 = i4;
        bip bipVar3 = bipVar2;
        String str101 = str19;
        String str102 = str20;
        Integer num182 = num35;
        Integer num183 = num41;
        ddz ddzVar8 = ddzVar4;
        String str103 = str26;
        String str104 = str27;
        Integer num184 = num52;
        Integer num185 = num53;
        Integer num186 = num39;
        Integer num187 = num40;
        Integer num188 = num45;
        String str105 = str25;
        Integer num189 = num50;
        Integer num190 = num51;
        Long l13 = l4;
        String str106 = str23;
        Integer num191 = num44;
        byte[] bArr9 = bArr3;
        String str107 = str28;
        Integer num192 = num49;
        Integer num193 = num37;
        Integer num194 = num38;
        ddz ddzVar9 = ddzVar6;
        Integer num195 = num43;
        Integer num196 = num47;
        Integer num197 = num48;
        String str108 = str21;
        String str109 = str22;
        Integer num198 = num42;
        ddz ddzVar10 = ddzVar5;
        Integer num199 = num46;
        apc apcVar2 = apcVar;
        String str110 = str29;
        Integer num200 = num36;
        String str111 = str24;
        ddz ddzVar11 = ddzVar3;
        acmVarP._bp(dfxVar);
        if ((-1 != i5) || (63 != (i3 & 63))) {
            ResourcesCompat.ag(new int[]{i5, i3}, new int[]{-1, 63}, descriptor);
            throw null;
        }
        ProtoModUserInfo protoModUserInfoVar = new ProtoModUserInfo();
        protoModUserInfoVar.a = num183;
        protoModUserInfoVar.b = ddzVar11;
        protoModUserInfoVar.c = ddzVar8;
        protoModUserInfoVar.d = num198;
        protoModUserInfoVar.e = ddzVar10;
        protoModUserInfoVar.f = ddzVar9;
        protoModUserInfoVar.g = num195;
        protoModUserInfoVar.h = num191;
        protoModUserInfoVar.i = bArr9;
        protoModUserInfoVar.j = num188;
        protoModUserInfoVar.k = str105;
        protoModUserInfoVar.l = str103;
        protoModUserInfoVar.m = str104;
        protoModUserInfoVar.n = num199;
        protoModUserInfoVar.o = apcVar2;
        protoModUserInfoVar.p = num196;
        protoModUserInfoVar.q = num197;
        protoModUserInfoVar.r = str107;
        protoModUserInfoVar.s = num192;
        protoModUserInfoVar.t = num189;
        protoModUserInfoVar.u = num190;
        protoModUserInfoVar.v = num184;
        protoModUserInfoVar.w = num185;
        protoModUserInfoVar.x = str110;
        protoModUserInfoVar.y = num200;
        protoModUserInfoVar.z = bipVar3;
        protoModUserInfoVar.aa = str109;
        protoModUserInfoVar.ab = str108;
        protoModUserInfoVar.ac = num193;
        protoModUserInfoVar.ad = num194;
        protoModUserInfoVar.ae = l13;
        protoModUserInfoVar.af = str106;
        protoModUserInfoVar.ag = num186;
        protoModUserInfoVar.ah = num187;
        protoModUserInfoVar.ai = str111;
        protoModUserInfoVar.aj = num182;
        protoModUserInfoVar.ak = str102;
        protoModUserInfoVar.al = str101;
        return protoModUserInfoVar;
    }

    @Override // me.hd.wauxv.obf.btd
    public final void c(avt avtVar, Object obj) {
        ProtoModUserInfo protoModUserInfoVar = (ProtoModUserInfo) obj;
        dfx dfxVar = descriptor;
        acn acnVarO = avtVar.o(dfxVar);
        bqj bqjVar = bqj.b;
        acnVarO.m(dfxVar, 0, bqjVar, protoModUserInfoVar.a);
        ddx ddxVar = ddx.b;
        acnVarO.m(dfxVar, 1, ddxVar, protoModUserInfoVar.b);
        acnVarO.m(dfxVar, 2, ddxVar, protoModUserInfoVar.c);
        acnVarO.m(dfxVar, 3, bqjVar, protoModUserInfoVar.d);
        acnVarO.m(dfxVar, 4, ddxVar, protoModUserInfoVar.e);
        acnVarO.m(dfxVar, 5, ddxVar, protoModUserInfoVar.f);
        acnVarO.m(dfxVar, 6, bqjVar, protoModUserInfoVar.g);
        acnVarO.m(dfxVar, 7, bqjVar, protoModUserInfoVar.h);
        acnVarO.m(dfxVar, 8, rx.j, protoModUserInfoVar.i);
        acnVarO.m(dfxVar, 9, bqjVar, protoModUserInfoVar.j);
        dnh dnhVar = dnh.b;
        acnVarO.m(dfxVar, 10, dnhVar, protoModUserInfoVar.k);
        acnVarO.m(dfxVar, 11, dnhVar, protoModUserInfoVar.l);
        acnVarO.m(dfxVar, 12, dnhVar, protoModUserInfoVar.m);
        acnVarO.m(dfxVar, 13, bqjVar, protoModUserInfoVar.n);
        acnVarO.m(dfxVar, 14, apa.b, protoModUserInfoVar.o);
        acnVarO.m(dfxVar, 15, bqjVar, protoModUserInfoVar.p);
        acnVarO.m(dfxVar, 16, bqjVar, protoModUserInfoVar.q);
        acnVarO.m(dfxVar, 17, dnhVar, protoModUserInfoVar.r);
        acnVarO.m(dfxVar, 18, bqjVar, protoModUserInfoVar.s);
        acnVarO.m(dfxVar, 19, bqjVar, protoModUserInfoVar.t);
        acnVarO.m(dfxVar, 20, bqjVar, protoModUserInfoVar.u);
        acnVarO.m(dfxVar, 21, bqjVar, protoModUserInfoVar.v);
        acnVarO.m(dfxVar, 22, bqjVar, protoModUserInfoVar.w);
        acnVarO.m(dfxVar, 23, dnhVar, protoModUserInfoVar.x);
        acnVarO.m(dfxVar, 24, bqjVar, protoModUserInfoVar.y);
        acnVarO.m(dfxVar, 25, bin.b, protoModUserInfoVar.z);
        acnVarO.m(dfxVar, 26, dnhVar, protoModUserInfoVar.aa);
        acnVarO.m(dfxVar, 27, dnhVar, protoModUserInfoVar.ab);
        acnVarO.m(dfxVar, 28, bqjVar, protoModUserInfoVar.ac);
        acnVarO.m(dfxVar, 29, bqjVar, protoModUserInfoVar.ad);
        acnVarO.m(dfxVar, 30, bya.b, protoModUserInfoVar.ae);
        acnVarO.m(dfxVar, 31, dnhVar, protoModUserInfoVar.af);
        acnVarO.m(dfxVar, 32, bqjVar, protoModUserInfoVar.ag);
        acnVarO.m(dfxVar, 33, bqjVar, protoModUserInfoVar.ah);
        acnVarO.m(dfxVar, 34, dnhVar, protoModUserInfoVar.ai);
        acnVarO.m(dfxVar, 35, bqjVar, protoModUserInfoVar.aj);
        acnVarO.m(dfxVar, 36, dnhVar, protoModUserInfoVar.ak);
        acnVarO.m(dfxVar, 37, dnhVar, protoModUserInfoVar.al);
        acnVarO.a(dfxVar);
    }

    @Override // me.hd.wauxv.obf.bgx
    public final btd[] d() {
        bqj bqjVar = bqj.b;
        btd btdVarT = aye.t(bqjVar);
        ddx ddxVar = ddx.b;
        btd btdVarT2 = aye.t(ddxVar);
        btd btdVarT3 = aye.t(ddxVar);
        btd btdVarT4 = aye.t(bqjVar);
        btd btdVarT5 = aye.t(ddxVar);
        btd btdVarT6 = aye.t(ddxVar);
        btd btdVarT7 = aye.t(bqjVar);
        btd btdVarT8 = aye.t(bqjVar);
        btd btdVarT9 = aye.t(rx.j);
        btd btdVarT10 = aye.t(bqjVar);
        dnh dnhVar = dnh.b;
        return new btd[]{btdVarT, btdVarT2, btdVarT3, btdVarT4, btdVarT5, btdVarT6, btdVarT7, btdVarT8, btdVarT9, btdVarT10, aye.t(dnhVar), aye.t(dnhVar), aye.t(dnhVar), aye.t(bqjVar), aye.t(apa.b), aye.t(bqjVar), aye.t(bqjVar), aye.t(dnhVar), aye.t(bqjVar), aye.t(bqjVar), aye.t(bqjVar), aye.t(bqjVar), aye.t(bqjVar), aye.t(dnhVar), aye.t(bqjVar), aye.t(bin.b), aye.t(dnhVar), aye.t(dnhVar), aye.t(bqjVar), aye.t(bqjVar), aye.t(bya.b), aye.t(dnhVar), aye.t(bqjVar), aye.t(bqjVar), aye.t(dnhVar), aye.t(bqjVar), aye.t(dnhVar), aye.t(dnhVar)};
    }

    @Override // me.hd.wauxv.obf.btd
    public final dfx getDescriptor() {
        return descriptor;
    }
}
