package me.hd.wauxv.obf;

import android.R;

/* JADX INFO: loaded from: classes.dex */
public abstract class cxs {
    public static final int[] a = {R.attr.background, R.attr.touchscreenBlocksFocus, R.attr.keyboardNavigationCluster, me.hd.wauxv.R.attr.elevation, me.hd.wauxv.R.attr.expanded, me.hd.wauxv.R.attr.liftOnScroll, me.hd.wauxv.R.attr.liftOnScrollColor, me.hd.wauxv.R.attr.liftOnScrollTargetViewId, me.hd.wauxv.R.attr.statusBarForeground};
    public static final int[] b = {me.hd.wauxv.R.attr.layout_scrollEffect, me.hd.wauxv.R.attr.layout_scrollFlags, me.hd.wauxv.R.attr.layout_scrollInterpolator};
    public static final int[] c = {me.hd.wauxv.R.attr.autoAdjustToWithinGrandparentBounds, me.hd.wauxv.R.attr.backgroundColor, me.hd.wauxv.R.attr.badgeGravity, me.hd.wauxv.R.attr.badgeHeight, me.hd.wauxv.R.attr.badgeRadius, me.hd.wauxv.R.attr.badgeShapeAppearance, me.hd.wauxv.R.attr.badgeShapeAppearanceOverlay, me.hd.wauxv.R.attr.badgeText, me.hd.wauxv.R.attr.badgeTextAppearance, me.hd.wauxv.R.attr.badgeTextColor, me.hd.wauxv.R.attr.badgeVerticalPadding, me.hd.wauxv.R.attr.badgeWidePadding, me.hd.wauxv.R.attr.badgeWidth, me.hd.wauxv.R.attr.badgeWithTextHeight, me.hd.wauxv.R.attr.badgeWithTextRadius, me.hd.wauxv.R.attr.badgeWithTextShapeAppearance, me.hd.wauxv.R.attr.badgeWithTextShapeAppearanceOverlay, me.hd.wauxv.R.attr.badgeWithTextWidth, me.hd.wauxv.R.attr.horizontalOffset, me.hd.wauxv.R.attr.horizontalOffsetWithText, me.hd.wauxv.R.attr.largeFontVerticalOffsetAdjustment, me.hd.wauxv.R.attr.maxCharacterCount, me.hd.wauxv.R.attr.maxNumber, me.hd.wauxv.R.attr.number, me.hd.wauxv.R.attr.offsetAlignmentMode, me.hd.wauxv.R.attr.verticalOffset, me.hd.wauxv.R.attr.verticalOffsetWithText};
    public static final int[] d = {R.attr.minHeight, me.hd.wauxv.R.attr.compatShadowEnabled, me.hd.wauxv.R.attr.itemHorizontalTranslationEnabled, me.hd.wauxv.R.attr.shapeAppearance, me.hd.wauxv.R.attr.shapeAppearanceOverlay};
    public static final int[] e = {R.attr.maxWidth, R.attr.maxHeight, R.attr.elevation, me.hd.wauxv.R.attr.backgroundTint, me.hd.wauxv.R.attr.behavior_draggable, me.hd.wauxv.R.attr.behavior_expandedOffset, me.hd.wauxv.R.attr.behavior_fitToContents, me.hd.wauxv.R.attr.behavior_halfExpandedRatio, me.hd.wauxv.R.attr.behavior_hideable, me.hd.wauxv.R.attr.behavior_peekHeight, me.hd.wauxv.R.attr.behavior_saveFlags, me.hd.wauxv.R.attr.behavior_significantVelocityThreshold, me.hd.wauxv.R.attr.behavior_skipCollapsed, me.hd.wauxv.R.attr.gestureInsetBottomIgnored, me.hd.wauxv.R.attr.marginLeftSystemWindowInsets, me.hd.wauxv.R.attr.marginRightSystemWindowInsets, me.hd.wauxv.R.attr.marginTopSystemWindowInsets, me.hd.wauxv.R.attr.paddingBottomSystemWindowInsets, me.hd.wauxv.R.attr.paddingLeftSystemWindowInsets, me.hd.wauxv.R.attr.paddingRightSystemWindowInsets, me.hd.wauxv.R.attr.paddingTopSystemWindowInsets, me.hd.wauxv.R.attr.shapeAppearance, me.hd.wauxv.R.attr.shapeAppearanceOverlay, me.hd.wauxv.R.attr.shouldRemoveExpandedCorners};
    public static final int[] f = {R.attr.minWidth, R.attr.minHeight, me.hd.wauxv.R.attr.cardBackgroundColor, me.hd.wauxv.R.attr.cardCornerRadius, me.hd.wauxv.R.attr.cardElevation, me.hd.wauxv.R.attr.cardMaxElevation, me.hd.wauxv.R.attr.cardPreventCornerOverlap, me.hd.wauxv.R.attr.cardUseCompatPadding, me.hd.wauxv.R.attr.contentPadding, me.hd.wauxv.R.attr.contentPaddingBottom, me.hd.wauxv.R.attr.contentPaddingLeft, me.hd.wauxv.R.attr.contentPaddingRight, me.hd.wauxv.R.attr.contentPaddingTop};
    public static final int[] g = {me.hd.wauxv.R.attr.carousel_alignment, me.hd.wauxv.R.attr.carousel_backwardTransition, me.hd.wauxv.R.attr.carousel_emptyViewsBehavior, me.hd.wauxv.R.attr.carousel_firstView, me.hd.wauxv.R.attr.carousel_forwardTransition, me.hd.wauxv.R.attr.carousel_infinite, me.hd.wauxv.R.attr.carousel_nextState, me.hd.wauxv.R.attr.carousel_previousState, me.hd.wauxv.R.attr.carousel_touchUpMode, me.hd.wauxv.R.attr.carousel_touchUp_dampeningFactor, me.hd.wauxv.R.attr.carousel_touchUp_velocityThreshold};
    public static final int[] h = {R.attr.textAppearance, R.attr.textSize, R.attr.textColor, R.attr.ellipsize, R.attr.maxWidth, R.attr.text, R.attr.checkable, me.hd.wauxv.R.attr.checkedIcon, me.hd.wauxv.R.attr.checkedIconEnabled, me.hd.wauxv.R.attr.checkedIconTint, me.hd.wauxv.R.attr.checkedIconVisible, me.hd.wauxv.R.attr.chipBackgroundColor, me.hd.wauxv.R.attr.chipCornerRadius, me.hd.wauxv.R.attr.chipEndPadding, me.hd.wauxv.R.attr.chipIcon, me.hd.wauxv.R.attr.chipIconEnabled, me.hd.wauxv.R.attr.chipIconSize, me.hd.wauxv.R.attr.chipIconTint, me.hd.wauxv.R.attr.chipIconVisible, me.hd.wauxv.R.attr.chipMinHeight, me.hd.wauxv.R.attr.chipMinTouchTargetSize, me.hd.wauxv.R.attr.chipStartPadding, me.hd.wauxv.R.attr.chipStrokeColor, me.hd.wauxv.R.attr.chipStrokeWidth, me.hd.wauxv.R.attr.chipSurfaceColor, me.hd.wauxv.R.attr.closeIcon, me.hd.wauxv.R.attr.closeIconEnabled, me.hd.wauxv.R.attr.closeIconEndPadding, me.hd.wauxv.R.attr.closeIconSize, me.hd.wauxv.R.attr.closeIconStartPadding, me.hd.wauxv.R.attr.closeIconTint, me.hd.wauxv.R.attr.closeIconVisible, me.hd.wauxv.R.attr.ensureMinTouchTargetSize, me.hd.wauxv.R.attr.hideMotionSpec, me.hd.wauxv.R.attr.iconEndPadding, me.hd.wauxv.R.attr.iconStartPadding, me.hd.wauxv.R.attr.rippleColor, me.hd.wauxv.R.attr.shapeAppearance, me.hd.wauxv.R.attr.shapeAppearanceOverlay, me.hd.wauxv.R.attr.showMotionSpec, me.hd.wauxv.R.attr.textEndPadding, me.hd.wauxv.R.attr.textStartPadding};
    public static final int[] i = {me.hd.wauxv.R.attr.clockFaceBackgroundColor, me.hd.wauxv.R.attr.clockNumberTextColor};
    public static final int[] j = {me.hd.wauxv.R.attr.clockHandColor, me.hd.wauxv.R.attr.materialCircleRadius, me.hd.wauxv.R.attr.selectorSize};
    public static final int[] k = {me.hd.wauxv.R.attr.collapsedTitleGravity, me.hd.wauxv.R.attr.collapsedTitleTextAppearance, me.hd.wauxv.R.attr.collapsedTitleTextColor, me.hd.wauxv.R.attr.contentScrim, me.hd.wauxv.R.attr.expandedTitleGravity, me.hd.wauxv.R.attr.expandedTitleMargin, me.hd.wauxv.R.attr.expandedTitleMarginBottom, me.hd.wauxv.R.attr.expandedTitleMarginEnd, me.hd.wauxv.R.attr.expandedTitleMarginStart, me.hd.wauxv.R.attr.expandedTitleMarginTop, me.hd.wauxv.R.attr.expandedTitleTextAppearance, me.hd.wauxv.R.attr.expandedTitleTextColor, me.hd.wauxv.R.attr.extraMultilineHeightEnabled, me.hd.wauxv.R.attr.forceApplySystemWindowInsetTop, me.hd.wauxv.R.attr.maxLines, me.hd.wauxv.R.attr.scrimAnimationDuration, me.hd.wauxv.R.attr.scrimVisibleHeightTrigger, me.hd.wauxv.R.attr.statusBarScrim, me.hd.wauxv.R.attr.title, me.hd.wauxv.R.attr.titleCollapseMode, me.hd.wauxv.R.attr.titleEnabled, me.hd.wauxv.R.attr.titlePositionInterpolator, me.hd.wauxv.R.attr.titleTextEllipsize, me.hd.wauxv.R.attr.toolbarId};
    public static final int[] l = {me.hd.wauxv.R.attr.layout_collapseMode, me.hd.wauxv.R.attr.layout_collapseParallaxMultiplier};
    public static final int[] m = {me.hd.wauxv.R.attr.behavior_autoHide, me.hd.wauxv.R.attr.behavior_autoShrink};
    public static final int[] n = {me.hd.wauxv.R.attr.behavior_autoHide};
    public static final int[] o = {R.attr.foreground, R.attr.foregroundGravity, me.hd.wauxv.R.attr.foregroundInsidePadding};
    public static final int[] p = {me.hd.wauxv.R.attr.backgroundInsetBottom, me.hd.wauxv.R.attr.backgroundInsetEnd, me.hd.wauxv.R.attr.backgroundInsetStart, me.hd.wauxv.R.attr.backgroundInsetTop, me.hd.wauxv.R.attr.backgroundTint};
    public static final int[] q = {R.attr.inputType, R.attr.popupElevation, me.hd.wauxv.R.attr.dropDownBackgroundTint, me.hd.wauxv.R.attr.simpleItemLayout, me.hd.wauxv.R.attr.simpleItemSelectedColor, me.hd.wauxv.R.attr.simpleItemSelectedRippleColor, me.hd.wauxv.R.attr.simpleItems};
    public static final int[] r = {R.attr.background, R.attr.insetLeft, R.attr.insetRight, R.attr.insetTop, R.attr.insetBottom, R.attr.checkable, me.hd.wauxv.R.attr.backgroundTint, me.hd.wauxv.R.attr.backgroundTintMode, me.hd.wauxv.R.attr.cornerRadius, me.hd.wauxv.R.attr.elevation, me.hd.wauxv.R.attr.icon, me.hd.wauxv.R.attr.iconGravity, me.hd.wauxv.R.attr.iconPadding, me.hd.wauxv.R.attr.iconSize, me.hd.wauxv.R.attr.iconTint, me.hd.wauxv.R.attr.iconTintMode, me.hd.wauxv.R.attr.rippleColor, me.hd.wauxv.R.attr.shapeAppearance, me.hd.wauxv.R.attr.shapeAppearanceOverlay, me.hd.wauxv.R.attr.strokeColor, me.hd.wauxv.R.attr.strokeWidth, me.hd.wauxv.R.attr.toggleCheckedStateOnClick};
    public static final int[] s = {R.attr.enabled, me.hd.wauxv.R.attr.checkedButton, me.hd.wauxv.R.attr.selectionRequired, me.hd.wauxv.R.attr.singleSelection};
    public static final int[] t = {R.attr.windowFullscreen, me.hd.wauxv.R.attr.backgroundTint, me.hd.wauxv.R.attr.dayInvalidStyle, me.hd.wauxv.R.attr.daySelectedStyle, me.hd.wauxv.R.attr.dayStyle, me.hd.wauxv.R.attr.dayTodayStyle, me.hd.wauxv.R.attr.nestedScrollable, me.hd.wauxv.R.attr.rangeFillColor, me.hd.wauxv.R.attr.yearSelectedStyle, me.hd.wauxv.R.attr.yearStyle, me.hd.wauxv.R.attr.yearTodayStyle};
    public static final int[] u = {R.attr.insetLeft, R.attr.insetRight, R.attr.insetTop, R.attr.insetBottom, me.hd.wauxv.R.attr.itemFillColor, me.hd.wauxv.R.attr.itemShapeAppearance, me.hd.wauxv.R.attr.itemShapeAppearanceOverlay, me.hd.wauxv.R.attr.itemStrokeColor, me.hd.wauxv.R.attr.itemStrokeWidth, me.hd.wauxv.R.attr.itemTextColor};
    public static final int[] v = {R.attr.checkable, me.hd.wauxv.R.attr.cardForegroundColor, me.hd.wauxv.R.attr.checkedIcon, me.hd.wauxv.R.attr.checkedIconGravity, me.hd.wauxv.R.attr.checkedIconMargin, me.hd.wauxv.R.attr.checkedIconSize, me.hd.wauxv.R.attr.checkedIconTint, me.hd.wauxv.R.attr.rippleColor, me.hd.wauxv.R.attr.shapeAppearance, me.hd.wauxv.R.attr.shapeAppearanceOverlay, me.hd.wauxv.R.attr.state_dragged, me.hd.wauxv.R.attr.strokeColor, me.hd.wauxv.R.attr.strokeWidth};
    public static final int[] w = {R.attr.button, me.hd.wauxv.R.attr.buttonCompat, me.hd.wauxv.R.attr.buttonIcon, me.hd.wauxv.R.attr.buttonIconTint, me.hd.wauxv.R.attr.buttonIconTintMode, me.hd.wauxv.R.attr.buttonTint, me.hd.wauxv.R.attr.centerIfNoTextEnabled, me.hd.wauxv.R.attr.checkedState, me.hd.wauxv.R.attr.errorAccessibilityLabel, me.hd.wauxv.R.attr.errorShown, me.hd.wauxv.R.attr.useMaterialThemeColors};
    public static final int[] x = {me.hd.wauxv.R.attr.buttonTint, me.hd.wauxv.R.attr.useMaterialThemeColors};
    public static final int[] y = {me.hd.wauxv.R.attr.shapeAppearance, me.hd.wauxv.R.attr.shapeAppearanceOverlay};
    public static final int[] z = {me.hd.wauxv.R.attr.thumbIcon, me.hd.wauxv.R.attr.thumbIconSize, me.hd.wauxv.R.attr.thumbIconTint, me.hd.wauxv.R.attr.thumbIconTintMode, me.hd.wauxv.R.attr.trackDecoration, me.hd.wauxv.R.attr.trackDecorationTint, me.hd.wauxv.R.attr.trackDecorationTintMode};
    public static final int[] aa = {R.attr.letterSpacing, R.attr.lineHeight, me.hd.wauxv.R.attr.lineHeight};
    public static final int[] ab = {R.attr.textAppearance, R.attr.lineHeight, me.hd.wauxv.R.attr.lineHeight};
    public static final int[] ac = {me.hd.wauxv.R.attr.logoAdjustViewBounds, me.hd.wauxv.R.attr.logoScaleType, me.hd.wauxv.R.attr.navigationIconTint, me.hd.wauxv.R.attr.subtitleCentered, me.hd.wauxv.R.attr.titleCentered};
    public static final int[] ad = {R.attr.height, R.attr.width, R.attr.color, me.hd.wauxv.R.attr.marginHorizontal, me.hd.wauxv.R.attr.shapeAppearance};
    public static final int[] ae = {me.hd.wauxv.R.attr.activeIndicatorLabelPadding, me.hd.wauxv.R.attr.backgroundTint, me.hd.wauxv.R.attr.elevation, me.hd.wauxv.R.attr.itemActiveIndicatorStyle, me.hd.wauxv.R.attr.itemBackground, me.hd.wauxv.R.attr.itemIconSize, me.hd.wauxv.R.attr.itemIconTint, me.hd.wauxv.R.attr.itemPaddingBottom, me.hd.wauxv.R.attr.itemPaddingTop, me.hd.wauxv.R.attr.itemRippleColor, me.hd.wauxv.R.attr.itemTextAppearanceActive, me.hd.wauxv.R.attr.itemTextAppearanceActiveBoldEnabled, me.hd.wauxv.R.attr.itemTextAppearanceInactive, me.hd.wauxv.R.attr.itemTextColor, me.hd.wauxv.R.attr.labelVisibilityMode, me.hd.wauxv.R.attr.menu};
    public static final int[] af = {me.hd.wauxv.R.attr.headerLayout, me.hd.wauxv.R.attr.itemMinHeight, me.hd.wauxv.R.attr.menuGravity, me.hd.wauxv.R.attr.paddingBottomSystemWindowInsets, me.hd.wauxv.R.attr.paddingStartSystemWindowInsets, me.hd.wauxv.R.attr.paddingTopSystemWindowInsets, me.hd.wauxv.R.attr.shapeAppearance, me.hd.wauxv.R.attr.shapeAppearanceOverlay};
    public static final int[] ag = {me.hd.wauxv.R.attr.materialCircleRadius};
    public static final int[] ah = {me.hd.wauxv.R.attr.behavior_overlapTop};
    public static final int[] ai = {me.hd.wauxv.R.attr.cornerFamily, me.hd.wauxv.R.attr.cornerFamilyBottomLeft, me.hd.wauxv.R.attr.cornerFamilyBottomRight, me.hd.wauxv.R.attr.cornerFamilyTopLeft, me.hd.wauxv.R.attr.cornerFamilyTopRight, me.hd.wauxv.R.attr.cornerSize, me.hd.wauxv.R.attr.cornerSizeBottomLeft, me.hd.wauxv.R.attr.cornerSizeBottomRight, me.hd.wauxv.R.attr.cornerSizeTopLeft, me.hd.wauxv.R.attr.cornerSizeTopRight};
    public static final int[] aj = {me.hd.wauxv.R.attr.contentPadding, me.hd.wauxv.R.attr.contentPaddingBottom, me.hd.wauxv.R.attr.contentPaddingEnd, me.hd.wauxv.R.attr.contentPaddingLeft, me.hd.wauxv.R.attr.contentPaddingRight, me.hd.wauxv.R.attr.contentPaddingStart, me.hd.wauxv.R.attr.contentPaddingTop, me.hd.wauxv.R.attr.shapeAppearance, me.hd.wauxv.R.attr.shapeAppearanceOverlay, me.hd.wauxv.R.attr.strokeColor, me.hd.wauxv.R.attr.strokeWidth};
    public static final int[] ak = {R.attr.maxWidth, R.attr.maxHeight, R.attr.elevation, me.hd.wauxv.R.attr.backgroundTint, me.hd.wauxv.R.attr.behavior_draggable, me.hd.wauxv.R.attr.coplanarSiblingViewId, me.hd.wauxv.R.attr.shapeAppearance, me.hd.wauxv.R.attr.shapeAppearanceOverlay};
    public static final int[] al = {R.attr.enabled, R.attr.value, R.attr.stepSize, R.attr.valueFrom, R.attr.valueTo, me.hd.wauxv.R.attr.haloColor, me.hd.wauxv.R.attr.haloRadius, me.hd.wauxv.R.attr.labelBehavior, me.hd.wauxv.R.attr.labelStyle, me.hd.wauxv.R.attr.minTouchTargetSize, me.hd.wauxv.R.attr.thumbColor, me.hd.wauxv.R.attr.thumbElevation, me.hd.wauxv.R.attr.thumbHeight, me.hd.wauxv.R.attr.thumbRadius, me.hd.wauxv.R.attr.thumbStrokeColor, me.hd.wauxv.R.attr.thumbStrokeWidth, me.hd.wauxv.R.attr.thumbTrackGapSize, me.hd.wauxv.R.attr.thumbWidth, me.hd.wauxv.R.attr.tickColor, me.hd.wauxv.R.attr.tickColorActive, me.hd.wauxv.R.attr.tickColorInactive, me.hd.wauxv.R.attr.tickRadiusActive, me.hd.wauxv.R.attr.tickRadiusInactive, me.hd.wauxv.R.attr.tickVisible, me.hd.wauxv.R.attr.trackColor, me.hd.wauxv.R.attr.trackColorActive, me.hd.wauxv.R.attr.trackColorInactive, me.hd.wauxv.R.attr.trackHeight, me.hd.wauxv.R.attr.trackInsideCornerSize, me.hd.wauxv.R.attr.trackStopIndicatorSize};
    public static final int[] am = {R.attr.maxWidth, me.hd.wauxv.R.attr.actionTextColorAlpha, me.hd.wauxv.R.attr.animationMode, me.hd.wauxv.R.attr.backgroundOverlayColorAlpha, me.hd.wauxv.R.attr.backgroundTint, me.hd.wauxv.R.attr.backgroundTintMode, me.hd.wauxv.R.attr.elevation, me.hd.wauxv.R.attr.maxActionInlineWidth, me.hd.wauxv.R.attr.shapeAppearance, me.hd.wauxv.R.attr.shapeAppearanceOverlay};
    public static final int[] an = {me.hd.wauxv.R.attr.tabBackground, me.hd.wauxv.R.attr.tabContentStart, me.hd.wauxv.R.attr.tabGravity, me.hd.wauxv.R.attr.tabIconTint, me.hd.wauxv.R.attr.tabIconTintMode, me.hd.wauxv.R.attr.tabIndicator, me.hd.wauxv.R.attr.tabIndicatorAnimationDuration, me.hd.wauxv.R.attr.tabIndicatorAnimationMode, me.hd.wauxv.R.attr.tabIndicatorColor, me.hd.wauxv.R.attr.tabIndicatorFullWidth, me.hd.wauxv.R.attr.tabIndicatorGravity, me.hd.wauxv.R.attr.tabIndicatorHeight, me.hd.wauxv.R.attr.tabInlineLabel, me.hd.wauxv.R.attr.tabMaxWidth, me.hd.wauxv.R.attr.tabMinWidth, me.hd.wauxv.R.attr.tabMode, me.hd.wauxv.R.attr.tabPadding, me.hd.wauxv.R.attr.tabPaddingBottom, me.hd.wauxv.R.attr.tabPaddingEnd, me.hd.wauxv.R.attr.tabPaddingStart, me.hd.wauxv.R.attr.tabPaddingTop, me.hd.wauxv.R.attr.tabRippleColor, me.hd.wauxv.R.attr.tabSelectedTextAppearance, me.hd.wauxv.R.attr.tabSelectedTextColor, me.hd.wauxv.R.attr.tabTextAppearance, me.hd.wauxv.R.attr.tabTextColor, me.hd.wauxv.R.attr.tabUnboundedRipple};
    public static final int[] ao = {R.attr.textSize, R.attr.typeface, R.attr.textStyle, R.attr.textColor, R.attr.textColorHint, R.attr.textColorLink, R.attr.shadowColor, R.attr.shadowDx, R.attr.shadowDy, R.attr.shadowRadius, R.attr.fontFamily, R.attr.textFontWeight, me.hd.wauxv.R.attr.fontFamily, me.hd.wauxv.R.attr.fontVariationSettings, me.hd.wauxv.R.attr.textAllCaps, me.hd.wauxv.R.attr.textLocale};
    public static final int[] ap = {me.hd.wauxv.R.attr.textInputLayoutFocusedRectEnabled};
    public static final int[] aq = {R.attr.enabled, R.attr.textColorHint, R.attr.maxWidth, R.attr.minWidth, R.attr.hint, R.attr.maxEms, R.attr.minEms, me.hd.wauxv.R.attr.boxBackgroundColor, me.hd.wauxv.R.attr.boxBackgroundMode, me.hd.wauxv.R.attr.boxCollapsedPaddingTop, me.hd.wauxv.R.attr.boxCornerRadiusBottomEnd, me.hd.wauxv.R.attr.boxCornerRadiusBottomStart, me.hd.wauxv.R.attr.boxCornerRadiusTopEnd, me.hd.wauxv.R.attr.boxCornerRadiusTopStart, me.hd.wauxv.R.attr.boxStrokeColor, me.hd.wauxv.R.attr.boxStrokeErrorColor, me.hd.wauxv.R.attr.boxStrokeWidth, me.hd.wauxv.R.attr.boxStrokeWidthFocused, me.hd.wauxv.R.attr.counterEnabled, me.hd.wauxv.R.attr.counterMaxLength, me.hd.wauxv.R.attr.counterOverflowTextAppearance, me.hd.wauxv.R.attr.counterOverflowTextColor, me.hd.wauxv.R.attr.counterTextAppearance, me.hd.wauxv.R.attr.counterTextColor, me.hd.wauxv.R.attr.cursorColor, me.hd.wauxv.R.attr.cursorErrorColor, me.hd.wauxv.R.attr.endIconCheckable, me.hd.wauxv.R.attr.endIconContentDescription, me.hd.wauxv.R.attr.endIconDrawable, me.hd.wauxv.R.attr.endIconMinSize, me.hd.wauxv.R.attr.endIconMode, me.hd.wauxv.R.attr.endIconScaleType, me.hd.wauxv.R.attr.endIconTint, me.hd.wauxv.R.attr.endIconTintMode, me.hd.wauxv.R.attr.errorAccessibilityLiveRegion, me.hd.wauxv.R.attr.errorContentDescription, me.hd.wauxv.R.attr.errorEnabled, me.hd.wauxv.R.attr.errorIconDrawable, me.hd.wauxv.R.attr.errorIconTint, me.hd.wauxv.R.attr.errorIconTintMode, me.hd.wauxv.R.attr.errorTextAppearance, me.hd.wauxv.R.attr.errorTextColor, me.hd.wauxv.R.attr.expandedHintEnabled, me.hd.wauxv.R.attr.helperText, me.hd.wauxv.R.attr.helperTextEnabled, me.hd.wauxv.R.attr.helperTextTextAppearance, me.hd.wauxv.R.attr.helperTextTextColor, me.hd.wauxv.R.attr.hintAnimationEnabled, me.hd.wauxv.R.attr.hintEnabled, me.hd.wauxv.R.attr.hintTextAppearance, me.hd.wauxv.R.attr.hintTextColor, me.hd.wauxv.R.attr.passwordToggleContentDescription, me.hd.wauxv.R.attr.passwordToggleDrawable, me.hd.wauxv.R.attr.passwordToggleEnabled, me.hd.wauxv.R.attr.passwordToggleTint, me.hd.wauxv.R.attr.passwordToggleTintMode, me.hd.wauxv.R.attr.placeholderText, me.hd.wauxv.R.attr.placeholderTextAppearance, me.hd.wauxv.R.attr.placeholderTextColor, me.hd.wauxv.R.attr.prefixText, me.hd.wauxv.R.attr.prefixTextAppearance, me.hd.wauxv.R.attr.prefixTextColor, me.hd.wauxv.R.attr.shapeAppearance, me.hd.wauxv.R.attr.shapeAppearanceOverlay, me.hd.wauxv.R.attr.startIconCheckable, me.hd.wauxv.R.attr.startIconContentDescription, me.hd.wauxv.R.attr.startIconDrawable, me.hd.wauxv.R.attr.startIconMinSize, me.hd.wauxv.R.attr.startIconScaleType, me.hd.wauxv.R.attr.startIconTint, me.hd.wauxv.R.attr.startIconTintMode, me.hd.wauxv.R.attr.suffixText, me.hd.wauxv.R.attr.suffixTextAppearance, me.hd.wauxv.R.attr.suffixTextColor};
    public static final int[] ar = {R.attr.textAppearance, me.hd.wauxv.R.attr.enforceMaterialTheme, me.hd.wauxv.R.attr.enforceTextAppearance};
    public static final int[] as = {R.attr.textAppearance, R.attr.textColor, R.attr.padding, R.attr.layout_margin, R.attr.minWidth, R.attr.minHeight, R.attr.text, me.hd.wauxv.R.attr.backgroundTint, me.hd.wauxv.R.attr.showMarker};
}
