package me.hd.wauxv.obf;

import net.bytebuddy.jar.asm.Opcodes;
import okhttp3.internal.http2.Http2Connection;

/* JADX INFO: compiled from: r8-map-id-b9de5da7d0413052737328a4e696e1bcc3145db8f6a41e1e318485e124198cd6 */
/* JADX INFO: loaded from: classes.dex */
public final /* synthetic */ class drw implements bgx {
    public static final drw b;
    private static final dfx descriptor;

    static {
        drw drwVar = new drw();
        b = drwVar;
        cuc cucVar = new cuc("me.hd.wauxv.hook.micromsg.core.protobuf.old.proto.TimeLineObjectProto" /* cnb.z(-157951717276458L) */, drwVar, 28);
        bjs.y(-158183645510442L, cucVar, false, 1);
        bjs.y(-158187940477738L, cucVar, false, 2);
        bjs.y(-158097746164522L, cucVar, false, 3);
        bjs.y(-158059091458858L, cucVar, false, 4);
        bjs.y(-157496450743082L, cucVar, false, 5);
        bjs.y(-157410551397162L, cucVar, false, 6);
        bjs.y(-157371896691498L, cucVar, false, 7);
        bjs.y(-157337536953130L, cucVar, false, 8);
        bjs.y(-157324652051242L, cucVar, false, 9);
        bjs.y(-157243047672618L, cucVar, false, 10);
        bjs.y(-157728378977066L, cucVar, false, 11);
        bjs.y(-157646774598442L, cucVar, false, 12);
        bjs.y(-157595234990890L, cucVar, false, 13);
        bjs.y(-157539400416042L, cucVar, false, 14);
        bjs.y(-154709016967978L, cucVar, false, 15);
        bjs.y(-154627412589354L, cucVar, false, 16);
        bjs.y(-154610232720170L, cucVar, false, 17);
        bjs.y(-154524333374250L, cucVar, false, 18);
        bjs.y(-154494268603178L, cucVar, false, 19);
        bjs.y(-155031139515178L, cucVar, false, 20);
        bjs.y(-154936650234666L, cucVar, false, 21);
        bjs.y(-154919470365482L, cucVar, false, 22);
        bjs.y(-154842160954154L, cucVar, false, 23);
        bjs.y(-154803506248490L, cucVar, false, 24);
        bjs.y(-154786326379306L, cucVar, false, 25);
        bjs.y(-154159261154090L, cucVar, false, 26);
        bjs.y(-154081951742762L, cucVar, false, 27);
        bjs.y(-154056181938986L, cucVar, false, 28);
        descriptor = cucVar;
    }

    @Override // me.hd.wauxv.obf.btd
    public final Object a(ajt ajtVar) {
        dtn dtnVar;
        String str;
        String str2;
        Integer num;
        Integer num2;
        String str3;
        String str4;
        String str5;
        dss dssVar;
        dsf dsfVar;
        dtq dtqVar;
        String str6;
        Integer num3;
        Integer num4;
        String str7;
        drz drzVar;
        boolean z;
        dtk dtkVar;
        Integer num5;
        int i;
        int i2;
        dfx dfxVar = descriptor;
        acm acmVarP = ajtVar.p(dfxVar);
        acmVarP.getClass();
        dtn dtnVar2 = null;
        dtk dtkVar2 = null;
        Boolean bool = null;
        duq duqVar = null;
        String str8 = null;
        Integer num6 = null;
        duk dukVar = null;
        String str9 = null;
        String str10 = null;
        dut dutVar = null;
        Integer num7 = null;
        duw duwVar = null;
        Integer num8 = null;
        String str11 = null;
        String str12 = null;
        Integer num9 = null;
        Integer num10 = null;
        String str13 = null;
        dtq dtqVar2 = null;
        dsf dsfVar2 = null;
        dss dssVar2 = null;
        String str14 = null;
        String str15 = null;
        String str16 = null;
        Integer num11 = null;
        Integer num12 = null;
        String str17 = null;
        drz drzVar2 = null;
        int i3 = 0;
        boolean z2 = true;
        while (z2) {
            int i4 = i3;
            int iF = acmVarP.f(dfxVar);
            switch (iF) {
                case -1:
                    Integer num13 = num9;
                    i3 = i4;
                    Boolean bool2 = bool;
                    String str18 = str11;
                    dtnVar = dtnVar2;
                    str = str12;
                    str2 = str17;
                    num6 = num6;
                    num = num12;
                    num2 = num11;
                    str3 = str16;
                    str4 = str15;
                    str5 = str14;
                    dssVar = dssVar2;
                    dsfVar = dsfVar2;
                    dtqVar = dtqVar2;
                    str6 = str13;
                    num3 = num10;
                    num4 = num13;
                    str7 = str18;
                    bool = bool2;
                    drzVar = drzVar2;
                    z = false;
                    dtnVar2 = dtnVar;
                    str12 = str;
                    num9 = num4;
                    num10 = num3;
                    str13 = str6;
                    dtqVar2 = dtqVar;
                    dsfVar2 = dsfVar;
                    dssVar2 = dssVar;
                    str14 = str5;
                    str15 = str4;
                    str16 = str3;
                    num11 = num2;
                    num12 = num;
                    str17 = str2;
                    z2 = z;
                    drzVar2 = drzVar;
                    str11 = str7;
                    break;
                case 0:
                    dtkVar = dtkVar2;
                    Integer num14 = num9;
                    Boolean bool3 = bool;
                    String str19 = str11;
                    dtnVar = dtnVar2;
                    String str20 = (String) acmVarP.i(dfxVar, 0, dnh.b, str19);
                    i3 = i4 | 1;
                    str = str12;
                    bool = bool3;
                    num6 = num6;
                    drzVar = drzVar2;
                    z = z2;
                    str2 = str17;
                    num = num12;
                    num2 = num11;
                    str3 = str16;
                    str4 = str15;
                    str5 = str14;
                    dssVar = dssVar2;
                    dsfVar = dsfVar2;
                    dtqVar = dtqVar2;
                    str6 = str13;
                    num3 = num10;
                    num4 = num14;
                    str7 = str20;
                    dtkVar2 = dtkVar;
                    dtnVar2 = dtnVar;
                    str12 = str;
                    num9 = num4;
                    num10 = num3;
                    str13 = str6;
                    dtqVar2 = dtqVar;
                    dsfVar2 = dsfVar;
                    dssVar2 = dssVar;
                    str14 = str5;
                    str15 = str4;
                    str16 = str3;
                    num11 = num2;
                    num12 = num;
                    str17 = str2;
                    z2 = z;
                    drzVar2 = drzVar;
                    str11 = str7;
                    break;
                case 1:
                    Boolean bool4 = bool;
                    Integer num15 = num9;
                    i3 = i4 | 2;
                    str = (String) acmVarP.i(dfxVar, 1, dnh.b, str12);
                    bool = bool4;
                    num6 = num6;
                    dtkVar2 = dtkVar2;
                    drzVar = drzVar2;
                    z = z2;
                    str2 = str17;
                    num = num12;
                    num2 = num11;
                    str3 = str16;
                    str4 = str15;
                    str5 = str14;
                    dssVar = dssVar2;
                    dsfVar = dsfVar2;
                    dtqVar = dtqVar2;
                    str6 = str13;
                    num3 = num10;
                    num4 = num15;
                    str7 = str11;
                    dtnVar = dtnVar2;
                    dtnVar2 = dtnVar;
                    str12 = str;
                    num9 = num4;
                    num10 = num3;
                    str13 = str6;
                    dtqVar2 = dtqVar;
                    dsfVar2 = dsfVar;
                    dssVar2 = dssVar;
                    str14 = str5;
                    str15 = str4;
                    str16 = str3;
                    num11 = num2;
                    num12 = num;
                    str17 = str2;
                    z2 = z;
                    drzVar2 = drzVar;
                    str11 = str7;
                    break;
                case 2:
                    dtkVar = dtkVar2;
                    Integer num16 = (Integer) acmVarP.i(dfxVar, 2, bqj.b, num9);
                    i3 = i4 | 4;
                    str7 = str11;
                    str = str12;
                    bool = bool;
                    num6 = num6;
                    dtnVar = dtnVar2;
                    drzVar = drzVar2;
                    z = z2;
                    str2 = str17;
                    num = num12;
                    num2 = num11;
                    str3 = str16;
                    str4 = str15;
                    str5 = str14;
                    dssVar = dssVar2;
                    dsfVar = dsfVar2;
                    dtqVar = dtqVar2;
                    str6 = str13;
                    num3 = num10;
                    num4 = num16;
                    dtkVar2 = dtkVar;
                    dtnVar2 = dtnVar;
                    str12 = str;
                    num9 = num4;
                    num10 = num3;
                    str13 = str6;
                    dtqVar2 = dtqVar;
                    dsfVar2 = dsfVar;
                    dssVar2 = dssVar;
                    str14 = str5;
                    str15 = str4;
                    str16 = str3;
                    num11 = num2;
                    num12 = num;
                    str17 = str2;
                    z2 = z;
                    drzVar2 = drzVar;
                    str11 = str7;
                    break;
                case 3:
                    dtkVar = dtkVar2;
                    Integer num17 = (Integer) acmVarP.i(dfxVar, 3, bqj.b, num10);
                    i3 = i4 | 8;
                    str7 = str11;
                    num4 = num9;
                    bool = bool;
                    num6 = num6;
                    dtnVar = dtnVar2;
                    str = str12;
                    drzVar = drzVar2;
                    z = z2;
                    str2 = str17;
                    num = num12;
                    num2 = num11;
                    str3 = str16;
                    str4 = str15;
                    str5 = str14;
                    dssVar = dssVar2;
                    dsfVar = dsfVar2;
                    dtqVar = dtqVar2;
                    str6 = str13;
                    num3 = num17;
                    dtkVar2 = dtkVar;
                    dtnVar2 = dtnVar;
                    str12 = str;
                    num9 = num4;
                    num10 = num3;
                    str13 = str6;
                    dtqVar2 = dtqVar;
                    dsfVar2 = dsfVar;
                    dssVar2 = dssVar;
                    str14 = str5;
                    str15 = str4;
                    str16 = str3;
                    num11 = num2;
                    num12 = num;
                    str17 = str2;
                    z2 = z;
                    drzVar2 = drzVar;
                    str11 = str7;
                    break;
                case 4:
                    dtkVar = dtkVar2;
                    String str21 = (String) acmVarP.i(dfxVar, 4, dnh.b, str13);
                    i3 = i4 | 16;
                    str7 = str11;
                    num3 = num10;
                    bool = bool;
                    num6 = num6;
                    dtnVar = dtnVar2;
                    num4 = num9;
                    drzVar = drzVar2;
                    str = str12;
                    z = z2;
                    str2 = str17;
                    num = num12;
                    num2 = num11;
                    str3 = str16;
                    str4 = str15;
                    str5 = str14;
                    dssVar = dssVar2;
                    dsfVar = dsfVar2;
                    dtqVar = dtqVar2;
                    str6 = str21;
                    dtkVar2 = dtkVar;
                    dtnVar2 = dtnVar;
                    str12 = str;
                    num9 = num4;
                    num10 = num3;
                    str13 = str6;
                    dtqVar2 = dtqVar;
                    dsfVar2 = dsfVar;
                    dssVar2 = dssVar;
                    str14 = str5;
                    str15 = str4;
                    str16 = str3;
                    num11 = num2;
                    num12 = num;
                    str17 = str2;
                    z2 = z;
                    drzVar2 = drzVar;
                    str11 = str7;
                    break;
                case 5:
                    dtkVar = dtkVar2;
                    dtq dtqVar3 = (dtq) acmVarP.i(dfxVar, 5, dto.b, dtqVar2);
                    i3 = i4 | 32;
                    str7 = str11;
                    str6 = str13;
                    bool = bool;
                    num6 = num6;
                    dtnVar = dtnVar2;
                    num3 = num10;
                    drzVar = drzVar2;
                    num4 = num9;
                    z = z2;
                    str = str12;
                    str2 = str17;
                    num = num12;
                    num2 = num11;
                    str3 = str16;
                    str4 = str15;
                    str5 = str14;
                    dssVar = dssVar2;
                    dsfVar = dsfVar2;
                    dtqVar = dtqVar3;
                    dtkVar2 = dtkVar;
                    dtnVar2 = dtnVar;
                    str12 = str;
                    num9 = num4;
                    num10 = num3;
                    str13 = str6;
                    dtqVar2 = dtqVar;
                    dsfVar2 = dsfVar;
                    dssVar2 = dssVar;
                    str14 = str5;
                    str15 = str4;
                    str16 = str3;
                    num11 = num2;
                    num12 = num;
                    str17 = str2;
                    z2 = z;
                    drzVar2 = drzVar;
                    str11 = str7;
                    break;
                case 6:
                    dtkVar = dtkVar2;
                    dsf dsfVar3 = (dsf) acmVarP.i(dfxVar, 6, dsd.b, dsfVar2);
                    i3 = i4 | 64;
                    str7 = str11;
                    dtqVar = dtqVar2;
                    bool = bool;
                    num6 = num6;
                    dtnVar = dtnVar2;
                    str6 = str13;
                    drzVar = drzVar2;
                    num3 = num10;
                    z = z2;
                    num4 = num9;
                    str2 = str17;
                    str = str12;
                    num = num12;
                    num2 = num11;
                    str3 = str16;
                    str4 = str15;
                    str5 = str14;
                    dssVar = dssVar2;
                    dsfVar = dsfVar3;
                    dtkVar2 = dtkVar;
                    dtnVar2 = dtnVar;
                    str12 = str;
                    num9 = num4;
                    num10 = num3;
                    str13 = str6;
                    dtqVar2 = dtqVar;
                    dsfVar2 = dsfVar;
                    dssVar2 = dssVar;
                    str14 = str5;
                    str15 = str4;
                    str16 = str3;
                    num11 = num2;
                    num12 = num;
                    str17 = str2;
                    z2 = z;
                    drzVar2 = drzVar;
                    str11 = str7;
                    break;
                case 7:
                    dtkVar = dtkVar2;
                    dss dssVar3 = (dss) acmVarP.i(dfxVar, 7, dsq.b, dssVar2);
                    i3 = i4 | 128;
                    str7 = str11;
                    dsfVar = dsfVar2;
                    bool = bool;
                    num6 = num6;
                    dtnVar = dtnVar2;
                    dtqVar = dtqVar2;
                    drzVar = drzVar2;
                    str6 = str13;
                    z = z2;
                    num3 = num10;
                    str2 = str17;
                    num4 = num9;
                    num = num12;
                    str = str12;
                    num2 = num11;
                    str3 = str16;
                    str4 = str15;
                    str5 = str14;
                    dssVar = dssVar3;
                    dtkVar2 = dtkVar;
                    dtnVar2 = dtnVar;
                    str12 = str;
                    num9 = num4;
                    num10 = num3;
                    str13 = str6;
                    dtqVar2 = dtqVar;
                    dsfVar2 = dsfVar;
                    dssVar2 = dssVar;
                    str14 = str5;
                    str15 = str4;
                    str16 = str3;
                    num11 = num2;
                    num12 = num;
                    str17 = str2;
                    z2 = z;
                    drzVar2 = drzVar;
                    str11 = str7;
                    break;
                case 8:
                    dtkVar = dtkVar2;
                    String str22 = (String) acmVarP.i(dfxVar, 8, dnh.b, str14);
                    i3 = i4 | 256;
                    str7 = str11;
                    dssVar = dssVar2;
                    bool = bool;
                    num6 = num6;
                    dtnVar = dtnVar2;
                    dsfVar = dsfVar2;
                    drzVar = drzVar2;
                    dtqVar = dtqVar2;
                    z = z2;
                    str6 = str13;
                    str2 = str17;
                    num3 = num10;
                    num = num12;
                    num4 = num9;
                    num2 = num11;
                    str = str12;
                    str3 = str16;
                    str4 = str15;
                    str5 = str22;
                    dtkVar2 = dtkVar;
                    dtnVar2 = dtnVar;
                    str12 = str;
                    num9 = num4;
                    num10 = num3;
                    str13 = str6;
                    dtqVar2 = dtqVar;
                    dsfVar2 = dsfVar;
                    dssVar2 = dssVar;
                    str14 = str5;
                    str15 = str4;
                    str16 = str3;
                    num11 = num2;
                    num12 = num;
                    str17 = str2;
                    z2 = z;
                    drzVar2 = drzVar;
                    str11 = str7;
                    break;
                case 9:
                    dtkVar = dtkVar2;
                    String str23 = (String) acmVarP.i(dfxVar, 9, dnh.b, str15);
                    i3 = i4 | 512;
                    str7 = str11;
                    str5 = str14;
                    bool = bool;
                    num6 = num6;
                    dtnVar = dtnVar2;
                    dssVar = dssVar2;
                    drzVar = drzVar2;
                    dsfVar = dsfVar2;
                    z = z2;
                    dtqVar = dtqVar2;
                    str2 = str17;
                    str6 = str13;
                    num = num12;
                    num3 = num10;
                    num2 = num11;
                    num4 = num9;
                    str3 = str16;
                    str4 = str23;
                    str = str12;
                    dtkVar2 = dtkVar;
                    dtnVar2 = dtnVar;
                    str12 = str;
                    num9 = num4;
                    num10 = num3;
                    str13 = str6;
                    dtqVar2 = dtqVar;
                    dsfVar2 = dsfVar;
                    dssVar2 = dssVar;
                    str14 = str5;
                    str15 = str4;
                    str16 = str3;
                    num11 = num2;
                    num12 = num;
                    str17 = str2;
                    z2 = z;
                    drzVar2 = drzVar;
                    str11 = str7;
                    break;
                case 10:
                    dtk dtkVar3 = dtkVar2;
                    String str24 = (String) acmVarP.i(dfxVar, 10, dnh.b, str16);
                    i3 = i4 | 1024;
                    str7 = str11;
                    str4 = str15;
                    bool = bool;
                    num6 = num6;
                    dtnVar = dtnVar2;
                    str5 = str14;
                    drzVar = drzVar2;
                    dssVar = dssVar2;
                    z = z2;
                    dsfVar = dsfVar2;
                    str2 = str17;
                    dtqVar = dtqVar2;
                    num = num12;
                    str6 = str13;
                    num2 = num11;
                    str3 = str24;
                    num3 = num10;
                    dtkVar2 = dtkVar3;
                    num4 = num9;
                    str = str12;
                    dtnVar2 = dtnVar;
                    str12 = str;
                    num9 = num4;
                    num10 = num3;
                    str13 = str6;
                    dtqVar2 = dtqVar;
                    dsfVar2 = dsfVar;
                    dssVar2 = dssVar;
                    str14 = str5;
                    str15 = str4;
                    str16 = str3;
                    num11 = num2;
                    num12 = num;
                    str17 = str2;
                    z2 = z;
                    drzVar2 = drzVar;
                    str11 = str7;
                    break;
                case 11:
                    dtk dtkVar4 = dtkVar2;
                    Integer num18 = (Integer) acmVarP.i(dfxVar, 11, bqj.b, num11);
                    i3 = i4 | 2048;
                    str7 = str11;
                    str3 = str16;
                    bool = bool;
                    num6 = num6;
                    dtnVar = dtnVar2;
                    str4 = str15;
                    drzVar = drzVar2;
                    str5 = str14;
                    z = z2;
                    dssVar = dssVar2;
                    str2 = str17;
                    dsfVar = dsfVar2;
                    num = num12;
                    num2 = num18;
                    dtqVar = dtqVar2;
                    dtkVar2 = dtkVar4;
                    str6 = str13;
                    num3 = num10;
                    num4 = num9;
                    str = str12;
                    dtnVar2 = dtnVar;
                    str12 = str;
                    num9 = num4;
                    num10 = num3;
                    str13 = str6;
                    dtqVar2 = dtqVar;
                    dsfVar2 = dsfVar;
                    dssVar2 = dssVar;
                    str14 = str5;
                    str15 = str4;
                    str16 = str3;
                    num11 = num2;
                    num12 = num;
                    str17 = str2;
                    z2 = z;
                    drzVar2 = drzVar;
                    str11 = str7;
                    break;
                case 12:
                    dtk dtkVar5 = dtkVar2;
                    Integer num19 = (Integer) acmVarP.i(dfxVar, 12, bqj.b, num12);
                    i3 = i4 | 4096;
                    str7 = str11;
                    num2 = num11;
                    bool = bool;
                    num6 = num6;
                    dtnVar = dtnVar2;
                    str3 = str16;
                    drzVar = drzVar2;
                    str4 = str15;
                    z = z2;
                    str5 = str14;
                    str2 = str17;
                    num = num19;
                    dssVar = dssVar2;
                    dtkVar2 = dtkVar5;
                    dsfVar = dsfVar2;
                    dtqVar = dtqVar2;
                    str6 = str13;
                    num3 = num10;
                    num4 = num9;
                    str = str12;
                    dtnVar2 = dtnVar;
                    str12 = str;
                    num9 = num4;
                    num10 = num3;
                    str13 = str6;
                    dtqVar2 = dtqVar;
                    dsfVar2 = dsfVar;
                    dssVar2 = dssVar;
                    str14 = str5;
                    str15 = str4;
                    str16 = str3;
                    num11 = num2;
                    num12 = num;
                    str17 = str2;
                    z2 = z;
                    drzVar2 = drzVar;
                    str11 = str7;
                    break;
                case 13:
                    dtk dtkVar6 = dtkVar2;
                    String str25 = (String) acmVarP.i(dfxVar, 13, dnh.b, str17);
                    i3 = i4 | 8192;
                    str7 = str11;
                    num = num12;
                    bool = bool;
                    num6 = num6;
                    dtnVar = dtnVar2;
                    num2 = num11;
                    drzVar = drzVar2;
                    str3 = str16;
                    z = z2;
                    str2 = str25;
                    str4 = str15;
                    dtkVar2 = dtkVar6;
                    str5 = str14;
                    dssVar = dssVar2;
                    dsfVar = dsfVar2;
                    dtqVar = dtqVar2;
                    str6 = str13;
                    num3 = num10;
                    num4 = num9;
                    str = str12;
                    dtnVar2 = dtnVar;
                    str12 = str;
                    num9 = num4;
                    num10 = num3;
                    str13 = str6;
                    dtqVar2 = dtqVar;
                    dsfVar2 = dsfVar;
                    dssVar2 = dssVar;
                    str14 = str5;
                    str15 = str4;
                    str16 = str3;
                    num11 = num2;
                    num12 = num;
                    str17 = str2;
                    z2 = z;
                    drzVar2 = drzVar;
                    str11 = str7;
                    break;
                case 14:
                    i3 = i4 | 16384;
                    drzVar = (drz) acmVarP.i(dfxVar, 14, drx.b, drzVar2);
                    str7 = str11;
                    z = z2;
                    num6 = num6;
                    dtkVar2 = dtkVar2;
                    dtnVar = dtnVar2;
                    str2 = str17;
                    num = num12;
                    num2 = num11;
                    str3 = str16;
                    str4 = str15;
                    str5 = str14;
                    dssVar = dssVar2;
                    dsfVar = dsfVar2;
                    dtqVar = dtqVar2;
                    str6 = str13;
                    num3 = num10;
                    num4 = num9;
                    str = str12;
                    dtnVar2 = dtnVar;
                    str12 = str;
                    num9 = num4;
                    num10 = num3;
                    str13 = str6;
                    dtqVar2 = dtqVar;
                    dsfVar2 = dsfVar;
                    dssVar2 = dssVar;
                    str14 = str5;
                    str15 = str4;
                    str16 = str3;
                    num11 = num2;
                    num12 = num;
                    str17 = str2;
                    z2 = z;
                    drzVar2 = drzVar;
                    str11 = str7;
                    break;
                case 15:
                    dtk dtkVar7 = dtkVar2;
                    i3 = i4 | 32768;
                    num6 = (Integer) acmVarP.i(dfxVar, 15, bqj.b, num6);
                    str7 = str11;
                    drzVar = drzVar2;
                    dtkVar2 = dtkVar7;
                    dtnVar = dtnVar2;
                    z = z2;
                    str2 = str17;
                    num = num12;
                    num2 = num11;
                    str3 = str16;
                    str4 = str15;
                    str5 = str14;
                    dssVar = dssVar2;
                    dsfVar = dsfVar2;
                    dtqVar = dtqVar2;
                    str6 = str13;
                    num3 = num10;
                    num4 = num9;
                    str = str12;
                    dtnVar2 = dtnVar;
                    str12 = str;
                    num9 = num4;
                    num10 = num3;
                    str13 = str6;
                    dtqVar2 = dtqVar;
                    dsfVar2 = dsfVar;
                    dssVar2 = dssVar;
                    str14 = str5;
                    str15 = str4;
                    str16 = str3;
                    num11 = num2;
                    num12 = num;
                    str17 = str2;
                    z2 = z;
                    drzVar2 = drzVar;
                    str11 = str7;
                    break;
                case 16:
                    num5 = num6;
                    i = i4 | 65536;
                    dukVar = (duk) acmVarP.i(dfxVar, 16, dui.b, dukVar);
                    i3 = i;
                    str7 = str11;
                    drzVar = drzVar2;
                    num6 = num5;
                    dtnVar = dtnVar2;
                    z = z2;
                    str2 = str17;
                    num = num12;
                    num2 = num11;
                    str3 = str16;
                    str4 = str15;
                    str5 = str14;
                    dssVar = dssVar2;
                    dsfVar = dsfVar2;
                    dtqVar = dtqVar2;
                    str6 = str13;
                    num3 = num10;
                    num4 = num9;
                    str = str12;
                    dtnVar2 = dtnVar;
                    str12 = str;
                    num9 = num4;
                    num10 = num3;
                    str13 = str6;
                    dtqVar2 = dtqVar;
                    dsfVar2 = dsfVar;
                    dssVar2 = dssVar;
                    str14 = str5;
                    str15 = str4;
                    str16 = str3;
                    num11 = num2;
                    num12 = num;
                    str17 = str2;
                    z2 = z;
                    drzVar2 = drzVar;
                    str11 = str7;
                    break;
                case 17:
                    num5 = num6;
                    i = i4 | 131072;
                    str9 = (String) acmVarP.i(dfxVar, 17, dnh.b, str9);
                    i3 = i;
                    str7 = str11;
                    drzVar = drzVar2;
                    num6 = num5;
                    dtnVar = dtnVar2;
                    z = z2;
                    str2 = str17;
                    num = num12;
                    num2 = num11;
                    str3 = str16;
                    str4 = str15;
                    str5 = str14;
                    dssVar = dssVar2;
                    dsfVar = dsfVar2;
                    dtqVar = dtqVar2;
                    str6 = str13;
                    num3 = num10;
                    num4 = num9;
                    str = str12;
                    dtnVar2 = dtnVar;
                    str12 = str;
                    num9 = num4;
                    num10 = num3;
                    str13 = str6;
                    dtqVar2 = dtqVar;
                    dsfVar2 = dsfVar;
                    dssVar2 = dssVar;
                    str14 = str5;
                    str15 = str4;
                    str16 = str3;
                    num11 = num2;
                    num12 = num;
                    str17 = str2;
                    z2 = z;
                    drzVar2 = drzVar;
                    str11 = str7;
                    break;
                case 18:
                    num5 = num6;
                    i = i4 | 262144;
                    str10 = (String) acmVarP.i(dfxVar, 18, dnh.b, str10);
                    i3 = i;
                    str7 = str11;
                    drzVar = drzVar2;
                    num6 = num5;
                    dtnVar = dtnVar2;
                    z = z2;
                    str2 = str17;
                    num = num12;
                    num2 = num11;
                    str3 = str16;
                    str4 = str15;
                    str5 = str14;
                    dssVar = dssVar2;
                    dsfVar = dsfVar2;
                    dtqVar = dtqVar2;
                    str6 = str13;
                    num3 = num10;
                    num4 = num9;
                    str = str12;
                    dtnVar2 = dtnVar;
                    str12 = str;
                    num9 = num4;
                    num10 = num3;
                    str13 = str6;
                    dtqVar2 = dtqVar;
                    dsfVar2 = dsfVar;
                    dssVar2 = dssVar;
                    str14 = str5;
                    str15 = str4;
                    str16 = str3;
                    num11 = num2;
                    num12 = num;
                    str17 = str2;
                    z2 = z;
                    drzVar2 = drzVar;
                    str11 = str7;
                    break;
                case 19:
                    num5 = num6;
                    dut dutVar2 = (dut) acmVarP.i(dfxVar, 19, dur.b, dutVar);
                    i = i4 | Opcodes.ASM8;
                    dutVar = dutVar2;
                    i3 = i;
                    str7 = str11;
                    drzVar = drzVar2;
                    num6 = num5;
                    dtnVar = dtnVar2;
                    z = z2;
                    str2 = str17;
                    num = num12;
                    num2 = num11;
                    str3 = str16;
                    str4 = str15;
                    str5 = str14;
                    dssVar = dssVar2;
                    dsfVar = dsfVar2;
                    dtqVar = dtqVar2;
                    str6 = str13;
                    num3 = num10;
                    num4 = num9;
                    str = str12;
                    dtnVar2 = dtnVar;
                    str12 = str;
                    num9 = num4;
                    num10 = num3;
                    str13 = str6;
                    dtqVar2 = dtqVar;
                    dsfVar2 = dsfVar;
                    dssVar2 = dssVar;
                    str14 = str5;
                    str15 = str4;
                    str16 = str3;
                    num11 = num2;
                    num12 = num;
                    str17 = str2;
                    z2 = z;
                    drzVar2 = drzVar;
                    str11 = str7;
                    break;
                case 20:
                    num5 = num6;
                    i = i4 | 1048576;
                    num7 = (Integer) acmVarP.i(dfxVar, 20, bqj.b, num7);
                    i3 = i;
                    str7 = str11;
                    drzVar = drzVar2;
                    num6 = num5;
                    dtnVar = dtnVar2;
                    z = z2;
                    str2 = str17;
                    num = num12;
                    num2 = num11;
                    str3 = str16;
                    str4 = str15;
                    str5 = str14;
                    dssVar = dssVar2;
                    dsfVar = dsfVar2;
                    dtqVar = dtqVar2;
                    str6 = str13;
                    num3 = num10;
                    num4 = num9;
                    str = str12;
                    dtnVar2 = dtnVar;
                    str12 = str;
                    num9 = num4;
                    num10 = num3;
                    str13 = str6;
                    dtqVar2 = dtqVar;
                    dsfVar2 = dsfVar;
                    dssVar2 = dssVar;
                    str14 = str5;
                    str15 = str4;
                    str16 = str3;
                    num11 = num2;
                    num12 = num;
                    str17 = str2;
                    z2 = z;
                    drzVar2 = drzVar;
                    str11 = str7;
                    break;
                case 21:
                    num5 = num6;
                    i = i4 | 2097152;
                    duwVar = (duw) acmVarP.i(dfxVar, 21, duu.b, duwVar);
                    i3 = i;
                    str7 = str11;
                    drzVar = drzVar2;
                    num6 = num5;
                    dtnVar = dtnVar2;
                    z = z2;
                    str2 = str17;
                    num = num12;
                    num2 = num11;
                    str3 = str16;
                    str4 = str15;
                    str5 = str14;
                    dssVar = dssVar2;
                    dsfVar = dsfVar2;
                    dtqVar = dtqVar2;
                    str6 = str13;
                    num3 = num10;
                    num4 = num9;
                    str = str12;
                    dtnVar2 = dtnVar;
                    str12 = str;
                    num9 = num4;
                    num10 = num3;
                    str13 = str6;
                    dtqVar2 = dtqVar;
                    dsfVar2 = dsfVar;
                    dssVar2 = dssVar;
                    str14 = str5;
                    str15 = str4;
                    str16 = str3;
                    num11 = num2;
                    num12 = num;
                    str17 = str2;
                    z2 = z;
                    drzVar2 = drzVar;
                    str11 = str7;
                    break;
                case 22:
                    num5 = num6;
                    i = i4 | 4194304;
                    num8 = (Integer) acmVarP.i(dfxVar, 22, bqj.b, num8);
                    i3 = i;
                    str7 = str11;
                    drzVar = drzVar2;
                    num6 = num5;
                    dtnVar = dtnVar2;
                    z = z2;
                    str2 = str17;
                    num = num12;
                    num2 = num11;
                    str3 = str16;
                    str4 = str15;
                    str5 = str14;
                    dssVar = dssVar2;
                    dsfVar = dsfVar2;
                    dtqVar = dtqVar2;
                    str6 = str13;
                    num3 = num10;
                    num4 = num9;
                    str = str12;
                    dtnVar2 = dtnVar;
                    str12 = str;
                    num9 = num4;
                    num10 = num3;
                    str13 = str6;
                    dtqVar2 = dtqVar;
                    dsfVar2 = dsfVar;
                    dssVar2 = dssVar;
                    str14 = str5;
                    str15 = str4;
                    str16 = str3;
                    num11 = num2;
                    num12 = num;
                    str17 = str2;
                    z2 = z;
                    drzVar2 = drzVar;
                    str11 = str7;
                    break;
                case 23:
                    num5 = num6;
                    dtnVar2 = (dtn) acmVarP.i(dfxVar, 23, dtl.b, dtnVar2);
                    i2 = 8388608;
                    i3 = i4 | i2;
                    str7 = str11;
                    drzVar = drzVar2;
                    num6 = num5;
                    dtnVar = dtnVar2;
                    z = z2;
                    str2 = str17;
                    num = num12;
                    num2 = num11;
                    str3 = str16;
                    str4 = str15;
                    str5 = str14;
                    dssVar = dssVar2;
                    dsfVar = dsfVar2;
                    dtqVar = dtqVar2;
                    str6 = str13;
                    num3 = num10;
                    num4 = num9;
                    str = str12;
                    dtnVar2 = dtnVar;
                    str12 = str;
                    num9 = num4;
                    num10 = num3;
                    str13 = str6;
                    dtqVar2 = dtqVar;
                    dsfVar2 = dsfVar;
                    dssVar2 = dssVar;
                    str14 = str5;
                    str15 = str4;
                    str16 = str3;
                    num11 = num2;
                    num12 = num;
                    str17 = str2;
                    z2 = z;
                    drzVar2 = drzVar;
                    str11 = str7;
                    break;
                case 24:
                    num5 = num6;
                    duqVar = (duq) acmVarP.i(dfxVar, 24, duo.b, duqVar);
                    i2 = Http2Connection.OKHTTP_CLIENT_WINDOW_SIZE;
                    i3 = i4 | i2;
                    str7 = str11;
                    drzVar = drzVar2;
                    num6 = num5;
                    dtnVar = dtnVar2;
                    z = z2;
                    str2 = str17;
                    num = num12;
                    num2 = num11;
                    str3 = str16;
                    str4 = str15;
                    str5 = str14;
                    dssVar = dssVar2;
                    dsfVar = dsfVar2;
                    dtqVar = dtqVar2;
                    str6 = str13;
                    num3 = num10;
                    num4 = num9;
                    str = str12;
                    dtnVar2 = dtnVar;
                    str12 = str;
                    num9 = num4;
                    num10 = num3;
                    str13 = str6;
                    dtqVar2 = dtqVar;
                    dsfVar2 = dsfVar;
                    dssVar2 = dssVar;
                    str14 = str5;
                    str15 = str4;
                    str16 = str3;
                    num11 = num2;
                    num12 = num;
                    str17 = str2;
                    z2 = z;
                    drzVar2 = drzVar;
                    str11 = str7;
                    break;
                case 25:
                    num5 = num6;
                    str8 = (String) acmVarP.i(dfxVar, 25, dnh.b, str8);
                    i2 = 33554432;
                    i3 = i4 | i2;
                    str7 = str11;
                    drzVar = drzVar2;
                    num6 = num5;
                    dtnVar = dtnVar2;
                    z = z2;
                    str2 = str17;
                    num = num12;
                    num2 = num11;
                    str3 = str16;
                    str4 = str15;
                    str5 = str14;
                    dssVar = dssVar2;
                    dsfVar = dsfVar2;
                    dtqVar = dtqVar2;
                    str6 = str13;
                    num3 = num10;
                    num4 = num9;
                    str = str12;
                    dtnVar2 = dtnVar;
                    str12 = str;
                    num9 = num4;
                    num10 = num3;
                    str13 = str6;
                    dtqVar2 = dtqVar;
                    dsfVar2 = dsfVar;
                    dssVar2 = dssVar;
                    str14 = str5;
                    str15 = str4;
                    str16 = str3;
                    num11 = num2;
                    num12 = num;
                    str17 = str2;
                    z2 = z;
                    drzVar2 = drzVar;
                    str11 = str7;
                    break;
                case 26:
                    num5 = num6;
                    bool = (Boolean) acmVarP.i(dfxVar, 26, pv.b, bool);
                    i2 = 67108864;
                    i3 = i4 | i2;
                    str7 = str11;
                    drzVar = drzVar2;
                    num6 = num5;
                    dtnVar = dtnVar2;
                    z = z2;
                    str2 = str17;
                    num = num12;
                    num2 = num11;
                    str3 = str16;
                    str4 = str15;
                    str5 = str14;
                    dssVar = dssVar2;
                    dsfVar = dsfVar2;
                    dtqVar = dtqVar2;
                    str6 = str13;
                    num3 = num10;
                    num4 = num9;
                    str = str12;
                    dtnVar2 = dtnVar;
                    str12 = str;
                    num9 = num4;
                    num10 = num3;
                    str13 = str6;
                    dtqVar2 = dtqVar;
                    dsfVar2 = dsfVar;
                    dssVar2 = dssVar;
                    str14 = str5;
                    str15 = str4;
                    str16 = str3;
                    num11 = num2;
                    num12 = num;
                    str17 = str2;
                    z2 = z;
                    drzVar2 = drzVar;
                    str11 = str7;
                    break;
                case 27:
                    num5 = num6;
                    dtkVar2 = (dtk) acmVarP.i(dfxVar, 27, dti.b, dtkVar2);
                    i2 = 134217728;
                    i3 = i4 | i2;
                    str7 = str11;
                    drzVar = drzVar2;
                    num6 = num5;
                    dtnVar = dtnVar2;
                    z = z2;
                    str2 = str17;
                    num = num12;
                    num2 = num11;
                    str3 = str16;
                    str4 = str15;
                    str5 = str14;
                    dssVar = dssVar2;
                    dsfVar = dsfVar2;
                    dtqVar = dtqVar2;
                    str6 = str13;
                    num3 = num10;
                    num4 = num9;
                    str = str12;
                    dtnVar2 = dtnVar;
                    str12 = str;
                    num9 = num4;
                    num10 = num3;
                    str13 = str6;
                    dtqVar2 = dtqVar;
                    dsfVar2 = dsfVar;
                    dssVar2 = dssVar;
                    str14 = str5;
                    str15 = str4;
                    str16 = str3;
                    num11 = num2;
                    num12 = num;
                    str17 = str2;
                    z2 = z;
                    drzVar2 = drzVar;
                    str11 = str7;
                    break;
                default:
                    throw new bsd(iF);
            }
        }
        Boolean bool5 = bool;
        Integer num20 = num6;
        String str26 = str11;
        String str27 = str12;
        Integer num21 = num9;
        dtn dtnVar3 = dtnVar2;
        acmVarP._bp(dfxVar);
        Integer num22 = num11;
        Integer num23 = num12;
        duw duwVar2 = duwVar;
        Integer num24 = num8;
        String str28 = str14;
        String str29 = str10;
        return new ejy(i3, str26, str27, num21, num10, str13, dtqVar2, dsfVar2, dssVar2, str28, str15, str16, num22, num23, str17, drzVar2, num20, dukVar, str9, str29, dutVar, num7, duwVar2, num24, dtnVar3, duqVar, str8, bool5, dtkVar2);
    }

    @Override // me.hd.wauxv.obf.btd
    public final void c(avt avtVar, Object obj) {
        ejy ejyVar = (ejy) obj;
        dfx dfxVar = descriptor;
        acn acnVarO = avtVar.o(dfxVar);
        dnh dnhVar = dnh.b;
        acnVarO.m(dfxVar, 0, dnhVar, ejyVar.a);
        acnVarO.m(dfxVar, 1, dnhVar, ejyVar.b);
        bqj bqjVar = bqj.b;
        acnVarO.m(dfxVar, 2, bqjVar, ejyVar.c);
        acnVarO.m(dfxVar, 3, bqjVar, ejyVar.d);
        acnVarO.m(dfxVar, 4, dnhVar, ejyVar.e);
        acnVarO.m(dfxVar, 5, dto.b, ejyVar.f);
        acnVarO.m(dfxVar, 6, dsd.b, ejyVar.g);
        acnVarO.m(dfxVar, 7, dsq.b, ejyVar.h);
        acnVarO.m(dfxVar, 8, dnhVar, ejyVar.i);
        acnVarO.m(dfxVar, 9, dnhVar, ejyVar.j);
        acnVarO.m(dfxVar, 10, dnhVar, ejyVar.k);
        acnVarO.m(dfxVar, 11, bqjVar, ejyVar.l);
        acnVarO.m(dfxVar, 12, bqjVar, ejyVar.m);
        acnVarO.m(dfxVar, 13, dnhVar, ejyVar.n);
        acnVarO.m(dfxVar, 14, drx.b, ejyVar.o);
        acnVarO.m(dfxVar, 15, bqjVar, ejyVar.p);
        acnVarO.m(dfxVar, 16, dui.b, ejyVar.q);
        acnVarO.m(dfxVar, 17, dnhVar, ejyVar.r);
        acnVarO.m(dfxVar, 18, dnhVar, ejyVar.s);
        acnVarO.m(dfxVar, 19, dur.b, ejyVar.t);
        acnVarO.m(dfxVar, 20, bqjVar, ejyVar.u);
        acnVarO.m(dfxVar, 21, duu.b, ejyVar.v);
        acnVarO.m(dfxVar, 22, bqjVar, ejyVar.w);
        acnVarO.m(dfxVar, 23, dtl.b, ejyVar.x);
        acnVarO.m(dfxVar, 24, duo.b, ejyVar.y);
        acnVarO.m(dfxVar, 25, dnhVar, ejyVar.z);
        acnVarO.m(dfxVar, 26, pv.b, ejyVar.aa);
        acnVarO.m(dfxVar, 27, dti.b, ejyVar.ab);
        acnVarO.a(dfxVar);
    }

    @Override // me.hd.wauxv.obf.bgx
    public final btd[] d() {
        dnh dnhVar = dnh.b;
        btd btdVarT = aye.t(dnhVar);
        btd btdVarT2 = aye.t(dnhVar);
        bqj bqjVar = bqj.b;
        return new btd[]{btdVarT, btdVarT2, aye.t(bqjVar), aye.t(bqjVar), aye.t(dnhVar), aye.t(dto.b), aye.t(dsd.b), aye.t(dsq.b), aye.t(dnhVar), aye.t(dnhVar), aye.t(dnhVar), aye.t(bqjVar), aye.t(bqjVar), aye.t(dnhVar), aye.t(drx.b), aye.t(bqjVar), aye.t(dui.b), aye.t(dnhVar), aye.t(dnhVar), aye.t(dur.b), aye.t(bqjVar), aye.t(duu.b), aye.t(bqjVar), aye.t(dtl.b), aye.t(duo.b), aye.t(dnhVar), aye.t(pv.b), aye.t(dti.b)};
    }

    @Override // me.hd.wauxv.obf.btd
    public final dfx getDescriptor() {
        return descriptor;
    }
}
