package me.hd.wauxv.obf;

import java.util.List;
import net.bytebuddy.jar.asm.Opcodes;
import okhttp3.internal.http2.Http2Connection;

/* JADX INFO: compiled from: r8-map-id-b9de5da7d0413052737328a4e696e1bcc3145db8f6a41e1e318485e124198cd6 */
/* JADX INFO: loaded from: classes.dex */
public final /* synthetic */ class dsz implements bgx {
    public static final dsz b;
    private static final dfx descriptor;

    static {
        dsz dszVar = new dsz();
        b = dszVar;
        cuc cucVar = new cuc(cnb.z(-190597763693354L), dszVar, 28);
        bjs.y(-178735064021802L, cucVar, false, 1);
        bjs.y(-179194625522474L, cucVar, false, 2);
        bjs.y(-179155970816810L, cucVar, false, 3);
        bjs.y(-179134495980330L, cucVar, false, 4);
        bjs.y(-179087251340074L, cucVar, false, 5);
        bjs.y(-179117316111146L, cucVar, false, 6);
        bjs.y(-179078661405482L, cucVar, false, 7);
        bjs.y(-178997057026858L, cucVar, false, 8);
        bjs.y(-178971287223082L, cucVar, false, 9);
        bjs.y(-178344221997866L, cucVar, false, 10);
        bjs.y(-178309862259498L, cucVar, false, 11);
        bjs.y(-178292682390314L, cucVar, false, 12);
        bjs.y(-178176718273322L, cucVar, false, 13);
        bjs.y(-178640574741290L, cucVar, false, 14);
        bjs.y(-178636279773994L, cucVar, false, 15);
        bjs.y(-178550380428074L, cucVar, false, 16);
        bjs.y(-178533200558890L, cucVar, false, 17);
        bjs.y(-178438711278378L, cucVar, false, 18);
        bjs.y(-178430121343786L, cucVar, false, 19);
        bjs.y(-180010669308714L, cucVar, false, 20);
        bjs.y(-179929064930090L, cucVar, false, 21);
        bjs.y(-179860345453354L, cucVar, false, 22);
        bjs.y(-179791625976618L, cucVar, false, 23);
        bjs.y(-180221122706218L, cucVar, false, 24);
        bjs.y(-180173878065962L, cucVar, false, 25);
        bjs.y(-180135223360298L, cucVar, false, 26);
        bjs.y(-180053618981674L, cucVar, false, 28);
        bjs.y(-179473798396714L, cucVar, false, 29);
        descriptor = cucVar;
    }

    @Override // me.hd.wauxv.obf.btd
    public final Object a(ajt ajtVar) {
        Integer num;
        String str;
        Integer num2;
        String str2;
        String str3;
        String str4;
        Long l;
        String str5;
        List list;
        Integer num3;
        Integer num4;
        String str6;
        String str7;
        String str8;
        String str9;
        String str10;
        boolean z;
        dxt dxtVar;
        String str11;
        int i;
        int i2;
        dfx dfxVar = descriptor;
        acm acmVarP = ajtVar.p(dfxVar);
        btt[] bttVarArr = dtb.a;
        acmVarP.getClass();
        String str12 = null;
        dxt dxtVar2 = null;
        String str13 = null;
        Integer num5 = null;
        String str14 = null;
        String str15 = null;
        String str16 = null;
        String str17 = null;
        String str18 = null;
        Integer num6 = null;
        String str19 = null;
        Integer num7 = null;
        String str20 = null;
        String str21 = null;
        String str22 = null;
        String str23 = null;
        String str24 = null;
        String str25 = null;
        Integer num8 = null;
        Integer num9 = null;
        List list2 = null;
        String str26 = null;
        Long l2 = null;
        String str27 = null;
        String str28 = null;
        String str29 = null;
        Integer num10 = null;
        String str30 = null;
        int i3 = 0;
        boolean z2 = true;
        while (z2) {
            int i4 = i3;
            int iF = acmVarP.f(dfxVar);
            switch (iF) {
                case -1:
                    String str31 = str23;
                    i3 = i4;
                    String str32 = str13;
                    String str33 = str21;
                    num = num5;
                    str = str22;
                    num2 = num10;
                    str16 = str16;
                    str2 = str29;
                    str3 = str28;
                    str4 = str27;
                    l = l2;
                    str5 = str26;
                    list = list2;
                    num3 = num9;
                    num4 = num8;
                    str6 = str25;
                    str7 = str24;
                    str8 = str31;
                    str9 = str33;
                    str13 = str32;
                    str10 = str30;
                    z = false;
                    num5 = num;
                    str22 = str;
                    str23 = str8;
                    str24 = str7;
                    str25 = str6;
                    num8 = num4;
                    num9 = num3;
                    list2 = list;
                    str26 = str5;
                    l2 = l;
                    str27 = str4;
                    str28 = str3;
                    str29 = str2;
                    num10 = num2;
                    z2 = z;
                    str30 = str10;
                    str21 = str9;
                    break;
                case 0:
                    dxtVar = dxtVar2;
                    String str34 = str23;
                    String str35 = str13;
                    String str36 = str21;
                    num = num5;
                    String str37 = (String) acmVarP.i(dfxVar, 0, dnh.b, str36);
                    i3 = i4 | 1;
                    str = str22;
                    str13 = str35;
                    str16 = str16;
                    str10 = str30;
                    z = z2;
                    num2 = num10;
                    str2 = str29;
                    str3 = str28;
                    str4 = str27;
                    l = l2;
                    str5 = str26;
                    list = list2;
                    num3 = num9;
                    num4 = num8;
                    str6 = str25;
                    str7 = str24;
                    str8 = str34;
                    str9 = str37;
                    dxtVar2 = dxtVar;
                    num5 = num;
                    str22 = str;
                    str23 = str8;
                    str24 = str7;
                    str25 = str6;
                    num8 = num4;
                    num9 = num3;
                    list2 = list;
                    str26 = str5;
                    l2 = l;
                    str27 = str4;
                    str28 = str3;
                    str29 = str2;
                    num10 = num2;
                    z2 = z;
                    str30 = str10;
                    str21 = str9;
                    break;
                case 1:
                    String str38 = str13;
                    String str39 = str23;
                    i3 = i4 | 2;
                    str = (String) acmVarP.i(dfxVar, 1, dnh.b, str22);
                    str13 = str38;
                    str16 = str16;
                    dxtVar2 = dxtVar2;
                    str10 = str30;
                    z = z2;
                    num2 = num10;
                    str2 = str29;
                    str3 = str28;
                    str4 = str27;
                    l = l2;
                    str5 = str26;
                    list = list2;
                    num3 = num9;
                    num4 = num8;
                    str6 = str25;
                    str7 = str24;
                    str8 = str39;
                    str9 = str21;
                    num = num5;
                    num5 = num;
                    str22 = str;
                    str23 = str8;
                    str24 = str7;
                    str25 = str6;
                    num8 = num4;
                    num9 = num3;
                    list2 = list;
                    str26 = str5;
                    l2 = l;
                    str27 = str4;
                    str28 = str3;
                    str29 = str2;
                    num10 = num2;
                    z2 = z;
                    str30 = str10;
                    str21 = str9;
                    break;
                case 2:
                    dxtVar = dxtVar2;
                    String str40 = (String) acmVarP.i(dfxVar, 2, dnh.b, str23);
                    i3 = i4 | 4;
                    str9 = str21;
                    str = str22;
                    str13 = str13;
                    str16 = str16;
                    num = num5;
                    str10 = str30;
                    z = z2;
                    num2 = num10;
                    str2 = str29;
                    str3 = str28;
                    str4 = str27;
                    l = l2;
                    str5 = str26;
                    list = list2;
                    num3 = num9;
                    num4 = num8;
                    str6 = str25;
                    str7 = str24;
                    str8 = str40;
                    dxtVar2 = dxtVar;
                    num5 = num;
                    str22 = str;
                    str23 = str8;
                    str24 = str7;
                    str25 = str6;
                    num8 = num4;
                    num9 = num3;
                    list2 = list;
                    str26 = str5;
                    l2 = l;
                    str27 = str4;
                    str28 = str3;
                    str29 = str2;
                    num10 = num2;
                    z2 = z;
                    str30 = str10;
                    str21 = str9;
                    break;
                case 3:
                    dxtVar = dxtVar2;
                    String str41 = (String) acmVarP.i(dfxVar, 3, dnh.b, str24);
                    i3 = i4 | 8;
                    str9 = str21;
                    str8 = str23;
                    str13 = str13;
                    str16 = str16;
                    num = num5;
                    str = str22;
                    str10 = str30;
                    z = z2;
                    num2 = num10;
                    str2 = str29;
                    str3 = str28;
                    str4 = str27;
                    l = l2;
                    str5 = str26;
                    list = list2;
                    num3 = num9;
                    num4 = num8;
                    str6 = str25;
                    str7 = str41;
                    dxtVar2 = dxtVar;
                    num5 = num;
                    str22 = str;
                    str23 = str8;
                    str24 = str7;
                    str25 = str6;
                    num8 = num4;
                    num9 = num3;
                    list2 = list;
                    str26 = str5;
                    l2 = l;
                    str27 = str4;
                    str28 = str3;
                    str29 = str2;
                    num10 = num2;
                    z2 = z;
                    str30 = str10;
                    str21 = str9;
                    break;
                case 4:
                    dxtVar = dxtVar2;
                    String str42 = (String) acmVarP.i(dfxVar, 4, dnh.b, str25);
                    i3 = i4 | 16;
                    str9 = str21;
                    str7 = str24;
                    str13 = str13;
                    str16 = str16;
                    num = num5;
                    str8 = str23;
                    str10 = str30;
                    str = str22;
                    z = z2;
                    num2 = num10;
                    str2 = str29;
                    str3 = str28;
                    str4 = str27;
                    l = l2;
                    str5 = str26;
                    list = list2;
                    num3 = num9;
                    num4 = num8;
                    str6 = str42;
                    dxtVar2 = dxtVar;
                    num5 = num;
                    str22 = str;
                    str23 = str8;
                    str24 = str7;
                    str25 = str6;
                    num8 = num4;
                    num9 = num3;
                    list2 = list;
                    str26 = str5;
                    l2 = l;
                    str27 = str4;
                    str28 = str3;
                    str29 = str2;
                    num10 = num2;
                    z2 = z;
                    str30 = str10;
                    str21 = str9;
                    break;
                case 5:
                    dxtVar = dxtVar2;
                    Integer num11 = (Integer) acmVarP.i(dfxVar, 5, bqj.b, num8);
                    i3 = i4 | 32;
                    str9 = str21;
                    str6 = str25;
                    str13 = str13;
                    str16 = str16;
                    num = num5;
                    str7 = str24;
                    str10 = str30;
                    str8 = str23;
                    z = z2;
                    str = str22;
                    num2 = num10;
                    str2 = str29;
                    str3 = str28;
                    str4 = str27;
                    l = l2;
                    str5 = str26;
                    list = list2;
                    num3 = num9;
                    num4 = num11;
                    dxtVar2 = dxtVar;
                    num5 = num;
                    str22 = str;
                    str23 = str8;
                    str24 = str7;
                    str25 = str6;
                    num8 = num4;
                    num9 = num3;
                    list2 = list;
                    str26 = str5;
                    l2 = l;
                    str27 = str4;
                    str28 = str3;
                    str29 = str2;
                    num10 = num2;
                    z2 = z;
                    str30 = str10;
                    str21 = str9;
                    break;
                case 6:
                    dxtVar = dxtVar2;
                    Integer num12 = (Integer) acmVarP.i(dfxVar, 6, bqj.b, num9);
                    i3 = i4 | 64;
                    str9 = str21;
                    num4 = num8;
                    str13 = str13;
                    str16 = str16;
                    num = num5;
                    str6 = str25;
                    str10 = str30;
                    str7 = str24;
                    z = z2;
                    str8 = str23;
                    num2 = num10;
                    str = str22;
                    str2 = str29;
                    str3 = str28;
                    str4 = str27;
                    l = l2;
                    str5 = str26;
                    list = list2;
                    num3 = num12;
                    dxtVar2 = dxtVar;
                    num5 = num;
                    str22 = str;
                    str23 = str8;
                    str24 = str7;
                    str25 = str6;
                    num8 = num4;
                    num9 = num3;
                    list2 = list;
                    str26 = str5;
                    l2 = l;
                    str27 = str4;
                    str28 = str3;
                    str29 = str2;
                    num10 = num2;
                    z2 = z;
                    str30 = str10;
                    str21 = str9;
                    break;
                case 7:
                    dxtVar = dxtVar2;
                    List list3 = (List) acmVarP.i(dfxVar, 7, (btd) bttVarArr[7].getValue(), list2);
                    i3 = i4 | 128;
                    str9 = str21;
                    num3 = num9;
                    str13 = str13;
                    str16 = str16;
                    num = num5;
                    num4 = num8;
                    str10 = str30;
                    str6 = str25;
                    z = z2;
                    str7 = str24;
                    num2 = num10;
                    str8 = str23;
                    str2 = str29;
                    str = str22;
                    str3 = str28;
                    str4 = str27;
                    l = l2;
                    str5 = str26;
                    list = list3;
                    dxtVar2 = dxtVar;
                    num5 = num;
                    str22 = str;
                    str23 = str8;
                    str24 = str7;
                    str25 = str6;
                    num8 = num4;
                    num9 = num3;
                    list2 = list;
                    str26 = str5;
                    l2 = l;
                    str27 = str4;
                    str28 = str3;
                    str29 = str2;
                    num10 = num2;
                    z2 = z;
                    str30 = str10;
                    str21 = str9;
                    break;
                case 8:
                    dxtVar = dxtVar2;
                    String str43 = (String) acmVarP.i(dfxVar, 8, dnh.b, str26);
                    i3 = i4 | 256;
                    str9 = str21;
                    list = list2;
                    str13 = str13;
                    str16 = str16;
                    num = num5;
                    num3 = num9;
                    str10 = str30;
                    num4 = num8;
                    z = z2;
                    str6 = str25;
                    num2 = num10;
                    str7 = str24;
                    str2 = str29;
                    str8 = str23;
                    str3 = str28;
                    str = str22;
                    str4 = str27;
                    l = l2;
                    str5 = str43;
                    dxtVar2 = dxtVar;
                    num5 = num;
                    str22 = str;
                    str23 = str8;
                    str24 = str7;
                    str25 = str6;
                    num8 = num4;
                    num9 = num3;
                    list2 = list;
                    str26 = str5;
                    l2 = l;
                    str27 = str4;
                    str28 = str3;
                    str29 = str2;
                    num10 = num2;
                    z2 = z;
                    str30 = str10;
                    str21 = str9;
                    break;
                case 9:
                    dxtVar = dxtVar2;
                    Long l3 = (Long) acmVarP.i(dfxVar, 9, bya.b, l2);
                    i3 = i4 | 512;
                    str9 = str21;
                    str5 = str26;
                    str13 = str13;
                    str16 = str16;
                    num = num5;
                    list = list2;
                    str10 = str30;
                    num3 = num9;
                    z = z2;
                    num4 = num8;
                    num2 = num10;
                    str6 = str25;
                    str2 = str29;
                    str7 = str24;
                    str3 = str28;
                    str8 = str23;
                    str4 = str27;
                    l = l3;
                    str = str22;
                    dxtVar2 = dxtVar;
                    num5 = num;
                    str22 = str;
                    str23 = str8;
                    str24 = str7;
                    str25 = str6;
                    num8 = num4;
                    num9 = num3;
                    list2 = list;
                    str26 = str5;
                    l2 = l;
                    str27 = str4;
                    str28 = str3;
                    str29 = str2;
                    num10 = num2;
                    z2 = z;
                    str30 = str10;
                    str21 = str9;
                    break;
                case 10:
                    dxt dxtVar3 = dxtVar2;
                    String str44 = (String) acmVarP.i(dfxVar, 10, dnh.b, str27);
                    i3 = i4 | 1024;
                    str9 = str21;
                    l = l2;
                    str13 = str13;
                    str16 = str16;
                    num = num5;
                    str5 = str26;
                    str10 = str30;
                    list = list2;
                    z = z2;
                    num3 = num9;
                    num2 = num10;
                    num4 = num8;
                    str2 = str29;
                    str6 = str25;
                    str3 = str28;
                    str4 = str44;
                    str7 = str24;
                    dxtVar2 = dxtVar3;
                    str8 = str23;
                    str = str22;
                    num5 = num;
                    str22 = str;
                    str23 = str8;
                    str24 = str7;
                    str25 = str6;
                    num8 = num4;
                    num9 = num3;
                    list2 = list;
                    str26 = str5;
                    l2 = l;
                    str27 = str4;
                    str28 = str3;
                    str29 = str2;
                    num10 = num2;
                    z2 = z;
                    str30 = str10;
                    str21 = str9;
                    break;
                case 11:
                    dxt dxtVar4 = dxtVar2;
                    String str45 = (String) acmVarP.i(dfxVar, 11, dnh.b, str28);
                    i3 = i4 | 2048;
                    str9 = str21;
                    str4 = str27;
                    str13 = str13;
                    str16 = str16;
                    num = num5;
                    l = l2;
                    str10 = str30;
                    str5 = str26;
                    z = z2;
                    list = list2;
                    num2 = num10;
                    num3 = num9;
                    str2 = str29;
                    str3 = str45;
                    num4 = num8;
                    dxtVar2 = dxtVar4;
                    str6 = str25;
                    str7 = str24;
                    str8 = str23;
                    str = str22;
                    num5 = num;
                    str22 = str;
                    str23 = str8;
                    str24 = str7;
                    str25 = str6;
                    num8 = num4;
                    num9 = num3;
                    list2 = list;
                    str26 = str5;
                    l2 = l;
                    str27 = str4;
                    str28 = str3;
                    str29 = str2;
                    num10 = num2;
                    z2 = z;
                    str30 = str10;
                    str21 = str9;
                    break;
                case 12:
                    dxt dxtVar5 = dxtVar2;
                    String str46 = (String) acmVarP.i(dfxVar, 12, dnh.b, str29);
                    i3 = i4 | 4096;
                    str9 = str21;
                    str3 = str28;
                    str13 = str13;
                    str16 = str16;
                    num = num5;
                    str4 = str27;
                    str10 = str30;
                    l = l2;
                    z = z2;
                    str5 = str26;
                    num2 = num10;
                    str2 = str46;
                    list = list2;
                    dxtVar2 = dxtVar5;
                    num3 = num9;
                    num4 = num8;
                    str6 = str25;
                    str7 = str24;
                    str8 = str23;
                    str = str22;
                    num5 = num;
                    str22 = str;
                    str23 = str8;
                    str24 = str7;
                    str25 = str6;
                    num8 = num4;
                    num9 = num3;
                    list2 = list;
                    str26 = str5;
                    l2 = l;
                    str27 = str4;
                    str28 = str3;
                    str29 = str2;
                    num10 = num2;
                    z2 = z;
                    str30 = str10;
                    str21 = str9;
                    break;
                case 13:
                    dxt dxtVar6 = dxtVar2;
                    Integer num13 = (Integer) acmVarP.i(dfxVar, 13, bqj.b, num10);
                    i3 = i4 | 8192;
                    str9 = str21;
                    str2 = str29;
                    str13 = str13;
                    str16 = str16;
                    num = num5;
                    str3 = str28;
                    str10 = str30;
                    str4 = str27;
                    z = z2;
                    num2 = num13;
                    l = l2;
                    dxtVar2 = dxtVar6;
                    str5 = str26;
                    list = list2;
                    num3 = num9;
                    num4 = num8;
                    str6 = str25;
                    str7 = str24;
                    str8 = str23;
                    str = str22;
                    num5 = num;
                    str22 = str;
                    str23 = str8;
                    str24 = str7;
                    str25 = str6;
                    num8 = num4;
                    num9 = num3;
                    list2 = list;
                    str26 = str5;
                    l2 = l;
                    str27 = str4;
                    str28 = str3;
                    str29 = str2;
                    num10 = num2;
                    z2 = z;
                    str30 = str10;
                    str21 = str9;
                    break;
                case 14:
                    i3 = i4 | 16384;
                    str10 = (String) acmVarP.i(dfxVar, 14, dnh.b, str30);
                    str9 = str21;
                    z = z2;
                    str16 = str16;
                    dxtVar2 = dxtVar2;
                    num = num5;
                    num2 = num10;
                    str2 = str29;
                    str3 = str28;
                    str4 = str27;
                    l = l2;
                    str5 = str26;
                    list = list2;
                    num3 = num9;
                    num4 = num8;
                    str6 = str25;
                    str7 = str24;
                    str8 = str23;
                    str = str22;
                    num5 = num;
                    str22 = str;
                    str23 = str8;
                    str24 = str7;
                    str25 = str6;
                    num8 = num4;
                    num9 = num3;
                    list2 = list;
                    str26 = str5;
                    l2 = l;
                    str27 = str4;
                    str28 = str3;
                    str29 = str2;
                    num10 = num2;
                    z2 = z;
                    str30 = str10;
                    str21 = str9;
                    break;
                case 15:
                    dxt dxtVar7 = dxtVar2;
                    i3 = i4 | 32768;
                    str16 = (String) acmVarP.i(dfxVar, 15, dnh.b, str16);
                    str9 = str21;
                    str10 = str30;
                    dxtVar2 = dxtVar7;
                    num = num5;
                    z = z2;
                    num2 = num10;
                    str2 = str29;
                    str3 = str28;
                    str4 = str27;
                    l = l2;
                    str5 = str26;
                    list = list2;
                    num3 = num9;
                    num4 = num8;
                    str6 = str25;
                    str7 = str24;
                    str8 = str23;
                    str = str22;
                    num5 = num;
                    str22 = str;
                    str23 = str8;
                    str24 = str7;
                    str25 = str6;
                    num8 = num4;
                    num9 = num3;
                    list2 = list;
                    str26 = str5;
                    l2 = l;
                    str27 = str4;
                    str28 = str3;
                    str29 = str2;
                    num10 = num2;
                    z2 = z;
                    str30 = str10;
                    str21 = str9;
                    break;
                case 16:
                    str11 = str16;
                    i = i4 | 65536;
                    str17 = (String) acmVarP.i(dfxVar, 16, dnh.b, str17);
                    i3 = i;
                    str9 = str21;
                    str10 = str30;
                    str16 = str11;
                    num = num5;
                    z = z2;
                    num2 = num10;
                    str2 = str29;
                    str3 = str28;
                    str4 = str27;
                    l = l2;
                    str5 = str26;
                    list = list2;
                    num3 = num9;
                    num4 = num8;
                    str6 = str25;
                    str7 = str24;
                    str8 = str23;
                    str = str22;
                    num5 = num;
                    str22 = str;
                    str23 = str8;
                    str24 = str7;
                    str25 = str6;
                    num8 = num4;
                    num9 = num3;
                    list2 = list;
                    str26 = str5;
                    l2 = l;
                    str27 = str4;
                    str28 = str3;
                    str29 = str2;
                    num10 = num2;
                    z2 = z;
                    str30 = str10;
                    str21 = str9;
                    break;
                case 17:
                    str11 = str16;
                    i = i4 | 131072;
                    str18 = (String) acmVarP.i(dfxVar, 17, dnh.b, str18);
                    i3 = i;
                    str9 = str21;
                    str10 = str30;
                    str16 = str11;
                    num = num5;
                    z = z2;
                    num2 = num10;
                    str2 = str29;
                    str3 = str28;
                    str4 = str27;
                    l = l2;
                    str5 = str26;
                    list = list2;
                    num3 = num9;
                    num4 = num8;
                    str6 = str25;
                    str7 = str24;
                    str8 = str23;
                    str = str22;
                    num5 = num;
                    str22 = str;
                    str23 = str8;
                    str24 = str7;
                    str25 = str6;
                    num8 = num4;
                    num9 = num3;
                    list2 = list;
                    str26 = str5;
                    l2 = l;
                    str27 = str4;
                    str28 = str3;
                    str29 = str2;
                    num10 = num2;
                    z2 = z;
                    str30 = str10;
                    str21 = str9;
                    break;
                case 18:
                    str11 = str16;
                    i = i4 | 262144;
                    num6 = (Integer) acmVarP.i(dfxVar, 18, bqj.b, num6);
                    i3 = i;
                    str9 = str21;
                    str10 = str30;
                    str16 = str11;
                    num = num5;
                    z = z2;
                    num2 = num10;
                    str2 = str29;
                    str3 = str28;
                    str4 = str27;
                    l = l2;
                    str5 = str26;
                    list = list2;
                    num3 = num9;
                    num4 = num8;
                    str6 = str25;
                    str7 = str24;
                    str8 = str23;
                    str = str22;
                    num5 = num;
                    str22 = str;
                    str23 = str8;
                    str24 = str7;
                    str25 = str6;
                    num8 = num4;
                    num9 = num3;
                    list2 = list;
                    str26 = str5;
                    l2 = l;
                    str27 = str4;
                    str28 = str3;
                    str29 = str2;
                    num10 = num2;
                    z2 = z;
                    str30 = str10;
                    str21 = str9;
                    break;
                case 19:
                    str11 = str16;
                    String str47 = (String) acmVarP.i(dfxVar, 19, dnh.b, str19);
                    i = i4 | Opcodes.ASM8;
                    str19 = str47;
                    i3 = i;
                    str9 = str21;
                    str10 = str30;
                    str16 = str11;
                    num = num5;
                    z = z2;
                    num2 = num10;
                    str2 = str29;
                    str3 = str28;
                    str4 = str27;
                    l = l2;
                    str5 = str26;
                    list = list2;
                    num3 = num9;
                    num4 = num8;
                    str6 = str25;
                    str7 = str24;
                    str8 = str23;
                    str = str22;
                    num5 = num;
                    str22 = str;
                    str23 = str8;
                    str24 = str7;
                    str25 = str6;
                    num8 = num4;
                    num9 = num3;
                    list2 = list;
                    str26 = str5;
                    l2 = l;
                    str27 = str4;
                    str28 = str3;
                    str29 = str2;
                    num10 = num2;
                    z2 = z;
                    str30 = str10;
                    str21 = str9;
                    break;
                case 20:
                    str11 = str16;
                    i = i4 | 1048576;
                    num7 = (Integer) acmVarP.i(dfxVar, 20, bqj.b, num7);
                    i3 = i;
                    str9 = str21;
                    str10 = str30;
                    str16 = str11;
                    num = num5;
                    z = z2;
                    num2 = num10;
                    str2 = str29;
                    str3 = str28;
                    str4 = str27;
                    l = l2;
                    str5 = str26;
                    list = list2;
                    num3 = num9;
                    num4 = num8;
                    str6 = str25;
                    str7 = str24;
                    str8 = str23;
                    str = str22;
                    num5 = num;
                    str22 = str;
                    str23 = str8;
                    str24 = str7;
                    str25 = str6;
                    num8 = num4;
                    num9 = num3;
                    list2 = list;
                    str26 = str5;
                    l2 = l;
                    str27 = str4;
                    str28 = str3;
                    str29 = str2;
                    num10 = num2;
                    z2 = z;
                    str30 = str10;
                    str21 = str9;
                    break;
                case 21:
                    str11 = str16;
                    i = i4 | 2097152;
                    str20 = (String) acmVarP.i(dfxVar, 21, dnh.b, str20);
                    i3 = i;
                    str9 = str21;
                    str10 = str30;
                    str16 = str11;
                    num = num5;
                    z = z2;
                    num2 = num10;
                    str2 = str29;
                    str3 = str28;
                    str4 = str27;
                    l = l2;
                    str5 = str26;
                    list = list2;
                    num3 = num9;
                    num4 = num8;
                    str6 = str25;
                    str7 = str24;
                    str8 = str23;
                    str = str22;
                    num5 = num;
                    str22 = str;
                    str23 = str8;
                    str24 = str7;
                    str25 = str6;
                    num8 = num4;
                    num9 = num3;
                    list2 = list;
                    str26 = str5;
                    l2 = l;
                    str27 = str4;
                    str28 = str3;
                    str29 = str2;
                    num10 = num2;
                    z2 = z;
                    str30 = str10;
                    str21 = str9;
                    break;
                case 22:
                    str11 = str16;
                    str12 = (String) acmVarP.i(dfxVar, 22, dnh.b, str12);
                    i2 = 4194304;
                    i3 = i4 | i2;
                    str9 = str21;
                    str10 = str30;
                    str16 = str11;
                    num = num5;
                    z = z2;
                    num2 = num10;
                    str2 = str29;
                    str3 = str28;
                    str4 = str27;
                    l = l2;
                    str5 = str26;
                    list = list2;
                    num3 = num9;
                    num4 = num8;
                    str6 = str25;
                    str7 = str24;
                    str8 = str23;
                    str = str22;
                    num5 = num;
                    str22 = str;
                    str23 = str8;
                    str24 = str7;
                    str25 = str6;
                    num8 = num4;
                    num9 = num3;
                    list2 = list;
                    str26 = str5;
                    l2 = l;
                    str27 = str4;
                    str28 = str3;
                    str29 = str2;
                    num10 = num2;
                    z2 = z;
                    str30 = str10;
                    str21 = str9;
                    break;
                case 23:
                    str11 = str16;
                    str14 = (String) acmVarP.i(dfxVar, 23, dnh.b, str14);
                    i2 = 8388608;
                    i3 = i4 | i2;
                    str9 = str21;
                    str10 = str30;
                    str16 = str11;
                    num = num5;
                    z = z2;
                    num2 = num10;
                    str2 = str29;
                    str3 = str28;
                    str4 = str27;
                    l = l2;
                    str5 = str26;
                    list = list2;
                    num3 = num9;
                    num4 = num8;
                    str6 = str25;
                    str7 = str24;
                    str8 = str23;
                    str = str22;
                    num5 = num;
                    str22 = str;
                    str23 = str8;
                    str24 = str7;
                    str25 = str6;
                    num8 = num4;
                    num9 = num3;
                    list2 = list;
                    str26 = str5;
                    l2 = l;
                    str27 = str4;
                    str28 = str3;
                    str29 = str2;
                    num10 = num2;
                    z2 = z;
                    str30 = str10;
                    str21 = str9;
                    break;
                case 24:
                    str11 = str16;
                    str15 = (String) acmVarP.i(dfxVar, 24, dnh.b, str15);
                    i2 = Http2Connection.OKHTTP_CLIENT_WINDOW_SIZE;
                    i3 = i4 | i2;
                    str9 = str21;
                    str10 = str30;
                    str16 = str11;
                    num = num5;
                    z = z2;
                    num2 = num10;
                    str2 = str29;
                    str3 = str28;
                    str4 = str27;
                    l = l2;
                    str5 = str26;
                    list = list2;
                    num3 = num9;
                    num4 = num8;
                    str6 = str25;
                    str7 = str24;
                    str8 = str23;
                    str = str22;
                    num5 = num;
                    str22 = str;
                    str23 = str8;
                    str24 = str7;
                    str25 = str6;
                    num8 = num4;
                    num9 = num3;
                    list2 = list;
                    str26 = str5;
                    l2 = l;
                    str27 = str4;
                    str28 = str3;
                    str29 = str2;
                    num10 = num2;
                    z2 = z;
                    str30 = str10;
                    str21 = str9;
                    break;
                case 25:
                    str11 = str16;
                    num5 = (Integer) acmVarP.i(dfxVar, 25, bqj.b, num5);
                    i2 = 33554432;
                    i3 = i4 | i2;
                    str9 = str21;
                    str10 = str30;
                    str16 = str11;
                    num = num5;
                    z = z2;
                    num2 = num10;
                    str2 = str29;
                    str3 = str28;
                    str4 = str27;
                    l = l2;
                    str5 = str26;
                    list = list2;
                    num3 = num9;
                    num4 = num8;
                    str6 = str25;
                    str7 = str24;
                    str8 = str23;
                    str = str22;
                    num5 = num;
                    str22 = str;
                    str23 = str8;
                    str24 = str7;
                    str25 = str6;
                    num8 = num4;
                    num9 = num3;
                    list2 = list;
                    str26 = str5;
                    l2 = l;
                    str27 = str4;
                    str28 = str3;
                    str29 = str2;
                    num10 = num2;
                    z2 = z;
                    str30 = str10;
                    str21 = str9;
                    break;
                case 26:
                    str11 = str16;
                    str13 = (String) acmVarP.i(dfxVar, 26, dnh.b, str13);
                    i2 = 67108864;
                    i3 = i4 | i2;
                    str9 = str21;
                    str10 = str30;
                    str16 = str11;
                    num = num5;
                    z = z2;
                    num2 = num10;
                    str2 = str29;
                    str3 = str28;
                    str4 = str27;
                    l = l2;
                    str5 = str26;
                    list = list2;
                    num3 = num9;
                    num4 = num8;
                    str6 = str25;
                    str7 = str24;
                    str8 = str23;
                    str = str22;
                    num5 = num;
                    str22 = str;
                    str23 = str8;
                    str24 = str7;
                    str25 = str6;
                    num8 = num4;
                    num9 = num3;
                    list2 = list;
                    str26 = str5;
                    l2 = l;
                    str27 = str4;
                    str28 = str3;
                    str29 = str2;
                    num10 = num2;
                    z2 = z;
                    str30 = str10;
                    str21 = str9;
                    break;
                case 27:
                    str11 = str16;
                    dxtVar2 = (dxt) acmVarP.i(dfxVar, 27, dxr.b, dxtVar2);
                    i2 = 134217728;
                    i3 = i4 | i2;
                    str9 = str21;
                    str10 = str30;
                    str16 = str11;
                    num = num5;
                    z = z2;
                    num2 = num10;
                    str2 = str29;
                    str3 = str28;
                    str4 = str27;
                    l = l2;
                    str5 = str26;
                    list = list2;
                    num3 = num9;
                    num4 = num8;
                    str6 = str25;
                    str7 = str24;
                    str8 = str23;
                    str = str22;
                    num5 = num;
                    str22 = str;
                    str23 = str8;
                    str24 = str7;
                    str25 = str6;
                    num8 = num4;
                    num9 = num3;
                    list2 = list;
                    str26 = str5;
                    l2 = l;
                    str27 = str4;
                    str28 = str3;
                    str29 = str2;
                    num10 = num2;
                    z2 = z;
                    str30 = str10;
                    str21 = str9;
                    break;
                default:
                    throw new bsd(iF);
            }
        }
        String str48 = str13;
        String str49 = str16;
        String str50 = str21;
        String str51 = str22;
        String str52 = str23;
        Integer num14 = num5;
        acmVarP._bp(dfxVar);
        String str53 = str28;
        String str54 = str20;
        return new dtb(i3, str50, str51, str52, str24, str25, num8, num9, list2, str26, l2, str27, str53, str29, num10, str30, str49, str17, str18, num6, str19, num7, str54, str12, str14, str15, num14, str48, dxtVar2);
    }

    @Override // me.hd.wauxv.obf.btd
    public final void c(avt avtVar, Object obj) {
        dtb dtbVar = (dtb) obj;
        dfx dfxVar = descriptor;
        acn acnVarO = avtVar.o(dfxVar);
        btt[] bttVarArr = dtb.a;
        dnh dnhVar = dnh.b;
        acnVarO.m(dfxVar, 0, dnhVar, dtbVar.b);
        acnVarO.m(dfxVar, 1, dnhVar, dtbVar.c);
        acnVarO.m(dfxVar, 2, dnhVar, dtbVar.d);
        acnVarO.m(dfxVar, 3, dnhVar, dtbVar.e);
        acnVarO.m(dfxVar, 4, dnhVar, dtbVar.f);
        bqj bqjVar = bqj.b;
        acnVarO.m(dfxVar, 5, bqjVar, dtbVar.g);
        acnVarO.m(dfxVar, 6, bqjVar, dtbVar.h);
        acnVarO.m(dfxVar, 7, (btd) bttVarArr[7].getValue(), dtbVar.i);
        acnVarO.m(dfxVar, 8, dnhVar, dtbVar.j);
        acnVarO.m(dfxVar, 9, bya.b, dtbVar.k);
        acnVarO.m(dfxVar, 10, dnhVar, dtbVar.l);
        acnVarO.m(dfxVar, 11, dnhVar, dtbVar.m);
        acnVarO.m(dfxVar, 12, dnhVar, dtbVar.n);
        acnVarO.m(dfxVar, 13, bqjVar, dtbVar.o);
        acnVarO.m(dfxVar, 14, dnhVar, dtbVar.p);
        acnVarO.m(dfxVar, 15, dnhVar, dtbVar.q);
        acnVarO.m(dfxVar, 16, dnhVar, dtbVar.r);
        acnVarO.m(dfxVar, 17, dnhVar, dtbVar.s);
        acnVarO.m(dfxVar, 18, bqjVar, dtbVar.t);
        acnVarO.m(dfxVar, 19, dnhVar, dtbVar.u);
        acnVarO.m(dfxVar, 20, bqjVar, dtbVar.v);
        acnVarO.m(dfxVar, 21, dnhVar, dtbVar.w);
        acnVarO.m(dfxVar, 22, dnhVar, dtbVar.x);
        acnVarO.m(dfxVar, 23, dnhVar, dtbVar.y);
        acnVarO.m(dfxVar, 24, dnhVar, dtbVar.z);
        acnVarO.m(dfxVar, 25, bqjVar, dtbVar.aa);
        acnVarO.m(dfxVar, 26, dnhVar, dtbVar.ab);
        acnVarO.m(dfxVar, 27, dxr.b, dtbVar.ac);
        acnVarO.a(dfxVar);
    }

    @Override // me.hd.wauxv.obf.bgx
    public final btd[] d() {
        btt[] bttVarArr = dtb.a;
        dnh dnhVar = dnh.b;
        btd btdVarT = aye.t(dnhVar);
        btd btdVarT2 = aye.t(dnhVar);
        btd btdVarT3 = aye.t(dnhVar);
        btd btdVarT4 = aye.t(dnhVar);
        btd btdVarT5 = aye.t(dnhVar);
        bqj bqjVar = bqj.b;
        return new btd[]{btdVarT, btdVarT2, btdVarT3, btdVarT4, btdVarT5, aye.t(bqjVar), aye.t(bqjVar), aye.t((btd) bttVarArr[7].getValue()), aye.t(dnhVar), aye.t(bya.b), aye.t(dnhVar), aye.t(dnhVar), aye.t(dnhVar), aye.t(bqjVar), aye.t(dnhVar), aye.t(dnhVar), aye.t(dnhVar), aye.t(dnhVar), aye.t(bqjVar), aye.t(dnhVar), aye.t(bqjVar), aye.t(dnhVar), aye.t(dnhVar), aye.t(dnhVar), aye.t(dnhVar), aye.t(bqjVar), aye.t(dnhVar), aye.t(dxr.b)};
    }

    @Override // me.hd.wauxv.obf.btd
    public final dfx getDescriptor() {
        return descriptor;
    }
}
