package me.hd.wauxv.obf;

import java.util.List;
import net.bytebuddy.jar.asm.Opcodes;
import okhttp3.internal.http2.Http2Connection;

/* JADX INFO: compiled from: r8-map-id-b9de5da7d0413052737328a4e696e1bcc3145db8f6a41e1e318485e124198cd6 */
/* JADX INFO: loaded from: classes.dex */
public final /* synthetic */ class ear implements bgx {
    public static final ear b;
    private static final dfx descriptor;

    static {
        ear earVar = new ear();
        b = earVar;
        cuc cucVar = new cuc(cnb.z(-212751205006122L), earVar, 73);
        bjs.y(-218459216542506L, cucVar, false, 1);
        bjs.y(-218411971902250L, cucVar, false, 2);
        bjs.y(-218386202098474L, cucVar, false, 3);
        bjs.y(-218304597719850L, cucVar, false, 4);
        bjs.y(-218278827916074L, cucVar, false, 5);
        bjs.y(-218802813926186L, cucVar, false, 6);
        bjs.y(-218768454187818L, cucVar, false, 7);
        bjs.y(-218734094449450L, cucVar, false, 9);
        bjs.y(-218695439743786L, cucVar, false, 10);
        bjs.y(-218579475626794L, cucVar, false, 11);
        bjs.y(-217956705368874L, cucVar, false, 12);
        bjs.y(-217810676480810L, cucVar, false, 13);
        bjs.y(-217793496611626L, cucVar, false, 14);
        bjs.y(-217772021775146L, cucVar, false, 15);
        bjs.y(-218167158766378L, cucVar, false, 16);
        bjs.y(-218141388962602L, cucVar, false, 17);
        bjs.y(-218051194649386L, cucVar, false, 18);
        bjs.y(-218003950009130L, cucVar, false, 19);
        bjs.y(-219563023137578L, cucVar, false, 20);
        bjs.y(-219558728170282L, cucVar, false, 21);
        bjs.y(-219459943922474L, cucVar, false, 22);
        bjs.y(-219416994249514L, cucVar, false, 23);
        bjs.y(-219885145684778L, cucVar, false, 24);
        bjs.y(-219807836273450L, cucVar, false, 25);
        bjs.y(-219743411764010L, cucVar, false, 26);
        bjs.y(-219674692287274L, cucVar, false, 27);
        bjs.y(-219657512418090L, cucVar, false, 28);
        bjs.y(-218983202552618L, cucVar, false, 29);
        bjs.y(-218974612618026L, cucVar, false, 30);
        bjs.y(-218875828370218L, cucVar, false, 31);
        bjs.y(-218867238435626L, cucVar, false, 32);
        bjs.y(-219339684838186L, cucVar, false, 33);
        bjs.y(-219223720721194L, cucVar, false, 34);
        bjs.y(-219159296211754L, cucVar, false, 35);
        bjs.y(-219103461636906L, cucVar, false, 36);
        bjs.y(-216281668123434L, cucVar, false, 37);
        bjs.y(-216169998973738L, cucVar, false, 38);
        bjs.y(-216144229169962L, cucVar, false, 39);
        bjs.y(-216560840997674L, cucVar, false, 40);
        bjs.y(-216453466815274L, cucVar, false, 41);
        bjs.y(-216431991978794L, cucVar, false, 42);
        bjs.y(-216341797665578L, cucVar, false, 43);
        bjs.y(-215719027407658L, cucVar, false, 46);
        bjs.y(-215688962636586L, cucVar, false, 47);
        bjs.y(-215671782767402L, cucVar, false, 48);
        bjs.y(-215590178388778L, cucVar, false, 49);
        bjs.y(-216002495249194L, cucVar, false, 50);
        bjs.y(-215942365707050L, cucVar, false, 51);
        bjs.y(-215916595903274L, cucVar, false, 52);
        bjs.y(-215830696557354L, cucVar, false, 53);
        bjs.y(-217419834456874L, cucVar, false, 54);
        bjs.y(-217351114980138L, cucVar, false, 55);
        bjs.y(-217290985437994L, cucVar, false, 56);
        bjs.y(-217222265961258L, cucVar, false, 59);
        bjs.y(-217690417396522L, cucVar, false, 60);
        bjs.y(-217574453279530L, cucVar, false, 61);
        bjs.y(-217510028770090L, cucVar, false, 62);
        bjs.y(-217458489162538L, cucVar, false, 63);
        bjs.y(-216732639689514L, cucVar, false, 64);
        bjs.y(-216659625245482L, cucVar, false, 65);
        bjs.y(-217153546484522L, cucVar, false, 66);
        bjs.y(-217033287400234L, cucVar, false, 67);
        bjs.y(-216977452825386L, cucVar, false, 68);
        bjs.y(-240427974261546L, cucVar, false, 69);
        bjs.y(-240307715177258L, cucVar, false, 70);
        bjs.y(-240629837724458L, cucVar, false, 71);
        bjs.y(-240604067920682L, cucVar, false, 72);
        bjs.y(-239942642957098L, cucVar, false, 73);
        bjs.y(-239891103349546L, cucVar, false, 74);
        bjs.y(-239770844265258L, cucVar, false, 75);
        bjs.y(-240217520864042L, cucVar, false, 77);
        bjs.y(-240123031583530L, cucVar, false, 78);
        bjs.y(-240071491975978L, cucVar, false, 79);
        descriptor = cucVar;
    }

    @Override // me.hd.wauxv.obf.btd
    public final Object a(ajt ajtVar) {
        eik eikVar;
        int i;
        Integer num;
        ebx ebxVar;
        ebx ebxVar2;
        ebx ebxVar3;
        Long l;
        Long l2;
        int i2;
        Long l3;
        ebx ebxVar4;
        Long l4;
        int i3;
        Long l5;
        int i4;
        Long l6;
        dfx dfxVar = descriptor;
        acm acmVarP = ajtVar.p(dfxVar);
        btt[] bttVarArr = eat.a;
        acmVarP.getClass();
        Long l7 = null;
        ebx ebxVar5 = null;
        eik eikVar2 = null;
        Long l8 = null;
        Long l9 = null;
        Long l10 = null;
        Long l11 = null;
        Long l12 = null;
        dwp dwpVar = null;
        String str = null;
        edq edqVar = null;
        ebr ebrVar = null;
        Long l13 = null;
        Long l14 = null;
        Integer num2 = null;
        Integer num3 = null;
        String str2 = null;
        Integer num4 = null;
        Integer num5 = null;
        Integer num6 = null;
        ejo ejoVar = null;
        ecs ecsVar = null;
        Integer num7 = null;
        Long l15 = null;
        Integer num8 = null;
        Integer num9 = null;
        Long l16 = null;
        dzp dzpVar = null;
        Integer num10 = null;
        Integer num11 = null;
        String str3 = null;
        Long l17 = null;
        Long l18 = null;
        Integer num12 = null;
        String str4 = null;
        dzg dzgVar = null;
        Integer num13 = null;
        ego egoVar = null;
        Integer num14 = null;
        egu eguVar = null;
        dxz dxzVar = null;
        String str5 = null;
        dwv dwvVar = null;
        Integer num15 = null;
        Long l19 = null;
        List list = null;
        Integer num16 = null;
        Integer num17 = null;
        Integer num18 = null;
        Integer num19 = null;
        Integer num20 = null;
        Integer num21 = null;
        eeo eeoVar = null;
        List list2 = null;
        Integer num22 = null;
        dzd dzdVar = null;
        ebc ebcVar = null;
        ean eanVar = null;
        String str6 = null;
        efw efwVar = null;
        dyc dycVar = null;
        String str7 = null;
        dzs dzsVar = null;
        Long l20 = null;
        List list3 = null;
        Integer num23 = null;
        dvr dvrVar = null;
        Integer num24 = null;
        dyf dyfVar = null;
        ecy ecyVar = null;
        Long l21 = null;
        dzm dzmVar = null;
        eib eibVar = null;
        int i5 = 0;
        boolean z = true;
        int i6 = 0;
        int i7 = 0;
        while (z) {
            ebr ebrVar2 = ebrVar;
            int iF = acmVarP.f(dfxVar);
            switch (iF) {
                case -1:
                    Long l22 = l13;
                    int i8 = i6;
                    int i9 = i7;
                    eikVar = eikVar2;
                    i = i8;
                    ebrVar = ebrVar2;
                    z = false;
                    num = num2;
                    ebxVar5 = ebxVar5;
                    l14 = l14;
                    l8 = l8;
                    i7 = i9;
                    l13 = l22;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 0:
                    ebxVar = ebxVar5;
                    Long l23 = l13;
                    int i10 = i6;
                    eikVar = eikVar2;
                    i7 |= 1;
                    l8 = l8;
                    i = i10;
                    ebrVar = ebrVar2;
                    num = num2;
                    l13 = l23;
                    l14 = (Long) acmVarP.i(dfxVar, 0, bya.b, l14);
                    ebxVar5 = ebxVar;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 1:
                    ebxVar2 = ebxVar5;
                    Long l24 = l13;
                    int i11 = i6;
                    eikVar = eikVar2;
                    int i12 = i7 | 2;
                    i = i11;
                    ebrVar = ebrVar2;
                    num3 = num3;
                    l8 = l8;
                    l13 = l24;
                    num = (Integer) acmVarP.i(dfxVar, 1, bqj.b, num2);
                    i7 = i12;
                    ebxVar5 = ebxVar2;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 2:
                    ebxVar3 = ebxVar5;
                    l = l13;
                    int i13 = i6;
                    int i14 = i7;
                    eikVar = eikVar2;
                    l2 = l8;
                    i2 = i14 | 4;
                    i = i13;
                    ebrVar = ebrVar2;
                    num3 = (Integer) acmVarP.i(dfxVar, 2, bqj.b, num3);
                    num = num2;
                    l8 = l2;
                    l13 = l;
                    ebxVar5 = ebxVar3;
                    i7 = i2;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 3:
                    ebxVar3 = ebxVar5;
                    l = l13;
                    int i15 = i6;
                    int i16 = i7;
                    eikVar = eikVar2;
                    l2 = l8;
                    i2 = i16 | 8;
                    i = i15;
                    ebrVar = ebrVar2;
                    str2 = (String) acmVarP.i(dfxVar, 3, dnh.b, str2);
                    num = num2;
                    l8 = l2;
                    l13 = l;
                    ebxVar5 = ebxVar3;
                    i7 = i2;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 4:
                    ebxVar3 = ebxVar5;
                    l = l13;
                    int i17 = i6;
                    int i18 = i7;
                    eikVar = eikVar2;
                    l2 = l8;
                    i2 = i18 | 16;
                    i = i17;
                    ebrVar = ebrVar2;
                    num4 = (Integer) acmVarP.i(dfxVar, 4, bqj.b, num4);
                    num = num2;
                    l8 = l2;
                    l13 = l;
                    ebxVar5 = ebxVar3;
                    i7 = i2;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 5:
                    ebxVar3 = ebxVar5;
                    l = l13;
                    int i19 = i6;
                    int i20 = i7;
                    eikVar = eikVar2;
                    l2 = l8;
                    i2 = i20 | 32;
                    i = i19;
                    ebrVar = ebrVar2;
                    num5 = (Integer) acmVarP.i(dfxVar, 5, bqj.b, num5);
                    num = num2;
                    l8 = l2;
                    l13 = l;
                    ebxVar5 = ebxVar3;
                    i7 = i2;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 6:
                    ebxVar3 = ebxVar5;
                    l = l13;
                    int i21 = i6;
                    int i22 = i7;
                    eikVar = eikVar2;
                    l2 = l8;
                    i2 = i22 | 64;
                    i = i21;
                    ebrVar = ebrVar2;
                    num6 = (Integer) acmVarP.i(dfxVar, 6, bqj.b, num6);
                    num = num2;
                    l8 = l2;
                    l13 = l;
                    ebxVar5 = ebxVar3;
                    i7 = i2;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 7:
                    ebxVar3 = ebxVar5;
                    l = l13;
                    int i23 = i6;
                    int i24 = i7;
                    eikVar = eikVar2;
                    l2 = l8;
                    i2 = i24 | 128;
                    i = i23;
                    ebrVar = ebrVar2;
                    ejoVar = (ejo) acmVarP.i(dfxVar, 7, ejm.b, ejoVar);
                    num = num2;
                    l8 = l2;
                    l13 = l;
                    ebxVar5 = ebxVar3;
                    i7 = i2;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 8:
                    ebxVar3 = ebxVar5;
                    l = l13;
                    int i25 = i6;
                    int i26 = i7;
                    eikVar = eikVar2;
                    l2 = l8;
                    i2 = i26 | 256;
                    i = i25;
                    ebrVar = ebrVar2;
                    ecsVar = (ecs) acmVarP.i(dfxVar, 8, ecq.b, ecsVar);
                    num = num2;
                    l8 = l2;
                    l13 = l;
                    ebxVar5 = ebxVar3;
                    i7 = i2;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 9:
                    ebxVar3 = ebxVar5;
                    l = l13;
                    int i27 = i6;
                    int i28 = i7;
                    eikVar = eikVar2;
                    l2 = l8;
                    i2 = i28 | 512;
                    i = i27;
                    ebrVar = ebrVar2;
                    num7 = (Integer) acmVarP.i(dfxVar, 9, bqj.b, num7);
                    num = num2;
                    l8 = l2;
                    l13 = l;
                    ebxVar5 = ebxVar3;
                    i7 = i2;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 10:
                    ebxVar3 = ebxVar5;
                    l = l13;
                    int i29 = i6;
                    int i30 = i7;
                    eikVar = eikVar2;
                    l2 = l8;
                    i2 = i30 | 1024;
                    i = i29;
                    ebrVar = ebrVar2;
                    l15 = (Long) acmVarP.i(dfxVar, 10, bya.b, l15);
                    num = num2;
                    l8 = l2;
                    l13 = l;
                    ebxVar5 = ebxVar3;
                    i7 = i2;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 11:
                    ebxVar3 = ebxVar5;
                    l = l13;
                    int i31 = i6;
                    int i32 = i7;
                    eikVar = eikVar2;
                    l2 = l8;
                    i2 = i32 | 2048;
                    i = i31;
                    ebrVar = ebrVar2;
                    num8 = (Integer) acmVarP.i(dfxVar, 11, bqj.b, num8);
                    num = num2;
                    l8 = l2;
                    l13 = l;
                    ebxVar5 = ebxVar3;
                    i7 = i2;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 12:
                    ebxVar3 = ebxVar5;
                    l = l13;
                    int i33 = i6;
                    int i34 = i7;
                    eikVar = eikVar2;
                    l2 = l8;
                    i2 = i34 | 4096;
                    i = i33;
                    ebrVar = ebrVar2;
                    num9 = (Integer) acmVarP.i(dfxVar, 12, bqj.b, num9);
                    num = num2;
                    l8 = l2;
                    l13 = l;
                    ebxVar5 = ebxVar3;
                    i7 = i2;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 13:
                    ebxVar3 = ebxVar5;
                    l = l13;
                    int i35 = i6;
                    int i36 = i7;
                    eikVar = eikVar2;
                    l2 = l8;
                    i2 = i36 | 8192;
                    i = i35;
                    ebrVar = ebrVar2;
                    l16 = (Long) acmVarP.i(dfxVar, 13, bya.b, l16);
                    num = num2;
                    l8 = l2;
                    l13 = l;
                    ebxVar5 = ebxVar3;
                    i7 = i2;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 14:
                    ebxVar3 = ebxVar5;
                    l = l13;
                    int i37 = i6;
                    int i38 = i7;
                    eikVar = eikVar2;
                    l2 = l8;
                    i2 = i38 | 16384;
                    i = i37;
                    ebrVar = ebrVar2;
                    dzpVar = (dzp) acmVarP.i(dfxVar, 14, dzn.b, dzpVar);
                    num = num2;
                    l8 = l2;
                    l13 = l;
                    ebxVar5 = ebxVar3;
                    i7 = i2;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 15:
                    ebxVar3 = ebxVar5;
                    l = l13;
                    int i39 = i6;
                    int i40 = i7;
                    eikVar = eikVar2;
                    l2 = l8;
                    i2 = i40 | 32768;
                    i = i39;
                    ebrVar = ebrVar2;
                    num10 = (Integer) acmVarP.i(dfxVar, 15, bqj.b, num10);
                    num = num2;
                    l8 = l2;
                    l13 = l;
                    ebxVar5 = ebxVar3;
                    i7 = i2;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 16:
                    ebxVar3 = ebxVar5;
                    l = l13;
                    int i41 = i6;
                    int i42 = i7;
                    eikVar = eikVar2;
                    l2 = l8;
                    i2 = i42 | 65536;
                    i = i41;
                    ebrVar = ebrVar2;
                    num11 = (Integer) acmVarP.i(dfxVar, 16, bqj.b, num11);
                    num = num2;
                    l8 = l2;
                    l13 = l;
                    ebxVar5 = ebxVar3;
                    i7 = i2;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 17:
                    ebxVar3 = ebxVar5;
                    l = l13;
                    int i43 = i6;
                    int i44 = i7;
                    eikVar = eikVar2;
                    l2 = l8;
                    i2 = i44 | 131072;
                    i = i43;
                    ebrVar = ebrVar2;
                    str3 = (String) acmVarP.i(dfxVar, 17, dnh.b, str3);
                    num = num2;
                    l8 = l2;
                    l13 = l;
                    ebxVar5 = ebxVar3;
                    i7 = i2;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 18:
                    ebxVar3 = ebxVar5;
                    l = l13;
                    int i45 = i6;
                    int i46 = i7;
                    eikVar = eikVar2;
                    l2 = l8;
                    i2 = i46 | 262144;
                    i = i45;
                    ebrVar = ebrVar2;
                    l17 = (Long) acmVarP.i(dfxVar, 18, bya.b, l17);
                    num = num2;
                    l8 = l2;
                    l13 = l;
                    ebxVar5 = ebxVar3;
                    i7 = i2;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 19:
                    ebxVar3 = ebxVar5;
                    l = l13;
                    int i47 = i6;
                    int i48 = i7;
                    eikVar = eikVar2;
                    l2 = l8;
                    Long l25 = (Long) acmVarP.i(dfxVar, 19, bya.b, l18);
                    i2 = i48 | Opcodes.ASM8;
                    i = i47;
                    ebrVar = ebrVar2;
                    l18 = l25;
                    num = num2;
                    l8 = l2;
                    l13 = l;
                    ebxVar5 = ebxVar3;
                    i7 = i2;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 20:
                    ebxVar3 = ebxVar5;
                    l = l13;
                    int i49 = i6;
                    int i50 = i7;
                    eikVar = eikVar2;
                    l2 = l8;
                    i2 = i50 | 1048576;
                    i = i49;
                    ebrVar = ebrVar2;
                    num12 = (Integer) acmVarP.i(dfxVar, 20, bqj.b, num12);
                    num = num2;
                    l8 = l2;
                    l13 = l;
                    ebxVar5 = ebxVar3;
                    i7 = i2;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 21:
                    ebxVar3 = ebxVar5;
                    l = l13;
                    int i51 = i6;
                    int i52 = i7;
                    eikVar = eikVar2;
                    l2 = l8;
                    i2 = i52 | 2097152;
                    i = i51;
                    ebrVar = ebrVar2;
                    str4 = (String) acmVarP.i(dfxVar, 21, dnh.b, str4);
                    num = num2;
                    l8 = l2;
                    l13 = l;
                    ebxVar5 = ebxVar3;
                    i7 = i2;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 22:
                    ebxVar3 = ebxVar5;
                    l = l13;
                    int i53 = i6;
                    int i54 = i7;
                    eikVar = eikVar2;
                    l2 = l8;
                    i2 = i54 | 4194304;
                    i = i53;
                    ebrVar = ebrVar2;
                    dzgVar = (dzg) acmVarP.i(dfxVar, 22, dze.b, dzgVar);
                    num = num2;
                    l8 = l2;
                    l13 = l;
                    ebxVar5 = ebxVar3;
                    i7 = i2;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 23:
                    ebxVar3 = ebxVar5;
                    l = l13;
                    int i55 = i6;
                    int i56 = i7;
                    eikVar = eikVar2;
                    l2 = l8;
                    i2 = i56 | 8388608;
                    i = i55;
                    ebrVar = ebrVar2;
                    num13 = (Integer) acmVarP.i(dfxVar, 23, bqj.b, num13);
                    num = num2;
                    l8 = l2;
                    l13 = l;
                    ebxVar5 = ebxVar3;
                    i7 = i2;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 24:
                    ebxVar3 = ebxVar5;
                    l = l13;
                    int i57 = i6;
                    int i58 = i7;
                    eikVar = eikVar2;
                    l2 = l8;
                    ego egoVar2 = (ego) acmVarP.i(dfxVar, 24, egm.b, egoVar);
                    i2 = i58 | Http2Connection.OKHTTP_CLIENT_WINDOW_SIZE;
                    i = i57;
                    ebrVar = ebrVar2;
                    egoVar = egoVar2;
                    num = num2;
                    l8 = l2;
                    l13 = l;
                    ebxVar5 = ebxVar3;
                    i7 = i2;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 25:
                    ebxVar3 = ebxVar5;
                    l = l13;
                    int i59 = i6;
                    int i60 = i7;
                    eikVar = eikVar2;
                    l2 = l8;
                    i2 = i60 | 33554432;
                    i = i59;
                    ebrVar = ebrVar2;
                    num14 = (Integer) acmVarP.i(dfxVar, 25, bqj.b, num14);
                    num = num2;
                    l8 = l2;
                    l13 = l;
                    ebxVar5 = ebxVar3;
                    i7 = i2;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 26:
                    ebxVar3 = ebxVar5;
                    l = l13;
                    int i61 = i6;
                    int i62 = i7;
                    eikVar = eikVar2;
                    l2 = l8;
                    i2 = i62 | 67108864;
                    i = i61;
                    ebrVar = ebrVar2;
                    eguVar = (egu) acmVarP.i(dfxVar, 26, egs.b, eguVar);
                    num = num2;
                    l8 = l2;
                    l13 = l;
                    ebxVar5 = ebxVar3;
                    i7 = i2;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 27:
                    ebxVar3 = ebxVar5;
                    l = l13;
                    int i63 = i6;
                    int i64 = i7;
                    eikVar = eikVar2;
                    l2 = l8;
                    i2 = i64 | 134217728;
                    i = i63;
                    ebrVar = ebrVar2;
                    dxzVar = (dxz) acmVarP.i(dfxVar, 27, dxx.b, dxzVar);
                    num = num2;
                    l8 = l2;
                    l13 = l;
                    ebxVar5 = ebxVar3;
                    i7 = i2;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 28:
                    ebxVar3 = ebxVar5;
                    l = l13;
                    int i65 = i6;
                    int i66 = i7;
                    eikVar = eikVar2;
                    l2 = l8;
                    i2 = i66 | 268435456;
                    i = i65;
                    ebrVar = ebrVar2;
                    str5 = (String) acmVarP.i(dfxVar, 28, dnh.b, str5);
                    num = num2;
                    l8 = l2;
                    l13 = l;
                    ebxVar5 = ebxVar3;
                    i7 = i2;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 29:
                    ebxVar3 = ebxVar5;
                    l = l13;
                    int i67 = i6;
                    int i68 = i7;
                    eikVar = eikVar2;
                    l2 = l8;
                    i2 = i68 | 536870912;
                    i = i67;
                    ebrVar = ebrVar2;
                    dwvVar = (dwv) acmVarP.i(dfxVar, 29, dwt.b, dwvVar);
                    num = num2;
                    l8 = l2;
                    l13 = l;
                    ebxVar5 = ebxVar3;
                    i7 = i2;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 30:
                    ebxVar3 = ebxVar5;
                    l = l13;
                    int i69 = i6;
                    int i70 = i7;
                    eikVar = eikVar2;
                    l2 = l8;
                    i2 = i70 | 1073741824;
                    i = i69;
                    ebrVar = ebrVar2;
                    num15 = (Integer) acmVarP.i(dfxVar, 30, bqj.b, num15);
                    num = num2;
                    l8 = l2;
                    l13 = l;
                    ebxVar5 = ebxVar3;
                    i7 = i2;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 31:
                    ebxVar2 = ebxVar5;
                    l3 = l13;
                    int i71 = i6;
                    eikVar = eikVar2;
                    i7 |= Integer.MIN_VALUE;
                    i = i71;
                    ebrVar = ebrVar2;
                    l19 = (Long) acmVarP.i(dfxVar, 31, bya.b, l19);
                    num = num2;
                    l13 = l3;
                    ebxVar5 = ebxVar2;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 32:
                    ebxVar4 = ebxVar5;
                    l4 = l13;
                    int i72 = i6;
                    eikVar = eikVar2;
                    i3 = i72 | 1;
                    list = (List) acmVarP.i(dfxVar, 32, (btd) bttVarArr[32].getValue(), list);
                    num = num2;
                    ebrVar = ebrVar2;
                    l13 = l4;
                    ebxVar5 = ebxVar4;
                    i = i3;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 33:
                    ebxVar4 = ebxVar5;
                    l4 = l13;
                    int i73 = i6;
                    eikVar = eikVar2;
                    i3 = i73 | 2;
                    num16 = (Integer) acmVarP.i(dfxVar, 33, bqj.b, num16);
                    num = num2;
                    ebrVar = ebrVar2;
                    l13 = l4;
                    ebxVar5 = ebxVar4;
                    i = i3;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 34:
                    ebxVar4 = ebxVar5;
                    l4 = l13;
                    int i74 = i6;
                    eikVar = eikVar2;
                    i3 = i74 | 4;
                    num17 = (Integer) acmVarP.i(dfxVar, 34, bqj.b, num17);
                    num = num2;
                    ebrVar = ebrVar2;
                    l13 = l4;
                    ebxVar5 = ebxVar4;
                    i = i3;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 35:
                    ebxVar4 = ebxVar5;
                    l4 = l13;
                    int i75 = i6;
                    eikVar = eikVar2;
                    i3 = i75 | 8;
                    num18 = (Integer) acmVarP.i(dfxVar, 35, bqj.b, num18);
                    num = num2;
                    ebrVar = ebrVar2;
                    l13 = l4;
                    ebxVar5 = ebxVar4;
                    i = i3;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 36:
                    ebxVar4 = ebxVar5;
                    l4 = l13;
                    int i76 = i6;
                    eikVar = eikVar2;
                    i3 = i76 | 16;
                    num19 = (Integer) acmVarP.i(dfxVar, 36, bqj.b, num19);
                    num = num2;
                    ebrVar = ebrVar2;
                    l13 = l4;
                    ebxVar5 = ebxVar4;
                    i = i3;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 37:
                    ebxVar4 = ebxVar5;
                    l4 = l13;
                    int i77 = i6;
                    eikVar = eikVar2;
                    i3 = i77 | 32;
                    num20 = (Integer) acmVarP.i(dfxVar, 37, bqj.b, num20);
                    num = num2;
                    ebrVar = ebrVar2;
                    l13 = l4;
                    ebxVar5 = ebxVar4;
                    i = i3;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 38:
                    ebxVar4 = ebxVar5;
                    l4 = l13;
                    int i78 = i6;
                    eikVar = eikVar2;
                    i3 = i78 | 64;
                    num21 = (Integer) acmVarP.i(dfxVar, 38, bqj.b, num21);
                    num = num2;
                    ebrVar = ebrVar2;
                    l13 = l4;
                    ebxVar5 = ebxVar4;
                    i = i3;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 39:
                    ebxVar4 = ebxVar5;
                    l4 = l13;
                    int i79 = i6;
                    eikVar = eikVar2;
                    i3 = i79 | 128;
                    eeoVar = (eeo) acmVarP.i(dfxVar, 39, eem.b, eeoVar);
                    num = num2;
                    ebrVar = ebrVar2;
                    l13 = l4;
                    ebxVar5 = ebxVar4;
                    i = i3;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 40:
                    ebxVar4 = ebxVar5;
                    l4 = l13;
                    int i80 = i6;
                    eikVar = eikVar2;
                    i3 = i80 | 256;
                    list2 = (List) acmVarP.i(dfxVar, 40, (btd) bttVarArr[40].getValue(), list2);
                    num = num2;
                    ebrVar = ebrVar2;
                    l13 = l4;
                    ebxVar5 = ebxVar4;
                    i = i3;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 41:
                    ebxVar4 = ebxVar5;
                    l4 = l13;
                    int i81 = i6;
                    eikVar = eikVar2;
                    i3 = i81 | 512;
                    num22 = (Integer) acmVarP.i(dfxVar, 41, bqj.b, num22);
                    num = num2;
                    ebrVar = ebrVar2;
                    l13 = l4;
                    ebxVar5 = ebxVar4;
                    i = i3;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 42:
                    ebxVar4 = ebxVar5;
                    l4 = l13;
                    int i82 = i6;
                    eikVar = eikVar2;
                    i3 = i82 | 1024;
                    dzdVar = (dzd) acmVarP.i(dfxVar, 42, dzb.b, dzdVar);
                    num = num2;
                    ebrVar = ebrVar2;
                    l13 = l4;
                    ebxVar5 = ebxVar4;
                    i = i3;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 43:
                    ebxVar4 = ebxVar5;
                    l4 = l13;
                    int i83 = i6;
                    eikVar = eikVar2;
                    i3 = i83 | 2048;
                    ebcVar = (ebc) acmVarP.i(dfxVar, 43, eba.b, ebcVar);
                    num = num2;
                    ebrVar = ebrVar2;
                    l13 = l4;
                    ebxVar5 = ebxVar4;
                    i = i3;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 44:
                    ebxVar4 = ebxVar5;
                    l4 = l13;
                    int i84 = i6;
                    eikVar = eikVar2;
                    i3 = i84 | 4096;
                    eanVar = (ean) acmVarP.i(dfxVar, 44, eal.b, eanVar);
                    num = num2;
                    ebrVar = ebrVar2;
                    l13 = l4;
                    ebxVar5 = ebxVar4;
                    i = i3;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 45:
                    ebxVar4 = ebxVar5;
                    l4 = l13;
                    int i85 = i6;
                    eikVar = eikVar2;
                    i3 = i85 | 8192;
                    str6 = (String) acmVarP.i(dfxVar, 45, dnh.b, str6);
                    num = num2;
                    ebrVar = ebrVar2;
                    l13 = l4;
                    ebxVar5 = ebxVar4;
                    i = i3;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 46:
                    ebxVar2 = ebxVar5;
                    l3 = l13;
                    i = i6 | 16384;
                    ebrVar = ebrVar2;
                    efwVar = (efw) acmVarP.i(dfxVar, 46, efu.b, efwVar);
                    eikVar = eikVar2;
                    num = num2;
                    l13 = l3;
                    ebxVar5 = ebxVar2;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 47:
                    ebxVar2 = ebxVar5;
                    l3 = l13;
                    i = i6 | 32768;
                    ebrVar = ebrVar2;
                    dycVar = (dyc) acmVarP.i(dfxVar, 47, dya.b, dycVar);
                    eikVar = eikVar2;
                    num = num2;
                    l13 = l3;
                    ebxVar5 = ebxVar2;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 48:
                    ebxVar2 = ebxVar5;
                    l3 = l13;
                    i = i6 | 65536;
                    ebrVar = ebrVar2;
                    str7 = (String) acmVarP.i(dfxVar, 48, dnh.b, str7);
                    eikVar = eikVar2;
                    num = num2;
                    l13 = l3;
                    ebxVar5 = ebxVar2;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 49:
                    ebxVar2 = ebxVar5;
                    l3 = l13;
                    i = i6 | 131072;
                    ebrVar = ebrVar2;
                    dzsVar = (dzs) acmVarP.i(dfxVar, 49, dzq.b, dzsVar);
                    eikVar = eikVar2;
                    num = num2;
                    l13 = l3;
                    ebxVar5 = ebxVar2;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 50:
                    ebxVar2 = ebxVar5;
                    l3 = l13;
                    i = i6 | 262144;
                    ebrVar = ebrVar2;
                    l20 = (Long) acmVarP.i(dfxVar, 50, bya.b, l20);
                    eikVar = eikVar2;
                    num = num2;
                    l13 = l3;
                    ebxVar5 = ebxVar2;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 51:
                    ebxVar2 = ebxVar5;
                    l3 = l13;
                    List list4 = (List) acmVarP.i(dfxVar, 51, (btd) bttVarArr[51].getValue(), list3);
                    i = i6 | Opcodes.ASM8;
                    ebrVar = ebrVar2;
                    list3 = list4;
                    eikVar = eikVar2;
                    num = num2;
                    l13 = l3;
                    ebxVar5 = ebxVar2;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 52:
                    ebxVar2 = ebxVar5;
                    l3 = l13;
                    i = i6 | 1048576;
                    ebrVar = ebrVar2;
                    num23 = (Integer) acmVarP.i(dfxVar, 52, bqj.b, num23);
                    eikVar = eikVar2;
                    num = num2;
                    l13 = l3;
                    ebxVar5 = ebxVar2;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 53:
                    ebxVar2 = ebxVar5;
                    l3 = l13;
                    i = i6 | 2097152;
                    ebrVar = ebrVar2;
                    dvrVar = (dvr) acmVarP.i(dfxVar, 53, dvp.b, dvrVar);
                    eikVar = eikVar2;
                    num = num2;
                    l13 = l3;
                    ebxVar5 = ebxVar2;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 54:
                    ebxVar2 = ebxVar5;
                    l3 = l13;
                    i = i6 | 4194304;
                    ebrVar = ebrVar2;
                    num24 = (Integer) acmVarP.i(dfxVar, 54, bqj.b, num24);
                    eikVar = eikVar2;
                    num = num2;
                    l13 = l3;
                    ebxVar5 = ebxVar2;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 55:
                    ebxVar2 = ebxVar5;
                    l3 = l13;
                    i = i6 | 8388608;
                    ebrVar = ebrVar2;
                    dyfVar = (dyf) acmVarP.i(dfxVar, 55, dyd.b, dyfVar);
                    eikVar = eikVar2;
                    num = num2;
                    l13 = l3;
                    ebxVar5 = ebxVar2;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 56:
                    ebxVar2 = ebxVar5;
                    l3 = l13;
                    ecy ecyVar2 = (ecy) acmVarP.i(dfxVar, 56, ecw.b, ecyVar);
                    i = i6 | Http2Connection.OKHTTP_CLIENT_WINDOW_SIZE;
                    ebrVar = ebrVar2;
                    ecyVar = ecyVar2;
                    eikVar = eikVar2;
                    num = num2;
                    l13 = l3;
                    ebxVar5 = ebxVar2;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 57:
                    ebxVar2 = ebxVar5;
                    l3 = l13;
                    i = i6 | 33554432;
                    ebrVar = ebrVar2;
                    l21 = (Long) acmVarP.i(dfxVar, 57, bya.b, l21);
                    eikVar = eikVar2;
                    num = num2;
                    l13 = l3;
                    ebxVar5 = ebxVar2;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 58:
                    ebxVar2 = ebxVar5;
                    l3 = l13;
                    i = i6 | 67108864;
                    ebrVar = ebrVar2;
                    dzmVar = (dzm) acmVarP.i(dfxVar, 58, dzk.b, dzmVar);
                    eikVar = eikVar2;
                    num = num2;
                    l13 = l3;
                    ebxVar5 = ebxVar2;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 59:
                    ebxVar2 = ebxVar5;
                    l3 = l13;
                    i = i6 | 134217728;
                    ebrVar = ebrVar2;
                    eibVar = (eib) acmVarP.i(dfxVar, 59, ehz.b, eibVar);
                    eikVar = eikVar2;
                    num = num2;
                    l13 = l3;
                    ebxVar5 = ebxVar2;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 60:
                    ebxVar = ebxVar5;
                    ebr ebrVar3 = (ebr) acmVarP.i(dfxVar, 60, ebp.b, ebrVar2);
                    int i86 = i6 | 268435456;
                    eikVar = eikVar2;
                    i = i86;
                    num = num2;
                    l13 = l13;
                    ebrVar = ebrVar3;
                    ebxVar5 = ebxVar;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 61:
                    ebxVar2 = ebxVar5;
                    i = i6 | 536870912;
                    ebrVar = ebrVar2;
                    l13 = (Long) acmVarP.i(dfxVar, 61, bya.b, l13);
                    eikVar = eikVar2;
                    num = num2;
                    ebxVar5 = ebxVar2;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 62:
                    l5 = l13;
                    l7 = (Long) acmVarP.i(dfxVar, 62, bya.b, l7);
                    i4 = i6 | 1073741824;
                    i = i4;
                    ebrVar = ebrVar2;
                    eikVar = eikVar2;
                    num = num2;
                    l13 = l5;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 63:
                    l5 = l13;
                    l9 = (Long) acmVarP.i(dfxVar, 63, bya.b, l9);
                    i4 = i6 | Integer.MIN_VALUE;
                    i = i4;
                    ebrVar = ebrVar2;
                    eikVar = eikVar2;
                    num = num2;
                    l13 = l5;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 64:
                    l6 = l13;
                    l10 = (Long) acmVarP.i(dfxVar, 64, bya.b, l10);
                    i5 |= 1;
                    num = num2;
                    ebrVar = ebrVar2;
                    l13 = l6;
                    i = i6;
                    eikVar = eikVar2;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 65:
                    l6 = l13;
                    l11 = (Long) acmVarP.i(dfxVar, 65, bya.b, l11);
                    i5 |= 2;
                    num = num2;
                    ebrVar = ebrVar2;
                    l13 = l6;
                    i = i6;
                    eikVar = eikVar2;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 66:
                    l6 = l13;
                    l12 = (Long) acmVarP.i(dfxVar, 66, bya.b, l12);
                    i5 |= 4;
                    num = num2;
                    ebrVar = ebrVar2;
                    l13 = l6;
                    i = i6;
                    eikVar = eikVar2;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 67:
                    l6 = l13;
                    l8 = (Long) acmVarP.i(dfxVar, 67, bya.b, l8);
                    i5 |= 8;
                    num = num2;
                    ebrVar = ebrVar2;
                    l13 = l6;
                    i = i6;
                    eikVar = eikVar2;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 68:
                    l6 = l13;
                    eikVar2 = (eik) acmVarP.i(dfxVar, 68, eii.b, eikVar2);
                    i5 |= 16;
                    num = num2;
                    ebrVar = ebrVar2;
                    l13 = l6;
                    i = i6;
                    eikVar = eikVar2;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 69:
                    l6 = l13;
                    ebxVar5 = (ebx) acmVarP.i(dfxVar, 69, ebv.b, ebxVar5);
                    i5 |= 32;
                    num = num2;
                    ebrVar = ebrVar2;
                    l13 = l6;
                    i = i6;
                    eikVar = eikVar2;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 70:
                    l6 = l13;
                    dwpVar = (dwp) acmVarP.i(dfxVar, 70, dwn.b, dwpVar);
                    i5 |= 64;
                    num = num2;
                    ebrVar = ebrVar2;
                    l13 = l6;
                    i = i6;
                    eikVar = eikVar2;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 71:
                    l6 = l13;
                    str = (String) acmVarP.i(dfxVar, 71, dnh.b, str);
                    i5 |= 128;
                    num = num2;
                    ebrVar = ebrVar2;
                    l13 = l6;
                    i = i6;
                    eikVar = eikVar2;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                case 72:
                    l6 = l13;
                    edqVar = (edq) acmVarP.i(dfxVar, 72, edo.b, edqVar);
                    i5 |= 256;
                    num = num2;
                    ebrVar = ebrVar2;
                    l13 = l6;
                    i = i6;
                    eikVar = eikVar2;
                    num2 = num;
                    eikVar2 = eikVar;
                    i6 = i;
                    break;
                default:
                    throw new bsd(iF);
            }
        }
        ebx ebxVar6 = ebxVar5;
        ebr ebrVar4 = ebrVar;
        Long l26 = l13;
        int i87 = i6;
        int i88 = i7;
        Long l27 = l8;
        Long l28 = l14;
        Integer num25 = num2;
        acmVarP._bp(dfxVar);
        return new eat(i88, i87, i5, l28, num25, num3, str2, num4, num5, num6, ejoVar, ecsVar, num7, l15, num8, num9, l16, dzpVar, num10, num11, str3, l17, l18, num12, str4, dzgVar, num13, egoVar, num14, eguVar, dxzVar, str5, dwvVar, num15, l19, list, num16, num17, num18, num19, num20, num21, eeoVar, list2, num22, dzdVar, ebcVar, eanVar, str6, efwVar, dycVar, str7, dzsVar, l20, list3, num23, dvrVar, num24, dyfVar, ecyVar, l21, dzmVar, eibVar, ebrVar4, l26, l7, l9, l10, l11, l12, l27, eikVar2, ebxVar6, dwpVar, str, edqVar);
    }

    @Override // me.hd.wauxv.obf.btd
    public final void c(avt avtVar, Object obj) {
        eat eatVar = (eat) obj;
        dfx dfxVar = descriptor;
        acn acnVarO = avtVar.o(dfxVar);
        btt[] bttVarArr = eat.a;
        bya byaVar = bya.b;
        acnVarO.m(dfxVar, 0, byaVar, eatVar.b);
        bqj bqjVar = bqj.b;
        acnVarO.m(dfxVar, 1, bqjVar, eatVar.c);
        acnVarO.m(dfxVar, 2, bqjVar, eatVar.d);
        dnh dnhVar = dnh.b;
        acnVarO.m(dfxVar, 3, dnhVar, eatVar.e);
        acnVarO.m(dfxVar, 4, bqjVar, eatVar.f);
        acnVarO.m(dfxVar, 5, bqjVar, eatVar.g);
        acnVarO.m(dfxVar, 6, bqjVar, eatVar.h);
        acnVarO.m(dfxVar, 7, ejm.b, eatVar.i);
        acnVarO.m(dfxVar, 8, ecq.b, eatVar.j);
        acnVarO.m(dfxVar, 9, bqjVar, eatVar.k);
        acnVarO.m(dfxVar, 10, byaVar, eatVar.l);
        acnVarO.m(dfxVar, 11, bqjVar, eatVar.m);
        acnVarO.m(dfxVar, 12, bqjVar, eatVar.n);
        acnVarO.m(dfxVar, 13, byaVar, eatVar.o);
        acnVarO.m(dfxVar, 14, dzn.b, eatVar.p);
        acnVarO.m(dfxVar, 15, bqjVar, eatVar.q);
        acnVarO.m(dfxVar, 16, bqjVar, eatVar.r);
        acnVarO.m(dfxVar, 17, dnhVar, eatVar.s);
        acnVarO.m(dfxVar, 18, byaVar, eatVar.t);
        acnVarO.m(dfxVar, 19, byaVar, eatVar.u);
        acnVarO.m(dfxVar, 20, bqjVar, eatVar.v);
        acnVarO.m(dfxVar, 21, dnhVar, eatVar.w);
        acnVarO.m(dfxVar, 22, dze.b, eatVar.x);
        acnVarO.m(dfxVar, 23, bqjVar, eatVar.y);
        acnVarO.m(dfxVar, 24, egm.b, eatVar.z);
        acnVarO.m(dfxVar, 25, bqjVar, eatVar.aa);
        acnVarO.m(dfxVar, 26, egs.b, eatVar.ab);
        acnVarO.m(dfxVar, 27, dxx.b, eatVar.ac);
        acnVarO.m(dfxVar, 28, dnhVar, eatVar.ad);
        acnVarO.m(dfxVar, 29, dwt.b, eatVar.ae);
        acnVarO.m(dfxVar, 30, bqjVar, eatVar.af);
        acnVarO.m(dfxVar, 31, byaVar, eatVar.ag);
        acnVarO.m(dfxVar, 32, (btd) bttVarArr[32].getValue(), eatVar.ah);
        acnVarO.m(dfxVar, 33, bqjVar, eatVar.ai);
        acnVarO.m(dfxVar, 34, bqjVar, eatVar.aj);
        acnVarO.m(dfxVar, 35, bqjVar, eatVar.ak);
        acnVarO.m(dfxVar, 36, bqjVar, eatVar.al);
        acnVarO.m(dfxVar, 37, bqjVar, eatVar.am);
        acnVarO.m(dfxVar, 38, bqjVar, eatVar.an);
        acnVarO.m(dfxVar, 39, eem.b, eatVar.ao);
        acnVarO.m(dfxVar, 40, (btd) bttVarArr[40].getValue(), eatVar.ap);
        acnVarO.m(dfxVar, 41, bqjVar, eatVar.aq);
        acnVarO.m(dfxVar, 42, dzb.b, eatVar.ar);
        acnVarO.m(dfxVar, 43, eba.b, eatVar.as);
        acnVarO.m(dfxVar, 44, eal.b, eatVar.at);
        acnVarO.m(dfxVar, 45, dnhVar, eatVar.au);
        acnVarO.m(dfxVar, 46, efu.b, eatVar.av);
        acnVarO.m(dfxVar, 47, dya.b, eatVar.aw);
        acnVarO.m(dfxVar, 48, dnhVar, eatVar.ax);
        acnVarO.m(dfxVar, 49, dzq.b, eatVar.ay);
        acnVarO.m(dfxVar, 50, byaVar, eatVar.az);
        acnVarO.m(dfxVar, 51, (btd) bttVarArr[51].getValue(), eatVar.ba);
        acnVarO.m(dfxVar, 52, bqjVar, eatVar.bb);
        acnVarO.m(dfxVar, 53, dvp.b, eatVar.bc);
        acnVarO.m(dfxVar, 54, bqjVar, eatVar.bd);
        acnVarO.m(dfxVar, 55, dyd.b, eatVar.be);
        acnVarO.m(dfxVar, 56, ecw.b, eatVar.bf);
        acnVarO.m(dfxVar, 57, byaVar, eatVar.bg);
        acnVarO.m(dfxVar, 58, dzk.b, eatVar.bh);
        acnVarO.m(dfxVar, 59, ehz.b, eatVar.bi);
        acnVarO.m(dfxVar, 60, ebp.b, eatVar.bj);
        acnVarO.m(dfxVar, 61, byaVar, eatVar.bk);
        acnVarO.m(dfxVar, 62, byaVar, eatVar.bl);
        acnVarO.m(dfxVar, 63, byaVar, eatVar.bm);
        acnVarO.m(dfxVar, 64, byaVar, eatVar.bn);
        acnVarO.m(dfxVar, 65, byaVar, eatVar.bo);
        acnVarO.m(dfxVar, 66, byaVar, eatVar.bp);
        acnVarO.m(dfxVar, 67, byaVar, eatVar.bq);
        acnVarO.m(dfxVar, 68, eii.b, eatVar.br);
        acnVarO.m(dfxVar, 69, ebv.b, eatVar.bs);
        acnVarO.m(dfxVar, 70, dwn.b, eatVar.bt);
        acnVarO.m(dfxVar, 71, dnhVar, eatVar.bu);
        acnVarO.m(dfxVar, 72, edo.b, eatVar.bv);
        acnVarO.a(dfxVar);
    }

    @Override // me.hd.wauxv.obf.bgx
    public final btd[] d() {
        btt[] bttVarArr = eat.a;
        bya byaVar = bya.b;
        btd btdVarT = aye.t(byaVar);
        bqj bqjVar = bqj.b;
        btd btdVarT2 = aye.t(bqjVar);
        btd btdVarT3 = aye.t(bqjVar);
        dnh dnhVar = dnh.b;
        return new btd[]{btdVarT, btdVarT2, btdVarT3, aye.t(dnhVar), aye.t(bqjVar), aye.t(bqjVar), aye.t(bqjVar), aye.t(ejm.b), aye.t(ecq.b), aye.t(bqjVar), aye.t(byaVar), aye.t(bqjVar), aye.t(bqjVar), aye.t(byaVar), aye.t(dzn.b), aye.t(bqjVar), aye.t(bqjVar), aye.t(dnhVar), aye.t(byaVar), aye.t(byaVar), aye.t(bqjVar), aye.t(dnhVar), aye.t(dze.b), aye.t(bqjVar), aye.t(egm.b), aye.t(bqjVar), aye.t(egs.b), aye.t(dxx.b), aye.t(dnhVar), aye.t(dwt.b), aye.t(bqjVar), aye.t(byaVar), aye.t((btd) bttVarArr[32].getValue()), aye.t(bqjVar), aye.t(bqjVar), aye.t(bqjVar), aye.t(bqjVar), aye.t(bqjVar), aye.t(bqjVar), aye.t(eem.b), aye.t((btd) bttVarArr[40].getValue()), aye.t(bqjVar), aye.t(dzb.b), aye.t(eba.b), aye.t(eal.b), aye.t(dnhVar), aye.t(efu.b), aye.t(dya.b), aye.t(dnhVar), aye.t(dzq.b), aye.t(byaVar), aye.t((btd) bttVarArr[51].getValue()), aye.t(bqjVar), aye.t(dvp.b), aye.t(bqjVar), aye.t(dyd.b), aye.t(ecw.b), aye.t(byaVar), aye.t(dzk.b), aye.t(ehz.b), aye.t(ebp.b), aye.t(byaVar), aye.t(byaVar), aye.t(byaVar), aye.t(byaVar), aye.t(byaVar), aye.t(byaVar), aye.t(byaVar), aye.t(eii.b), aye.t(ebv.b), aye.t(dwn.b), aye.t(dnhVar), aye.t(edo.b)};
    }

    @Override // me.hd.wauxv.obf.btd
    public final dfx getDescriptor() {
        return descriptor;
    }
}
