package me.hd.wauxv.obf;

import java.util.List;

/* JADX INFO: compiled from: r8-map-id-b9de5da7d0413052737328a4e696e1bcc3145db8f6a41e1e318485e124198cd6 */
/* JADX INFO: loaded from: classes.dex */
public final class eat {
    public static final eas Companion = new eas();
    public static final btt[] a;
    public final Integer aa;
    public final egu ab;
    public final dxz ac;
    public final String ad;
    public final dwv ae;
    public final Integer af;
    public final Long ag;
    public final List ah;
    public final Integer ai;
    public final Integer aj;
    public final Integer ak;
    public final Integer al;
    public final Integer am;
    public final Integer an;
    public final eeo ao;
    public final List ap;
    public final Integer aq;
    public final dzd ar;
    public final ebc as;
    public final ean at;
    public final String au;
    public final efw av;
    public final dyc aw;
    public final String ax;
    public final dzs ay;
    public final Long az;
    public final Long b;
    public final List ba;
    public final Integer bb;
    public final dvr bc;
    public final Integer bd;
    public final dyf be;
    public final ecy bf;
    public final Long bg;
    public final dzm bh;
    public final eib bi;
    public final ebr bj;
    public final Long bk;
    public final Long bl;
    public final Long bm;
    public final Long bn;
    public final Long bo;
    public final Long bp;
    public final Long bq;
    public final eik br;
    public final ebx bs;
    public final dwp bt;
    public final String bu;
    public final edq bv;
    public final Integer c;
    public final Integer d;
    public final String e;
    public final Integer f;
    public final Integer g;
    public final Integer h;
    public final ejo i;
    public final ecs j;
    public final Integer k;
    public final Long l;
    public final Integer m;
    public final Integer n;
    public final Long o;
    public final dzp p;
    public final Integer q;
    public final Integer r;
    public final String s;
    public final Long t;
    public final Long u;
    public final Integer v;
    public final String w;
    public final dzg x;
    public final Integer y;
    public final ego z;

    static {
        dtr dtrVar = new dtr(18);
        btx btxVar = btx.a;
        a = new btt[]{null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, ewz.am(btxVar, dtrVar), null, null, null, null, null, null, null, ewz.am(btxVar, new dtr(19)), null, null, null, null, null, null, null, null, null, null, ewz.am(btxVar, new dtr(20)), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null};
    }

    public /* synthetic */ eat(int i, int i2, int i3, Long l, Integer num, Integer num2, String str, Integer num3, Integer num4, Integer num5, ejo ejoVar, ecs ecsVar, Integer num6, Long l2, Integer num7, Integer num8, Long l3, dzp dzpVar, Integer num9, Integer num10, String str2, Long l4, Long l5, Integer num11, String str3, dzg dzgVar, Integer num12, ego egoVar, Integer num13, egu eguVar, dxz dxzVar, String str4, dwv dwvVar, Integer num14, Long l6, List list, Integer num15, Integer num16, Integer num17, Integer num18, Integer num19, Integer num20, eeo eeoVar, List list2, Integer num21, dzd dzdVar, ebc ebcVar, ean eanVar, String str5, efw efwVar, dyc dycVar, String str6, dzs dzsVar, Long l7, List list3, Integer num22, dvr dvrVar, Integer num23, dyf dyfVar, ecy ecyVar, Long l8, dzm dzmVar, eib eibVar, ebr ebrVar, Long l9, Long l10, Long l11, Long l12, Long l13, Long l14, Long l15, eik eikVar, ebx ebxVar, dwp dwpVar, String str7, edq edqVar) {
        if ((511 != (i3 & 511)) || ((-1 != i) | (-1 != i2))) {
            bht.ag(new int[]{i, i2, i3}, new int[]{-1, -1, 511}, ear.b.getDescriptor());
            throw null;
        }
        this.b = l;
        this.c = num;
        this.d = num2;
        this.e = str;
        this.f = num3;
        this.g = num4;
        this.h = num5;
        this.i = ejoVar;
        this.j = ecsVar;
        this.k = num6;
        this.l = l2;
        this.m = num7;
        this.n = num8;
        this.o = l3;
        this.p = dzpVar;
        this.q = num9;
        this.r = num10;
        this.s = str2;
        this.t = l4;
        this.u = l5;
        this.v = num11;
        this.w = str3;
        this.x = dzgVar;
        this.y = num12;
        this.z = egoVar;
        this.aa = num13;
        this.ab = eguVar;
        this.ac = dxzVar;
        this.ad = str4;
        this.ae = dwvVar;
        this.af = num14;
        this.ag = l6;
        this.ah = list;
        this.ai = num15;
        this.aj = num16;
        this.ak = num17;
        this.al = num18;
        this.am = num19;
        this.an = num20;
        this.ao = eeoVar;
        this.ap = list2;
        this.aq = num21;
        this.ar = dzdVar;
        this.as = ebcVar;
        this.at = eanVar;
        this.au = str5;
        this.av = efwVar;
        this.aw = dycVar;
        this.ax = str6;
        this.ay = dzsVar;
        this.az = l7;
        this.ba = list3;
        this.bb = num22;
        this.bc = dvrVar;
        this.bd = num23;
        this.be = dyfVar;
        this.bf = ecyVar;
        this.bg = l8;
        this.bh = dzmVar;
        this.bi = eibVar;
        this.bj = ebrVar;
        this.bk = l9;
        this.bl = l10;
        this.bm = l11;
        this.bn = l12;
        this.bo = l13;
        this.bp = l14;
        this.bq = l15;
        this.br = eikVar;
        this.bs = ebxVar;
        this.bt = dwpVar;
        this.bu = str7;
        this.bv = edqVar;
    }

    public final boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (!(obj instanceof eat)) {
            return false;
        }
        eat eatVar = (eat) obj;
        return bzo.f(this.b, eatVar.b) && bzo.f(this.c, eatVar.c) && bzo.f(this.d, eatVar.d) && bzo.f(this.e, eatVar.e) && bzo.f(this.f, eatVar.f) && bzo.f(this.g, eatVar.g) && bzo.f(this.h, eatVar.h) && bzo.f(this.i, eatVar.i) && bzo.f(this.j, eatVar.j) && bzo.f(this.k, eatVar.k) && bzo.f(this.l, eatVar.l) && bzo.f(this.m, eatVar.m) && bzo.f(this.n, eatVar.n) && bzo.f(this.o, eatVar.o) && bzo.f(this.p, eatVar.p) && bzo.f(this.q, eatVar.q) && bzo.f(this.r, eatVar.r) && bzo.f(this.s, eatVar.s) && bzo.f(this.t, eatVar.t) && bzo.f(this.u, eatVar.u) && bzo.f(this.v, eatVar.v) && bzo.f(this.w, eatVar.w) && bzo.f(this.x, eatVar.x) && bzo.f(this.y, eatVar.y) && bzo.f(this.z, eatVar.z) && bzo.f(this.aa, eatVar.aa) && bzo.f(this.ab, eatVar.ab) && bzo.f(this.ac, eatVar.ac) && bzo.f(this.ad, eatVar.ad) && bzo.f(this.ae, eatVar.ae) && bzo.f(this.af, eatVar.af) && bzo.f(this.ag, eatVar.ag) && bzo.f(this.ah, eatVar.ah) && bzo.f(this.ai, eatVar.ai) && bzo.f(this.aj, eatVar.aj) && bzo.f(this.ak, eatVar.ak) && bzo.f(this.al, eatVar.al) && bzo.f(this.am, eatVar.am) && bzo.f(this.an, eatVar.an) && bzo.f(this.ao, eatVar.ao) && bzo.f(this.ap, eatVar.ap) && bzo.f(this.aq, eatVar.aq) && bzo.f(this.ar, eatVar.ar) && bzo.f(this.as, eatVar.as) && bzo.f(this.at, eatVar.at) && bzo.f(this.au, eatVar.au) && bzo.f(this.av, eatVar.av) && bzo.f(this.aw, eatVar.aw) && bzo.f(this.ax, eatVar.ax) && bzo.f(this.ay, eatVar.ay) && bzo.f(this.az, eatVar.az) && bzo.f(this.ba, eatVar.ba) && bzo.f(this.bb, eatVar.bb) && bzo.f(this.bc, eatVar.bc) && bzo.f(this.bd, eatVar.bd) && bzo.f(this.be, eatVar.be) && bzo.f(this.bf, eatVar.bf) && bzo.f(this.bg, eatVar.bg) && bzo.f(this.bh, eatVar.bh) && bzo.f(this.bi, eatVar.bi) && bzo.f(this.bj, eatVar.bj) && bzo.f(this.bk, eatVar.bk) && bzo.f(this.bl, eatVar.bl) && bzo.f(this.bm, eatVar.bm) && bzo.f(this.bn, eatVar.bn) && bzo.f(this.bo, eatVar.bo) && bzo.f(this.bp, eatVar.bp) && bzo.f(this.bq, eatVar.bq) && bzo.f(this.br, eatVar.br) && bzo.f(this.bs, eatVar.bs) && bzo.f(this.bt, eatVar.bt) && bzo.f(this.bu, eatVar.bu) && bzo.f(this.bv, eatVar.bv);
    }

    public final int hashCode() {
        Long l = this.b;
        int iHashCode = (l == null ? 0 : l.hashCode()) * 31;
        Integer num = this.c;
        int iHashCode2 = (iHashCode + (num == null ? 0 : num.hashCode())) * 31;
        Integer num2 = this.d;
        int iHashCode3 = (iHashCode2 + (num2 == null ? 0 : num2.hashCode())) * 31;
        String str = this.e;
        int iHashCode4 = (iHashCode3 + (str == null ? 0 : str.hashCode())) * 31;
        Integer num3 = this.f;
        int iHashCode5 = (iHashCode4 + (num3 == null ? 0 : num3.hashCode())) * 31;
        Integer num4 = this.g;
        int iHashCode6 = (iHashCode5 + (num4 == null ? 0 : num4.hashCode())) * 31;
        Integer num5 = this.h;
        int iHashCode7 = (iHashCode6 + (num5 == null ? 0 : num5.hashCode())) * 31;
        ejo ejoVar = this.i;
        int iHashCode8 = (iHashCode7 + (ejoVar == null ? 0 : ejoVar.hashCode())) * 31;
        ecs ecsVar = this.j;
        int iHashCode9 = (iHashCode8 + (ecsVar == null ? 0 : ecsVar.hashCode())) * 31;
        Integer num6 = this.k;
        int iHashCode10 = (iHashCode9 + (num6 == null ? 0 : num6.hashCode())) * 31;
        Long l2 = this.l;
        int iHashCode11 = (iHashCode10 + (l2 == null ? 0 : l2.hashCode())) * 31;
        Integer num7 = this.m;
        int iHashCode12 = (iHashCode11 + (num7 == null ? 0 : num7.hashCode())) * 31;
        Integer num8 = this.n;
        int iHashCode13 = (iHashCode12 + (num8 == null ? 0 : num8.hashCode())) * 31;
        Long l3 = this.o;
        int iHashCode14 = (iHashCode13 + (l3 == null ? 0 : l3.hashCode())) * 31;
        dzp dzpVar = this.p;
        int iHashCode15 = (iHashCode14 + (dzpVar == null ? 0 : dzpVar.hashCode())) * 31;
        Integer num9 = this.q;
        int iHashCode16 = (iHashCode15 + (num9 == null ? 0 : num9.hashCode())) * 31;
        Integer num10 = this.r;
        int iHashCode17 = (iHashCode16 + (num10 == null ? 0 : num10.hashCode())) * 31;
        String str2 = this.s;
        int iHashCode18 = (iHashCode17 + (str2 == null ? 0 : str2.hashCode())) * 31;
        Long l4 = this.t;
        int iHashCode19 = (iHashCode18 + (l4 == null ? 0 : l4.hashCode())) * 31;
        Long l5 = this.u;
        int iHashCode20 = (iHashCode19 + (l5 == null ? 0 : l5.hashCode())) * 31;
        Integer num11 = this.v;
        int iHashCode21 = (iHashCode20 + (num11 == null ? 0 : num11.hashCode())) * 31;
        String str3 = this.w;
        int iHashCode22 = (iHashCode21 + (str3 == null ? 0 : str3.hashCode())) * 31;
        dzg dzgVar = this.x;
        int iHashCode23 = (iHashCode22 + (dzgVar == null ? 0 : dzgVar.hashCode())) * 31;
        Integer num12 = this.y;
        int iHashCode24 = (iHashCode23 + (num12 == null ? 0 : num12.hashCode())) * 31;
        ego egoVar = this.z;
        int iHashCode25 = (iHashCode24 + (egoVar == null ? 0 : egoVar.hashCode())) * 31;
        Integer num13 = this.aa;
        int iHashCode26 = (iHashCode25 + (num13 == null ? 0 : num13.hashCode())) * 31;
        egu eguVar = this.ab;
        int iHashCode27 = (iHashCode26 + (eguVar == null ? 0 : eguVar.hashCode())) * 31;
        dxz dxzVar = this.ac;
        int iHashCode28 = (iHashCode27 + (dxzVar == null ? 0 : dxzVar.hashCode())) * 31;
        String str4 = this.ad;
        int iHashCode29 = (iHashCode28 + (str4 == null ? 0 : str4.hashCode())) * 31;
        dwv dwvVar = this.ae;
        int iHashCode30 = (iHashCode29 + (dwvVar == null ? 0 : dwvVar.hashCode())) * 31;
        Integer num14 = this.af;
        int iHashCode31 = (iHashCode30 + (num14 == null ? 0 : num14.hashCode())) * 31;
        Long l6 = this.ag;
        int iHashCode32 = (iHashCode31 + (l6 == null ? 0 : l6.hashCode())) * 31;
        List list = this.ah;
        int iHashCode33 = (iHashCode32 + (list == null ? 0 : list.hashCode())) * 31;
        Integer num15 = this.ai;
        int iHashCode34 = (iHashCode33 + (num15 == null ? 0 : num15.hashCode())) * 31;
        Integer num16 = this.aj;
        int iHashCode35 = (iHashCode34 + (num16 == null ? 0 : num16.hashCode())) * 31;
        Integer num17 = this.ak;
        int iHashCode36 = (iHashCode35 + (num17 == null ? 0 : num17.hashCode())) * 31;
        Integer num18 = this.al;
        int iHashCode37 = (iHashCode36 + (num18 == null ? 0 : num18.hashCode())) * 31;
        Integer num19 = this.am;
        int iHashCode38 = (iHashCode37 + (num19 == null ? 0 : num19.hashCode())) * 31;
        Integer num20 = this.an;
        int iHashCode39 = (iHashCode38 + (num20 == null ? 0 : num20.hashCode())) * 31;
        eeo eeoVar = this.ao;
        int iHashCode40 = (iHashCode39 + (eeoVar == null ? 0 : eeoVar.hashCode())) * 31;
        List list2 = this.ap;
        int iHashCode41 = (iHashCode40 + (list2 == null ? 0 : list2.hashCode())) * 31;
        Integer num21 = this.aq;
        int iHashCode42 = (iHashCode41 + (num21 == null ? 0 : num21.hashCode())) * 31;
        dzd dzdVar = this.ar;
        int iHashCode43 = (iHashCode42 + (dzdVar == null ? 0 : dzdVar.hashCode())) * 31;
        ebc ebcVar = this.as;
        int iHashCode44 = (iHashCode43 + (ebcVar == null ? 0 : ebcVar.hashCode())) * 31;
        ean eanVar = this.at;
        int iHashCode45 = (iHashCode44 + (eanVar == null ? 0 : eanVar.hashCode())) * 31;
        String str5 = this.au;
        int iHashCode46 = (iHashCode45 + (str5 == null ? 0 : str5.hashCode())) * 31;
        efw efwVar = this.av;
        int iHashCode47 = (iHashCode46 + (efwVar == null ? 0 : efwVar.hashCode())) * 31;
        dyc dycVar = this.aw;
        int iHashCode48 = (iHashCode47 + (dycVar == null ? 0 : dycVar.hashCode())) * 31;
        String str6 = this.ax;
        int iHashCode49 = (iHashCode48 + (str6 == null ? 0 : str6.hashCode())) * 31;
        dzs dzsVar = this.ay;
        int iHashCode50 = (iHashCode49 + (dzsVar == null ? 0 : dzsVar.hashCode())) * 31;
        Long l7 = this.az;
        int iHashCode51 = (iHashCode50 + (l7 == null ? 0 : l7.hashCode())) * 31;
        List list3 = this.ba;
        int iHashCode52 = (iHashCode51 + (list3 == null ? 0 : list3.hashCode())) * 31;
        Integer num22 = this.bb;
        int iHashCode53 = (iHashCode52 + (num22 == null ? 0 : num22.hashCode())) * 31;
        dvr dvrVar = this.bc;
        int iHashCode54 = (iHashCode53 + (dvrVar == null ? 0 : dvrVar.hashCode())) * 31;
        Integer num23 = this.bd;
        int iHashCode55 = (iHashCode54 + (num23 == null ? 0 : num23.hashCode())) * 31;
        dyf dyfVar = this.be;
        int iHashCode56 = (iHashCode55 + (dyfVar == null ? 0 : dyfVar.hashCode())) * 31;
        ecy ecyVar = this.bf;
        int iHashCode57 = (iHashCode56 + (ecyVar == null ? 0 : ecyVar.hashCode())) * 31;
        Long l8 = this.bg;
        int iHashCode58 = (iHashCode57 + (l8 == null ? 0 : l8.hashCode())) * 31;
        dzm dzmVar = this.bh;
        int iHashCode59 = (iHashCode58 + (dzmVar == null ? 0 : dzmVar.hashCode())) * 31;
        eib eibVar = this.bi;
        int iHashCode60 = (iHashCode59 + (eibVar == null ? 0 : eibVar.hashCode())) * 31;
        ebr ebrVar = this.bj;
        int iHashCode61 = (iHashCode60 + (ebrVar == null ? 0 : ebrVar.hashCode())) * 31;
        Long l9 = this.bk;
        int iHashCode62 = (iHashCode61 + (l9 == null ? 0 : l9.hashCode())) * 31;
        Long l10 = this.bl;
        int iHashCode63 = (iHashCode62 + (l10 == null ? 0 : l10.hashCode())) * 31;
        Long l11 = this.bm;
        int iHashCode64 = (iHashCode63 + (l11 == null ? 0 : l11.hashCode())) * 31;
        Long l12 = this.bn;
        int iHashCode65 = (iHashCode64 + (l12 == null ? 0 : l12.hashCode())) * 31;
        Long l13 = this.bo;
        int iHashCode66 = (iHashCode65 + (l13 == null ? 0 : l13.hashCode())) * 31;
        Long l14 = this.bp;
        int iHashCode67 = (iHashCode66 + (l14 == null ? 0 : l14.hashCode())) * 31;
        Long l15 = this.bq;
        int iHashCode68 = (iHashCode67 + (l15 == null ? 0 : l15.hashCode())) * 31;
        eik eikVar = this.br;
        int iHashCode69 = (iHashCode68 + (eikVar == null ? 0 : eikVar.hashCode())) * 31;
        ebx ebxVar = this.bs;
        int iHashCode70 = (iHashCode69 + (ebxVar == null ? 0 : ebxVar.hashCode())) * 31;
        dwp dwpVar = this.bt;
        int iHashCode71 = (iHashCode70 + (dwpVar == null ? 0 : dwpVar.hashCode())) * 31;
        String str7 = this.bu;
        int iHashCode72 = (iHashCode71 + (str7 == null ? 0 : str7.hashCode())) * 31;
        edq edqVar = this.bv;
        return iHashCode72 + (edqVar != null ? edqVar.hashCode() : 0);
    }

    public final String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(cnb.z(-239977002695466L));
        dkz.ad(sb, this.b, -241553255693098L);
        bjs.w(sb, this.c, -241548960725802L);
        bjs.w(sb, this.d, -241471651314474L);
        yg.u(sb, this.e, -241381457001258L);
        bjs.w(sb, this.f, -241377162033962L);
        bjs.w(sb, this.g, -241828133600042L);
        bjs.w(sb, this.h, -241815248698154L);
        sb.append(this.i);
        sb.append(cnb.z(-241729349352234L));
        sb.append(this.j);
        sb.append(cnb.z(-241686399679274L));
        bjs.w(sb, this.k, -241016384781098L);
        dkz.ad(sb, this.l, -240874650860330L);
        bjs.w(sb, this.m, -240810226350890L);
        bjs.w(sb, this.n, -241342802295594L);
        dkz.ad(sb, this.o, -241192478440234L);
        sb.append(this.p);
        sb.append(cnb.z(-241119463996202L));
        bjs.w(sb, this.q, -238301965450026L);
        bjs.w(sb, this.r, -238190296300330L);
        yg.u(sb, this.s, -238121576823594L);
        dkz.ad(sb, this.t, -238052857346858L);
        dkz.ad(sb, this.u, -238594023226154L);
        bjs.w(sb, this.v, -238486649043754L);
        yg.u(sb, this.w, -238409339632426L);
        sb.append(this.x);
        sb.append(cnb.z(-238353505057578L));
        bjs.w(sb, this.y, -237692080093994L);
        sb.append(this.z);
        sb.append(cnb.z(-237627655584554L));
        bjs.w(sb, this.aa, -237563231075114L);
        sb.append(this.ab);
        sb.append(cnb.z(-237992727804714L));
        sb.append(this.ac);
        sb.append(cnb.z(-237919713360682L));
        yg.u(sb, this.ad, -237842403949354L);
        sb.append(this.ae);
        sb.append(cnb.z(-237786569374506L));
        bjs.w(sb, this.af, -239362822372138L);
        dkz.ad(sb, this.ag, -239251153222442L);
        yg.v(sb, this.ah, -239208203549482L);
        bjs.w(sb, this.ai, -239637700279082L);
        bjs.w(sb, this.aj, -239586160671530L);
        bjs.w(sb, this.ak, -239427246881578L);
        bjs.w(sb, this.al, -238856016231210L);
        bjs.w(sb, this.am, -238727167212330L);
        bjs.w(sb, this.an, -239122304203562L);
        sb.append(this.ao);
        sb.append(cnb.z(-239105124334378L));
        yg.v(sb, this.ap, -239036404857642L);
        bjs.w(sb, this.aq, -238967685380906L);
        sb.append(this.ar);
        sb.append(cnb.z(-238890375969578L));
        sb.append(this.as);
        sb.append(cnb.z(-244873265412906L));
        sb.append(this.at);
        sb.append(cnb.z(-244795956001578L));
        yg.u(sb, this.au, -244662812015402L);
        sb.append(this.av);
        sb.append(cnb.z(-245105193646890L));
        sb.append(this.aw);
        sb.append(cnb.z(-245083718810410L));
        yg.u(sb, this.ax, -245019294300970L);
        sb.append(this.ay);
        sb.append(cnb.z(-244344984435498L));
        dkz.ad(sb, this.az, -244297739795242L);
        yg.v(sb, this.ba, -244173185743658L);
        bjs.w(sb, this.bb, -244125941103402L);
        sb.append(this.bc);
        sb.append(cnb.z(-244546847898410L));
        bjs.w(sb, this.bd, -244503898225450L);
        sb.append(this.be);
        sb.append(cnb.z(-244392229075754L));
        sb.append(this.bf);
        sb.append(cnb.z(-245925532400426L));
        dkz.ad(sb, this.bg, -245753733708586L);
        sb.append(this.bh);
        sb.append(cnb.z(-246251949914922L));
        sb.append(this.bi);
        sb.append(cnb.z(-246131690830634L));
        sb.append(this.bj);
        sb.append(cnb.z(-246032906582826L));
        dkz.ad(sb, this.bk, -245380071553834L);
        dkz.ad(sb, this.bl, -245195387960106L);
        dkz.ad(sb, this.bm, -245577640049450L);
        dkz.ad(sb, this.bn, -242674242157354L);
        dkz.ad(sb, this.bo, -242584047844138L);
        dkz.ad(sb, this.bp, -242493853530922L);
        dkz.ad(sb, this.bq, -242927645227818L);
        sb.append(this.br);
        sb.append(cnb.z(-242828860980010L));
        sb.append(this.bs);
        sb.append(cnb.z(-242730076732202L));
        sb.append(this.bt);
        sb.append(cnb.z(-242038586997546L));
        yg.u(sb, this.bu, -241991342357290L);
        sb.append(this.bv);
        sb.append(')');
        return sb.toString();
    }
}
