package me.hd.wauxv.obf;

import net.bytebuddy.jar.asm.Opcodes;
import okhttp3.internal.http2.Http2Connection;

/* JADX INFO: compiled from: r8-map-id-b9de5da7d0413052737328a4e696e1bcc3145db8f6a41e1e318485e124198cd6 */
/* JADX INFO: loaded from: classes.dex */
public final /* synthetic */ class eeg implements bgx {
    public static final eeg b;
    private static final dfx descriptor;

    static {
        eeg eegVar = new eeg();
        b = eegVar;
        cuc cucVar = new cuc("me.hd.wauxv.hook.micromsg.core.protobuf.old.proto.TimeLineObjectProto.sc1Proto" /* "me.hd.wauxv.hook.micromsg.core.protobuf.old.proto.TimeLineObjectProto.sc1Proto" /* "me.hd.wauxv.hook.micromsg.core.protobuf.old.proto.TimeLineObjectProto.sc1Proto" /* cnb.z(-278167851891498L)  */, eegVar, 30);
        bjs.y(-277261613792042L, cucVar, false, 1);
        bjs.y(-277201484249898L, cucVar, false, 2);
        bjs.y(-277124174838570L, cucVar, false, 3);
        bjs.y(-277626686012202L, cucVar, false, 4);
        bjs.y(-277557966535466L, cucVar, false, 5);
        bjs.y(-277429117516586L, cucVar, false, 6);
        bjs.y(-277364693007146L, cucVar, false, 7);
        bjs.y(-278945240972074L, cucVar, false, 8);
        bjs.y(-278885111429930L, cucVar, false, 9);
        bjs.y(-278846456724266L, cucVar, false, 10);
        bjs.y(-278803507051306L, cucVar, false, 11);
        bjs.y(-278777737247530L, cucVar, false, 12);
        bjs.y(-279215823911722L, cucVar, false, 13);
        bjs.y(-279228708813610L, cucVar, false, 14);
        bjs.y(-279074089990954L, cucVar, false, 15);
        bjs.y(-278438434831146L, cucVar, false, 17);
        bjs.y(-278288110975786L, cucVar, false, 18);
        bjs.y(-278262341172010L, cucVar, false, 19);
        bjs.y(-278223686466346L, cucVar, false, 20);
        bjs.y(-278721902672682L, cucVar, false, 21);
        bjs.y(-278614528490282L, cucVar, false, 22);
        bjs.y(-278489974438698L, cucVar, false, 23);
        bjs.y(-278481384504106L, cucVar, false, 24);
        bjs.y(-266837728164650L, cucVar, false, 25);
        bjs.y(-266751828818730L, cucVar, false, 26);
        bjs.y(-266726059014954L, cucVar, false, 27);
        bjs.y(-266640159669034L, cucVar, false, 28);
        bjs.y(-267181325548330L, cucVar, false, 29);
        bjs.y(-267056771496746L, cucVar, false, 30);
        bjs.y(-267000936921898L, cucVar, false, 31);
        descriptor = cucVar;
    }

    @Override // me.hd.wauxv.obf.btd
    public final Object a(ajt ajtVar) {
        String str;
        Integer num;
        Integer num2;
        String str2;
        String str3;
        Integer num3;
        Integer num4;
        Integer num5;
        Float f;
        String str4;
        String str5;
        String str6;
        String str7;
        String str8;
        String str9;
        String str10;
        String str11;
        String str12;
        boolean z;
        ein einVar;
        String str13;
        int i;
        int i2;
        dfx dfxVar = descriptor;
        acm acmVarP = ajtVar.p(dfxVar);
        acmVarP.getClass();
        String str14 = null;
        ein einVar2 = null;
        Boolean bool = null;
        dte dteVar = null;
        Boolean bool2 = null;
        dws dwsVar = null;
        efd efdVar = null;
        String str15 = null;
        Integer num6 = null;
        String str16 = null;
        String str17 = null;
        Long l = null;
        ehv ehvVar = null;
        String str18 = null;
        Integer num7 = null;
        String str19 = null;
        String str20 = null;
        String str21 = null;
        String str22 = null;
        String str23 = null;
        String str24 = null;
        String str25 = null;
        Float f2 = null;
        Integer num8 = null;
        Integer num9 = null;
        Integer num10 = null;
        String str26 = null;
        String str27 = null;
        Integer num11 = null;
        String str28 = null;
        int i3 = 0;
        boolean z2 = true;
        while (z2) {
            int i4 = i3;
            int iF = acmVarP.f(dfxVar);
            switch (iF) {
                case -1:
                    String str29 = str19;
                    i3 = i4;
                    Boolean bool3 = bool;
                    String str30 = str18;
                    str = str14;
                    num = num7;
                    num2 = num11;
                    str15 = str15;
                    str2 = str27;
                    str3 = str26;
                    num3 = num10;
                    num4 = num9;
                    num5 = num8;
                    f = f2;
                    str4 = str25;
                    str5 = str24;
                    str6 = str23;
                    str7 = str22;
                    str8 = str21;
                    str9 = str20;
                    str10 = str29;
                    str11 = str30;
                    bool = bool3;
                    str12 = str28;
                    z = false;
                    str14 = str;
                    num7 = num;
                    str19 = str10;
                    str20 = str9;
                    str21 = str8;
                    str22 = str7;
                    str23 = str6;
                    str24 = str5;
                    str25 = str4;
                    f2 = f;
                    num8 = num5;
                    num9 = num4;
                    num10 = num3;
                    str26 = str3;
                    str27 = str2;
                    num11 = num2;
                    z2 = z;
                    str28 = str12;
                    str18 = str11;
                    break;
                case 0:
                    einVar = einVar2;
                    String str31 = str19;
                    Boolean bool4 = bool;
                    String str32 = str18;
                    str = str14;
                    String str33 = (String) acmVarP.i(dfxVar, 0, dnh.b, str32);
                    i3 = i4 | 1;
                    num = num7;
                    bool = bool4;
                    str15 = str15;
                    str12 = str28;
                    z = z2;
                    num2 = num11;
                    str2 = str27;
                    str3 = str26;
                    num3 = num10;
                    num4 = num9;
                    num5 = num8;
                    f = f2;
                    str4 = str25;
                    str5 = str24;
                    str6 = str23;
                    str7 = str22;
                    str8 = str21;
                    str9 = str20;
                    str10 = str31;
                    str11 = str33;
                    einVar2 = einVar;
                    str14 = str;
                    num7 = num;
                    str19 = str10;
                    str20 = str9;
                    str21 = str8;
                    str22 = str7;
                    str23 = str6;
                    str24 = str5;
                    str25 = str4;
                    f2 = f;
                    num8 = num5;
                    num9 = num4;
                    num10 = num3;
                    str26 = str3;
                    str27 = str2;
                    num11 = num2;
                    z2 = z;
                    str28 = str12;
                    str18 = str11;
                    break;
                case 1:
                    Boolean bool5 = bool;
                    String str34 = str19;
                    i3 = i4 | 2;
                    num = (Integer) acmVarP.i(dfxVar, 1, bqj.b, num7);
                    bool = bool5;
                    str15 = str15;
                    einVar2 = einVar2;
                    str12 = str28;
                    z = z2;
                    num2 = num11;
                    str2 = str27;
                    str3 = str26;
                    num3 = num10;
                    num4 = num9;
                    num5 = num8;
                    f = f2;
                    str4 = str25;
                    str5 = str24;
                    str6 = str23;
                    str7 = str22;
                    str8 = str21;
                    str9 = str20;
                    str10 = str34;
                    str11 = str18;
                    str = str14;
                    str14 = str;
                    num7 = num;
                    str19 = str10;
                    str20 = str9;
                    str21 = str8;
                    str22 = str7;
                    str23 = str6;
                    str24 = str5;
                    str25 = str4;
                    f2 = f;
                    num8 = num5;
                    num9 = num4;
                    num10 = num3;
                    str26 = str3;
                    str27 = str2;
                    num11 = num2;
                    z2 = z;
                    str28 = str12;
                    str18 = str11;
                    break;
                case 2:
                    einVar = einVar2;
                    String str35 = (String) acmVarP.i(dfxVar, 2, dnh.b, str19);
                    i3 = i4 | 4;
                    str11 = str18;
                    num = num7;
                    bool = bool;
                    str15 = str15;
                    str = str14;
                    str12 = str28;
                    z = z2;
                    num2 = num11;
                    str2 = str27;
                    str3 = str26;
                    num3 = num10;
                    num4 = num9;
                    num5 = num8;
                    f = f2;
                    str4 = str25;
                    str5 = str24;
                    str6 = str23;
                    str7 = str22;
                    str8 = str21;
                    str9 = str20;
                    str10 = str35;
                    einVar2 = einVar;
                    str14 = str;
                    num7 = num;
                    str19 = str10;
                    str20 = str9;
                    str21 = str8;
                    str22 = str7;
                    str23 = str6;
                    str24 = str5;
                    str25 = str4;
                    f2 = f;
                    num8 = num5;
                    num9 = num4;
                    num10 = num3;
                    str26 = str3;
                    str27 = str2;
                    num11 = num2;
                    z2 = z;
                    str28 = str12;
                    str18 = str11;
                    break;
                case 3:
                    einVar = einVar2;
                    String str36 = (String) acmVarP.i(dfxVar, 3, dnh.b, str20);
                    i3 = i4 | 8;
                    str11 = str18;
                    str10 = str19;
                    bool = bool;
                    str15 = str15;
                    str = str14;
                    num = num7;
                    str12 = str28;
                    z = z2;
                    num2 = num11;
                    str2 = str27;
                    str3 = str26;
                    num3 = num10;
                    num4 = num9;
                    num5 = num8;
                    f = f2;
                    str4 = str25;
                    str5 = str24;
                    str6 = str23;
                    str7 = str22;
                    str8 = str21;
                    str9 = str36;
                    einVar2 = einVar;
                    str14 = str;
                    num7 = num;
                    str19 = str10;
                    str20 = str9;
                    str21 = str8;
                    str22 = str7;
                    str23 = str6;
                    str24 = str5;
                    str25 = str4;
                    f2 = f;
                    num8 = num5;
                    num9 = num4;
                    num10 = num3;
                    str26 = str3;
                    str27 = str2;
                    num11 = num2;
                    z2 = z;
                    str28 = str12;
                    str18 = str11;
                    break;
                case 4:
                    einVar = einVar2;
                    String str37 = (String) acmVarP.i(dfxVar, 4, dnh.b, str21);
                    i3 = i4 | 16;
                    str11 = str18;
                    str9 = str20;
                    bool = bool;
                    str15 = str15;
                    str = str14;
                    str10 = str19;
                    str12 = str28;
                    num = num7;
                    z = z2;
                    num2 = num11;
                    str2 = str27;
                    str3 = str26;
                    num3 = num10;
                    num4 = num9;
                    num5 = num8;
                    f = f2;
                    str4 = str25;
                    str5 = str24;
                    str6 = str23;
                    str7 = str22;
                    str8 = str37;
                    einVar2 = einVar;
                    str14 = str;
                    num7 = num;
                    str19 = str10;
                    str20 = str9;
                    str21 = str8;
                    str22 = str7;
                    str23 = str6;
                    str24 = str5;
                    str25 = str4;
                    f2 = f;
                    num8 = num5;
                    num9 = num4;
                    num10 = num3;
                    str26 = str3;
                    str27 = str2;
                    num11 = num2;
                    z2 = z;
                    str28 = str12;
                    str18 = str11;
                    break;
                case 5:
                    einVar = einVar2;
                    String str38 = (String) acmVarP.i(dfxVar, 5, dnh.b, str22);
                    i3 = i4 | 32;
                    str11 = str18;
                    str8 = str21;
                    bool = bool;
                    str15 = str15;
                    str = str14;
                    str9 = str20;
                    str12 = str28;
                    str10 = str19;
                    z = z2;
                    num = num7;
                    num2 = num11;
                    str2 = str27;
                    str3 = str26;
                    num3 = num10;
                    num4 = num9;
                    num5 = num8;
                    f = f2;
                    str4 = str25;
                    str5 = str24;
                    str6 = str23;
                    str7 = str38;
                    einVar2 = einVar;
                    str14 = str;
                    num7 = num;
                    str19 = str10;
                    str20 = str9;
                    str21 = str8;
                    str22 = str7;
                    str23 = str6;
                    str24 = str5;
                    str25 = str4;
                    f2 = f;
                    num8 = num5;
                    num9 = num4;
                    num10 = num3;
                    str26 = str3;
                    str27 = str2;
                    num11 = num2;
                    z2 = z;
                    str28 = str12;
                    str18 = str11;
                    break;
                case 6:
                    einVar = einVar2;
                    String str39 = (String) acmVarP.i(dfxVar, 6, dnh.b, str23);
                    i3 = i4 | 64;
                    str11 = str18;
                    str7 = str22;
                    bool = bool;
                    str15 = str15;
                    str = str14;
                    str8 = str21;
                    str12 = str28;
                    str9 = str20;
                    z = z2;
                    str10 = str19;
                    num2 = num11;
                    num = num7;
                    str2 = str27;
                    str3 = str26;
                    num3 = num10;
                    num4 = num9;
                    num5 = num8;
                    f = f2;
                    str4 = str25;
                    str5 = str24;
                    str6 = str39;
                    einVar2 = einVar;
                    str14 = str;
                    num7 = num;
                    str19 = str10;
                    str20 = str9;
                    str21 = str8;
                    str22 = str7;
                    str23 = str6;
                    str24 = str5;
                    str25 = str4;
                    f2 = f;
                    num8 = num5;
                    num9 = num4;
                    num10 = num3;
                    str26 = str3;
                    str27 = str2;
                    num11 = num2;
                    z2 = z;
                    str28 = str12;
                    str18 = str11;
                    break;
                case 7:
                    einVar = einVar2;
                    String str40 = (String) acmVarP.i(dfxVar, 7, dnh.b, str24);
                    i3 = i4 | 128;
                    str11 = str18;
                    str6 = str23;
                    bool = bool;
                    str15 = str15;
                    str = str14;
                    str7 = str22;
                    str12 = str28;
                    str8 = str21;
                    z = z2;
                    str9 = str20;
                    num2 = num11;
                    str10 = str19;
                    str2 = str27;
                    num = num7;
                    str3 = str26;
                    num3 = num10;
                    num4 = num9;
                    num5 = num8;
                    f = f2;
                    str4 = str25;
                    str5 = str40;
                    einVar2 = einVar;
                    str14 = str;
                    num7 = num;
                    str19 = str10;
                    str20 = str9;
                    str21 = str8;
                    str22 = str7;
                    str23 = str6;
                    str24 = str5;
                    str25 = str4;
                    f2 = f;
                    num8 = num5;
                    num9 = num4;
                    num10 = num3;
                    str26 = str3;
                    str27 = str2;
                    num11 = num2;
                    z2 = z;
                    str28 = str12;
                    str18 = str11;
                    break;
                case 8:
                    einVar = einVar2;
                    String str41 = (String) acmVarP.i(dfxVar, 8, dnh.b, str25);
                    i3 = i4 | 256;
                    str11 = str18;
                    str5 = str24;
                    bool = bool;
                    str15 = str15;
                    str = str14;
                    str6 = str23;
                    str12 = str28;
                    str7 = str22;
                    z = z2;
                    str8 = str21;
                    num2 = num11;
                    str9 = str20;
                    str2 = str27;
                    str10 = str19;
                    str3 = str26;
                    num = num7;
                    num3 = num10;
                    num4 = num9;
                    num5 = num8;
                    f = f2;
                    str4 = str41;
                    einVar2 = einVar;
                    str14 = str;
                    num7 = num;
                    str19 = str10;
                    str20 = str9;
                    str21 = str8;
                    str22 = str7;
                    str23 = str6;
                    str24 = str5;
                    str25 = str4;
                    f2 = f;
                    num8 = num5;
                    num9 = num4;
                    num10 = num3;
                    str26 = str3;
                    str27 = str2;
                    num11 = num2;
                    z2 = z;
                    str28 = str12;
                    str18 = str11;
                    break;
                case 9:
                    einVar = einVar2;
                    Float f3 = (Float) acmVarP.i(dfxVar, 9, bbm.b, f2);
                    i3 = i4 | 512;
                    str11 = str18;
                    str4 = str25;
                    bool = bool;
                    str15 = str15;
                    str = str14;
                    str5 = str24;
                    str12 = str28;
                    str6 = str23;
                    z = z2;
                    str7 = str22;
                    num2 = num11;
                    str8 = str21;
                    str2 = str27;
                    str9 = str20;
                    str3 = str26;
                    str10 = str19;
                    num3 = num10;
                    num = num7;
                    num4 = num9;
                    num5 = num8;
                    f = f3;
                    einVar2 = einVar;
                    str14 = str;
                    num7 = num;
                    str19 = str10;
                    str20 = str9;
                    str21 = str8;
                    str22 = str7;
                    str23 = str6;
                    str24 = str5;
                    str25 = str4;
                    f2 = f;
                    num8 = num5;
                    num9 = num4;
                    num10 = num3;
                    str26 = str3;
                    str27 = str2;
                    num11 = num2;
                    z2 = z;
                    str28 = str12;
                    str18 = str11;
                    break;
                case 10:
                    einVar = einVar2;
                    Integer num12 = (Integer) acmVarP.i(dfxVar, 10, bqj.b, num8);
                    i3 = i4 | 1024;
                    str11 = str18;
                    f = f2;
                    bool = bool;
                    str15 = str15;
                    str = str14;
                    str4 = str25;
                    str12 = str28;
                    str5 = str24;
                    z = z2;
                    str6 = str23;
                    num2 = num11;
                    str7 = str22;
                    str2 = str27;
                    str8 = str21;
                    str3 = str26;
                    str9 = str20;
                    num3 = num10;
                    str10 = str19;
                    num4 = num9;
                    num5 = num12;
                    num = num7;
                    einVar2 = einVar;
                    str14 = str;
                    num7 = num;
                    str19 = str10;
                    str20 = str9;
                    str21 = str8;
                    str22 = str7;
                    str23 = str6;
                    str24 = str5;
                    str25 = str4;
                    f2 = f;
                    num8 = num5;
                    num9 = num4;
                    num10 = num3;
                    str26 = str3;
                    str27 = str2;
                    num11 = num2;
                    z2 = z;
                    str28 = str12;
                    str18 = str11;
                    break;
                case 11:
                    ein einVar3 = einVar2;
                    Integer num13 = (Integer) acmVarP.i(dfxVar, 11, bqj.b, num9);
                    i3 = i4 | 2048;
                    str11 = str18;
                    num5 = num8;
                    bool = bool;
                    str15 = str15;
                    str = str14;
                    f = f2;
                    str12 = str28;
                    str4 = str25;
                    z = z2;
                    str5 = str24;
                    num2 = num11;
                    str6 = str23;
                    str2 = str27;
                    str7 = str22;
                    str3 = str26;
                    str8 = str21;
                    num3 = num10;
                    num4 = num13;
                    str9 = str20;
                    einVar2 = einVar3;
                    str10 = str19;
                    num = num7;
                    str14 = str;
                    num7 = num;
                    str19 = str10;
                    str20 = str9;
                    str21 = str8;
                    str22 = str7;
                    str23 = str6;
                    str24 = str5;
                    str25 = str4;
                    f2 = f;
                    num8 = num5;
                    num9 = num4;
                    num10 = num3;
                    str26 = str3;
                    str27 = str2;
                    num11 = num2;
                    z2 = z;
                    str28 = str12;
                    str18 = str11;
                    break;
                case 12:
                    ein einVar4 = einVar2;
                    Integer num14 = (Integer) acmVarP.i(dfxVar, 12, bqj.b, num10);
                    i3 = i4 | 4096;
                    str11 = str18;
                    num4 = num9;
                    bool = bool;
                    str15 = str15;
                    str = str14;
                    num5 = num8;
                    str12 = str28;
                    f = f2;
                    z = z2;
                    str4 = str25;
                    num2 = num11;
                    str5 = str24;
                    str2 = str27;
                    str6 = str23;
                    str3 = str26;
                    num3 = num14;
                    str7 = str22;
                    einVar2 = einVar4;
                    str8 = str21;
                    str9 = str20;
                    str10 = str19;
                    num = num7;
                    str14 = str;
                    num7 = num;
                    str19 = str10;
                    str20 = str9;
                    str21 = str8;
                    str22 = str7;
                    str23 = str6;
                    str24 = str5;
                    str25 = str4;
                    f2 = f;
                    num8 = num5;
                    num9 = num4;
                    num10 = num3;
                    str26 = str3;
                    str27 = str2;
                    num11 = num2;
                    z2 = z;
                    str28 = str12;
                    str18 = str11;
                    break;
                case 13:
                    ein einVar5 = einVar2;
                    String str42 = (String) acmVarP.i(dfxVar, 13, dnh.b, str26);
                    i3 = i4 | 8192;
                    str11 = str18;
                    num3 = num10;
                    bool = bool;
                    str15 = str15;
                    str = str14;
                    num4 = num9;
                    str12 = str28;
                    num5 = num8;
                    z = z2;
                    f = f2;
                    num2 = num11;
                    str4 = str25;
                    str2 = str27;
                    str3 = str42;
                    str5 = str24;
                    einVar2 = einVar5;
                    str6 = str23;
                    str7 = str22;
                    str8 = str21;
                    str9 = str20;
                    str10 = str19;
                    num = num7;
                    str14 = str;
                    num7 = num;
                    str19 = str10;
                    str20 = str9;
                    str21 = str8;
                    str22 = str7;
                    str23 = str6;
                    str24 = str5;
                    str25 = str4;
                    f2 = f;
                    num8 = num5;
                    num9 = num4;
                    num10 = num3;
                    str26 = str3;
                    str27 = str2;
                    num11 = num2;
                    z2 = z;
                    str28 = str12;
                    str18 = str11;
                    break;
                case 14:
                    ein einVar6 = einVar2;
                    String str43 = (String) acmVarP.i(dfxVar, 14, dnh.b, str27);
                    i3 = i4 | 16384;
                    str11 = str18;
                    str3 = str26;
                    str12 = str28;
                    str15 = str15;
                    str = str14;
                    num3 = num10;
                    z = z2;
                    num4 = num9;
                    num2 = num11;
                    str2 = str43;
                    num5 = num8;
                    einVar2 = einVar6;
                    f = f2;
                    str4 = str25;
                    str5 = str24;
                    str6 = str23;
                    str7 = str22;
                    str8 = str21;
                    str9 = str20;
                    str10 = str19;
                    num = num7;
                    str14 = str;
                    num7 = num;
                    str19 = str10;
                    str20 = str9;
                    str21 = str8;
                    str22 = str7;
                    str23 = str6;
                    str24 = str5;
                    str25 = str4;
                    f2 = f;
                    num8 = num5;
                    num9 = num4;
                    num10 = num3;
                    str26 = str3;
                    str27 = str2;
                    num11 = num2;
                    z2 = z;
                    str28 = str12;
                    str18 = str11;
                    break;
                case 15:
                    ein einVar7 = einVar2;
                    Integer num15 = (Integer) acmVarP.i(dfxVar, 15, bqj.b, num11);
                    i3 = i4 | 32768;
                    str11 = str18;
                    str2 = str27;
                    str12 = str28;
                    str15 = str15;
                    str = str14;
                    str3 = str26;
                    z = z2;
                    num2 = num15;
                    num3 = num10;
                    einVar2 = einVar7;
                    num4 = num9;
                    num5 = num8;
                    f = f2;
                    str4 = str25;
                    str5 = str24;
                    str6 = str23;
                    str7 = str22;
                    str8 = str21;
                    str9 = str20;
                    str10 = str19;
                    num = num7;
                    str14 = str;
                    num7 = num;
                    str19 = str10;
                    str20 = str9;
                    str21 = str8;
                    str22 = str7;
                    str23 = str6;
                    str24 = str5;
                    str25 = str4;
                    f2 = f;
                    num8 = num5;
                    num9 = num4;
                    num10 = num3;
                    str26 = str3;
                    str27 = str2;
                    num11 = num2;
                    z2 = z;
                    str28 = str12;
                    str18 = str11;
                    break;
                case 16:
                    i3 = i4 | 65536;
                    str12 = (String) acmVarP.i(dfxVar, 16, dnh.b, str28);
                    str11 = str18;
                    z = z2;
                    str15 = str15;
                    einVar2 = einVar2;
                    str = str14;
                    num2 = num11;
                    str2 = str27;
                    str3 = str26;
                    num3 = num10;
                    num4 = num9;
                    num5 = num8;
                    f = f2;
                    str4 = str25;
                    str5 = str24;
                    str6 = str23;
                    str7 = str22;
                    str8 = str21;
                    str9 = str20;
                    str10 = str19;
                    num = num7;
                    str14 = str;
                    num7 = num;
                    str19 = str10;
                    str20 = str9;
                    str21 = str8;
                    str22 = str7;
                    str23 = str6;
                    str24 = str5;
                    str25 = str4;
                    f2 = f;
                    num8 = num5;
                    num9 = num4;
                    num10 = num3;
                    str26 = str3;
                    str27 = str2;
                    num11 = num2;
                    z2 = z;
                    str28 = str12;
                    str18 = str11;
                    break;
                case 17:
                    ein einVar8 = einVar2;
                    i3 = i4 | 131072;
                    str15 = (String) acmVarP.i(dfxVar, 17, dnh.b, str15);
                    str11 = str18;
                    str12 = str28;
                    einVar2 = einVar8;
                    str = str14;
                    z = z2;
                    num2 = num11;
                    str2 = str27;
                    str3 = str26;
                    num3 = num10;
                    num4 = num9;
                    num5 = num8;
                    f = f2;
                    str4 = str25;
                    str5 = str24;
                    str6 = str23;
                    str7 = str22;
                    str8 = str21;
                    str9 = str20;
                    str10 = str19;
                    num = num7;
                    str14 = str;
                    num7 = num;
                    str19 = str10;
                    str20 = str9;
                    str21 = str8;
                    str22 = str7;
                    str23 = str6;
                    str24 = str5;
                    str25 = str4;
                    f2 = f;
                    num8 = num5;
                    num9 = num4;
                    num10 = num3;
                    str26 = str3;
                    str27 = str2;
                    num11 = num2;
                    z2 = z;
                    str28 = str12;
                    str18 = str11;
                    break;
                case 18:
                    str13 = str15;
                    i = i4 | 262144;
                    num6 = (Integer) acmVarP.i(dfxVar, 18, bqj.b, num6);
                    i3 = i;
                    str11 = str18;
                    str12 = str28;
                    str15 = str13;
                    str = str14;
                    z = z2;
                    num2 = num11;
                    str2 = str27;
                    str3 = str26;
                    num3 = num10;
                    num4 = num9;
                    num5 = num8;
                    f = f2;
                    str4 = str25;
                    str5 = str24;
                    str6 = str23;
                    str7 = str22;
                    str8 = str21;
                    str9 = str20;
                    str10 = str19;
                    num = num7;
                    str14 = str;
                    num7 = num;
                    str19 = str10;
                    str20 = str9;
                    str21 = str8;
                    str22 = str7;
                    str23 = str6;
                    str24 = str5;
                    str25 = str4;
                    f2 = f;
                    num8 = num5;
                    num9 = num4;
                    num10 = num3;
                    str26 = str3;
                    str27 = str2;
                    num11 = num2;
                    z2 = z;
                    str28 = str12;
                    str18 = str11;
                    break;
                case 19:
                    str13 = str15;
                    String str44 = (String) acmVarP.i(dfxVar, 19, dnh.b, str16);
                    i = i4 | Opcodes.ASM8;
                    str16 = str44;
                    i3 = i;
                    str11 = str18;
                    str12 = str28;
                    str15 = str13;
                    str = str14;
                    z = z2;
                    num2 = num11;
                    str2 = str27;
                    str3 = str26;
                    num3 = num10;
                    num4 = num9;
                    num5 = num8;
                    f = f2;
                    str4 = str25;
                    str5 = str24;
                    str6 = str23;
                    str7 = str22;
                    str8 = str21;
                    str9 = str20;
                    str10 = str19;
                    num = num7;
                    str14 = str;
                    num7 = num;
                    str19 = str10;
                    str20 = str9;
                    str21 = str8;
                    str22 = str7;
                    str23 = str6;
                    str24 = str5;
                    str25 = str4;
                    f2 = f;
                    num8 = num5;
                    num9 = num4;
                    num10 = num3;
                    str26 = str3;
                    str27 = str2;
                    num11 = num2;
                    z2 = z;
                    str28 = str12;
                    str18 = str11;
                    break;
                case 20:
                    str13 = str15;
                    i = i4 | 1048576;
                    str17 = (String) acmVarP.i(dfxVar, 20, dnh.b, str17);
                    i3 = i;
                    str11 = str18;
                    str12 = str28;
                    str15 = str13;
                    str = str14;
                    z = z2;
                    num2 = num11;
                    str2 = str27;
                    str3 = str26;
                    num3 = num10;
                    num4 = num9;
                    num5 = num8;
                    f = f2;
                    str4 = str25;
                    str5 = str24;
                    str6 = str23;
                    str7 = str22;
                    str8 = str21;
                    str9 = str20;
                    str10 = str19;
                    num = num7;
                    str14 = str;
                    num7 = num;
                    str19 = str10;
                    str20 = str9;
                    str21 = str8;
                    str22 = str7;
                    str23 = str6;
                    str24 = str5;
                    str25 = str4;
                    f2 = f;
                    num8 = num5;
                    num9 = num4;
                    num10 = num3;
                    str26 = str3;
                    str27 = str2;
                    num11 = num2;
                    z2 = z;
                    str28 = str12;
                    str18 = str11;
                    break;
                case 21:
                    str13 = str15;
                    i = i4 | 2097152;
                    l = (Long) acmVarP.i(dfxVar, 21, bya.b, l);
                    i3 = i;
                    str11 = str18;
                    str12 = str28;
                    str15 = str13;
                    str = str14;
                    z = z2;
                    num2 = num11;
                    str2 = str27;
                    str3 = str26;
                    num3 = num10;
                    num4 = num9;
                    num5 = num8;
                    f = f2;
                    str4 = str25;
                    str5 = str24;
                    str6 = str23;
                    str7 = str22;
                    str8 = str21;
                    str9 = str20;
                    str10 = str19;
                    num = num7;
                    str14 = str;
                    num7 = num;
                    str19 = str10;
                    str20 = str9;
                    str21 = str8;
                    str22 = str7;
                    str23 = str6;
                    str24 = str5;
                    str25 = str4;
                    f2 = f;
                    num8 = num5;
                    num9 = num4;
                    num10 = num3;
                    str26 = str3;
                    str27 = str2;
                    num11 = num2;
                    z2 = z;
                    str28 = str12;
                    str18 = str11;
                    break;
                case 22:
                    str13 = str15;
                    i = i4 | 4194304;
                    ehvVar = (ehv) acmVarP.i(dfxVar, 22, eht.b, ehvVar);
                    i3 = i;
                    str11 = str18;
                    str12 = str28;
                    str15 = str13;
                    str = str14;
                    z = z2;
                    num2 = num11;
                    str2 = str27;
                    str3 = str26;
                    num3 = num10;
                    num4 = num9;
                    num5 = num8;
                    f = f2;
                    str4 = str25;
                    str5 = str24;
                    str6 = str23;
                    str7 = str22;
                    str8 = str21;
                    str9 = str20;
                    str10 = str19;
                    num = num7;
                    str14 = str;
                    num7 = num;
                    str19 = str10;
                    str20 = str9;
                    str21 = str8;
                    str22 = str7;
                    str23 = str6;
                    str24 = str5;
                    str25 = str4;
                    f2 = f;
                    num8 = num5;
                    num9 = num4;
                    num10 = num3;
                    str26 = str3;
                    str27 = str2;
                    num11 = num2;
                    z2 = z;
                    str28 = str12;
                    str18 = str11;
                    break;
                case 23:
                    str13 = str15;
                    str14 = (String) acmVarP.i(dfxVar, 23, dnh.b, str14);
                    i2 = 8388608;
                    i3 = i4 | i2;
                    str11 = str18;
                    str12 = str28;
                    str15 = str13;
                    str = str14;
                    z = z2;
                    num2 = num11;
                    str2 = str27;
                    str3 = str26;
                    num3 = num10;
                    num4 = num9;
                    num5 = num8;
                    f = f2;
                    str4 = str25;
                    str5 = str24;
                    str6 = str23;
                    str7 = str22;
                    str8 = str21;
                    str9 = str20;
                    str10 = str19;
                    num = num7;
                    str14 = str;
                    num7 = num;
                    str19 = str10;
                    str20 = str9;
                    str21 = str8;
                    str22 = str7;
                    str23 = str6;
                    str24 = str5;
                    str25 = str4;
                    f2 = f;
                    num8 = num5;
                    num9 = num4;
                    num10 = num3;
                    str26 = str3;
                    str27 = str2;
                    num11 = num2;
                    z2 = z;
                    str28 = str12;
                    str18 = str11;
                    break;
                case 24:
                    str13 = str15;
                    dteVar = (dte) acmVarP.i(dfxVar, 24, dtc.b, dteVar);
                    i2 = Http2Connection.OKHTTP_CLIENT_WINDOW_SIZE;
                    i3 = i4 | i2;
                    str11 = str18;
                    str12 = str28;
                    str15 = str13;
                    str = str14;
                    z = z2;
                    num2 = num11;
                    str2 = str27;
                    str3 = str26;
                    num3 = num10;
                    num4 = num9;
                    num5 = num8;
                    f = f2;
                    str4 = str25;
                    str5 = str24;
                    str6 = str23;
                    str7 = str22;
                    str8 = str21;
                    str9 = str20;
                    str10 = str19;
                    num = num7;
                    str14 = str;
                    num7 = num;
                    str19 = str10;
                    str20 = str9;
                    str21 = str8;
                    str22 = str7;
                    str23 = str6;
                    str24 = str5;
                    str25 = str4;
                    f2 = f;
                    num8 = num5;
                    num9 = num4;
                    num10 = num3;
                    str26 = str3;
                    str27 = str2;
                    num11 = num2;
                    z2 = z;
                    str28 = str12;
                    str18 = str11;
                    break;
                case 25:
                    str13 = str15;
                    bool2 = (Boolean) acmVarP.i(dfxVar, 25, pv.b, bool2);
                    i2 = 33554432;
                    i3 = i4 | i2;
                    str11 = str18;
                    str12 = str28;
                    str15 = str13;
                    str = str14;
                    z = z2;
                    num2 = num11;
                    str2 = str27;
                    str3 = str26;
                    num3 = num10;
                    num4 = num9;
                    num5 = num8;
                    f = f2;
                    str4 = str25;
                    str5 = str24;
                    str6 = str23;
                    str7 = str22;
                    str8 = str21;
                    str9 = str20;
                    str10 = str19;
                    num = num7;
                    str14 = str;
                    num7 = num;
                    str19 = str10;
                    str20 = str9;
                    str21 = str8;
                    str22 = str7;
                    str23 = str6;
                    str24 = str5;
                    str25 = str4;
                    f2 = f;
                    num8 = num5;
                    num9 = num4;
                    num10 = num3;
                    str26 = str3;
                    str27 = str2;
                    num11 = num2;
                    z2 = z;
                    str28 = str12;
                    str18 = str11;
                    break;
                case 26:
                    str13 = str15;
                    bool = (Boolean) acmVarP.i(dfxVar, 26, pv.b, bool);
                    i2 = 67108864;
                    i3 = i4 | i2;
                    str11 = str18;
                    str12 = str28;
                    str15 = str13;
                    str = str14;
                    z = z2;
                    num2 = num11;
                    str2 = str27;
                    str3 = str26;
                    num3 = num10;
                    num4 = num9;
                    num5 = num8;
                    f = f2;
                    str4 = str25;
                    str5 = str24;
                    str6 = str23;
                    str7 = str22;
                    str8 = str21;
                    str9 = str20;
                    str10 = str19;
                    num = num7;
                    str14 = str;
                    num7 = num;
                    str19 = str10;
                    str20 = str9;
                    str21 = str8;
                    str22 = str7;
                    str23 = str6;
                    str24 = str5;
                    str25 = str4;
                    f2 = f;
                    num8 = num5;
                    num9 = num4;
                    num10 = num3;
                    str26 = str3;
                    str27 = str2;
                    num11 = num2;
                    z2 = z;
                    str28 = str12;
                    str18 = str11;
                    break;
                case 27:
                    str13 = str15;
                    einVar2 = (ein) acmVarP.i(dfxVar, 27, eil.b, einVar2);
                    i2 = 134217728;
                    i3 = i4 | i2;
                    str11 = str18;
                    str12 = str28;
                    str15 = str13;
                    str = str14;
                    z = z2;
                    num2 = num11;
                    str2 = str27;
                    str3 = str26;
                    num3 = num10;
                    num4 = num9;
                    num5 = num8;
                    f = f2;
                    str4 = str25;
                    str5 = str24;
                    str6 = str23;
                    str7 = str22;
                    str8 = str21;
                    str9 = str20;
                    str10 = str19;
                    num = num7;
                    str14 = str;
                    num7 = num;
                    str19 = str10;
                    str20 = str9;
                    str21 = str8;
                    str22 = str7;
                    str23 = str6;
                    str24 = str5;
                    str25 = str4;
                    f2 = f;
                    num8 = num5;
                    num9 = num4;
                    num10 = num3;
                    str26 = str3;
                    str27 = str2;
                    num11 = num2;
                    z2 = z;
                    str28 = str12;
                    str18 = str11;
                    break;
                case 28:
                    str13 = str15;
                    dwsVar = (dws) acmVarP.i(dfxVar, 28, dwq.b, dwsVar);
                    i2 = 268435456;
                    i3 = i4 | i2;
                    str11 = str18;
                    str12 = str28;
                    str15 = str13;
                    str = str14;
                    z = z2;
                    num2 = num11;
                    str2 = str27;
                    str3 = str26;
                    num3 = num10;
                    num4 = num9;
                    num5 = num8;
                    f = f2;
                    str4 = str25;
                    str5 = str24;
                    str6 = str23;
                    str7 = str22;
                    str8 = str21;
                    str9 = str20;
                    str10 = str19;
                    num = num7;
                    str14 = str;
                    num7 = num;
                    str19 = str10;
                    str20 = str9;
                    str21 = str8;
                    str22 = str7;
                    str23 = str6;
                    str24 = str5;
                    str25 = str4;
                    f2 = f;
                    num8 = num5;
                    num9 = num4;
                    num10 = num3;
                    str26 = str3;
                    str27 = str2;
                    num11 = num2;
                    z2 = z;
                    str28 = str12;
                    str18 = str11;
                    break;
                case 29:
                    str13 = str15;
                    efdVar = (efd) acmVarP.i(dfxVar, 29, efb.b, efdVar);
                    i2 = 536870912;
                    i3 = i4 | i2;
                    str11 = str18;
                    str12 = str28;
                    str15 = str13;
                    str = str14;
                    z = z2;
                    num2 = num11;
                    str2 = str27;
                    str3 = str26;
                    num3 = num10;
                    num4 = num9;
                    num5 = num8;
                    f = f2;
                    str4 = str25;
                    str5 = str24;
                    str6 = str23;
                    str7 = str22;
                    str8 = str21;
                    str9 = str20;
                    str10 = str19;
                    num = num7;
                    str14 = str;
                    num7 = num;
                    str19 = str10;
                    str20 = str9;
                    str21 = str8;
                    str22 = str7;
                    str23 = str6;
                    str24 = str5;
                    str25 = str4;
                    f2 = f;
                    num8 = num5;
                    num9 = num4;
                    num10 = num3;
                    str26 = str3;
                    str27 = str2;
                    num11 = num2;
                    z2 = z;
                    str28 = str12;
                    str18 = str11;
                    break;
                default:
                    throw new bsd(iF);
            }
        }
        ein einVar9 = einVar2;
        Boolean bool6 = bool;
        String str45 = str15;
        acmVarP._bp(dfxVar);
        Integer num16 = num10;
        ehv ehvVar2 = ehvVar;
        return new eei(i3, str18, num7, str19, str20, str21, str22, str23, str24, str25, f2, num8, num9, num16, str26, str27, num11, str28, str45, num6, str16, str17, l, ehvVar2, str14, dteVar, bool2, bool6, einVar9, dwsVar, efdVar);
    }

    @Override // me.hd.wauxv.obf.btd
    public final void c(avt avtVar, Object obj) {
        eei eeiVar = (eei) obj;
        dfx dfxVar = descriptor;
        acn acnVarO = avtVar.o(dfxVar);
        dnh dnhVar = dnh.b;
        acnVarO.m(dfxVar, 0, dnhVar, eeiVar.a);
        bqj bqjVar = bqj.b;
        acnVarO.m(dfxVar, 1, bqjVar, eeiVar.b);
        acnVarO.m(dfxVar, 2, dnhVar, eeiVar.c);
        acnVarO.m(dfxVar, 3, dnhVar, eeiVar.d);
        acnVarO.m(dfxVar, 4, dnhVar, eeiVar.e);
        acnVarO.m(dfxVar, 5, dnhVar, eeiVar.f);
        acnVarO.m(dfxVar, 6, dnhVar, eeiVar.g);
        acnVarO.m(dfxVar, 7, dnhVar, eeiVar.h);
        acnVarO.m(dfxVar, 8, dnhVar, eeiVar.i);
        acnVarO.m(dfxVar, 9, bbm.b, eeiVar.j);
        acnVarO.m(dfxVar, 10, bqjVar, eeiVar.k);
        acnVarO.m(dfxVar, 11, bqjVar, eeiVar.l);
        acnVarO.m(dfxVar, 12, bqjVar, eeiVar.m);
        acnVarO.m(dfxVar, 13, dnhVar, eeiVar.n);
        acnVarO.m(dfxVar, 14, dnhVar, eeiVar.o);
        acnVarO.m(dfxVar, 15, bqjVar, eeiVar.p);
        acnVarO.m(dfxVar, 16, dnhVar, eeiVar.q);
        acnVarO.m(dfxVar, 17, dnhVar, eeiVar.r);
        acnVarO.m(dfxVar, 18, bqjVar, eeiVar.s);
        acnVarO.m(dfxVar, 19, dnhVar, eeiVar.t);
        acnVarO.m(dfxVar, 20, dnhVar, eeiVar.u);
        acnVarO.m(dfxVar, 21, bya.b, eeiVar.v);
        acnVarO.m(dfxVar, 22, eht.b, eeiVar.w);
        acnVarO.m(dfxVar, 23, dnhVar, eeiVar.x);
        acnVarO.m(dfxVar, 24, dtc.b, eeiVar.y);
        pv pvVar = pv.b;
        acnVarO.m(dfxVar, 25, pvVar, eeiVar.z);
        acnVarO.m(dfxVar, 26, pvVar, eeiVar.aa);
        acnVarO.m(dfxVar, 27, eil.b, eeiVar.ab);
        acnVarO.m(dfxVar, 28, dwq.b, eeiVar.ac);
        acnVarO.m(dfxVar, 29, efb.b, eeiVar.ad);
        acnVarO.a(dfxVar);
    }

    @Override // me.hd.wauxv.obf.bgx
    public final btd[] d() {
        dnh dnhVar = dnh.b;
        btd btdVarT = aye.t(dnhVar);
        bqj bqjVar = bqj.b;
        btd btdVarT2 = aye.t(bqjVar);
        btd btdVarT3 = aye.t(dnhVar);
        btd btdVarT4 = aye.t(dnhVar);
        btd btdVarT5 = aye.t(dnhVar);
        btd btdVarT6 = aye.t(dnhVar);
        btd btdVarT7 = aye.t(dnhVar);
        btd btdVarT8 = aye.t(dnhVar);
        btd btdVarT9 = aye.t(dnhVar);
        btd btdVarT10 = aye.t(bbm.b);
        btd btdVarT11 = aye.t(bqjVar);
        btd btdVarT12 = aye.t(bqjVar);
        btd btdVarT13 = aye.t(bqjVar);
        btd btdVarT14 = aye.t(dnhVar);
        btd btdVarT15 = aye.t(dnhVar);
        btd btdVarT16 = aye.t(bqjVar);
        btd btdVarT17 = aye.t(dnhVar);
        btd btdVarT18 = aye.t(dnhVar);
        btd btdVarT19 = aye.t(bqjVar);
        btd btdVarT20 = aye.t(dnhVar);
        btd btdVarT21 = aye.t(dnhVar);
        btd btdVarT22 = aye.t(bya.b);
        btd btdVarT23 = aye.t(eht.b);
        btd btdVarT24 = aye.t(dnhVar);
        btd btdVarT25 = aye.t(dtc.b);
        pv pvVar = pv.b;
        return new btd[]{btdVarT, btdVarT2, btdVarT3, btdVarT4, btdVarT5, btdVarT6, btdVarT7, btdVarT8, btdVarT9, btdVarT10, btdVarT11, btdVarT12, btdVarT13, btdVarT14, btdVarT15, btdVarT16, btdVarT17, btdVarT18, btdVarT19, btdVarT20, btdVarT21, btdVarT22, btdVarT23, btdVarT24, btdVarT25, aye.t(pvVar), aye.t(pvVar), aye.t(eil.b), aye.t(dwq.b), aye.t(efb.b)};
    }

    @Override // me.hd.wauxv.obf.btd
    public final dfx getDescriptor() {
        return descriptor;
    }
}
