package me.hd.wauxv.obf;

import java.util.List;
import net.bytebuddy.jar.asm.Opcodes;
import okhttp3.internal.http2.Http2Connection;

/* JADX INFO: compiled from: r8-map-id-b9de5da7d0413052737328a4e696e1bcc3145db8f6a41e1e318485e124198cd6 */
/* JADX INFO: loaded from: classes.dex */
public final /* synthetic */ class efx implements bgx {
    public static final efx b;
    private static final dfx descriptor;

    static {
        efx efxVar = new efx();
        b = efxVar;
        cuc cucVar = new cuc("me.hd.wauxv.hook.micromsg.core.protobuf.old.proto.TimeLineObjectProto.uq0Proto" /*
                                                                                                               * cnb.z(-
                                                                                                               * 286723426745130L)
                                                                                                               */,
                efxVar, 30);
        bjs.y(-286366944459562L, cucVar, false, 1);
        bjs.y(-286293930015530L, cucVar, false, 2);
        bjs.y(-286259570277162L, cucVar, false, 3);
        bjs.y(-286233800473386L, cucVar, false, 4);
        bjs.y(-286216620604202L, cucVar, false, 5);
        bjs.y(-287792873601834L, cucVar, false, 6);
        bjs.y(-287706974255914L, cucVar, false, 7);
        bjs.y(-287642549746474L, cucVar, false, 8);
        bjs.y(-287616779942698L, cucVar, false, 9);
        bjs.y(-287530880596778L, cucVar, false, 10);
        bjs.y(-288046276672298L, cucVar, false, 11);
        bjs.y(-288007621966634L, cucVar, false, 12);
        bjs.y(-287981852162858L, cucVar, false, 13);
        bjs.y(-287956082359082L, cucVar, false, 14);
        bjs.y(-287921722620714L, cucVar, false, 15);
        bjs.y(-287857298111274L, cucVar, false, 16);
        bjs.y(-287818643405610L, cucVar, false, 17);
        bjs.y(-287182988245802L, cucVar, false, 18);
        bjs.y(-287165808376618L, cucVar, false, 19);
        bjs.y(-287079909030698L, cucVar, false, 20);
        bjs.y(-287075614063402L, cucVar, false, 21);
        bjs.y(-287509405760298L, cucVar, false, 22);
        bjs.y(-287393441643306L, cucVar, false, 23);
        bjs.y(-287371966806826L, cucVar, false, 24);
        bjs.y(-287286067460906L, cucVar, false, 25);
        bjs.y(-310865437915946L, cucVar, false, 26);
        bjs.y(-310852553014058L, cucVar, false, 27);
        bjs.y(-310783833537322L, cucVar, false, 28);
        bjs.y(-310659279485738L, cucVar, false, 29);
        bjs.y(-311110251051818L, cucVar, false, 30);
        descriptor = cucVar;
    }

    @Override // me.hd.wauxv.obf.btd
    public final Object a(ajt ajtVar) {
        egx egxVar;
        dsy dsyVar;
        dte dteVar;
        Integer num;
        Long l;
        Integer num2;
        String str;
        String str2;
        String str3;
        Integer num3;
        Integer num4;
        Long l2;
        String str4;
        Integer num5;
        String str5;
        String str6;
        Long l3;
        eiz eizVar;
        boolean z;
        Integer num6;
        Long l4;
        int i;
        int i2;
        dfx dfxVar = descriptor;
        acm acmVarP = ajtVar.p(dfxVar);
        IHasGetValue[] bttVarArr = efz.a;
        acmVarP.getClass();
        List list = null;
        Integer num7 = null;
        ecv ecvVar = null;
        egx egxVar2 = null;
        String str7 = null;
        dvu dvuVar = null;
        String str8 = null;
        ehy ehyVar = null;
        Long l5 = null;
        eju ejuVar = null;
        dte dteVar2 = null;
        efj efjVar = null;
        Integer num8 = null;
        Long l6 = null;
        dsy dsyVar2 = null;
        String str9 = null;
        String str10 = null;
        Integer num9 = null;
        String str11 = null;
        Long l7 = null;
        Integer num10 = null;
        Integer num11 = null;
        String str12 = null;
        String str13 = null;
        String str14 = null;
        Integer num12 = null;
        Long l8 = null;
        Integer num13 = null;
        dte dteVar3 = null;
        eiz eizVar2 = null;
        int i3 = 0;
        boolean z2 = true;
        while (z2) {
            int i4 = i3;
            int iF = acmVarP.f(dfxVar);
            switch (iF) {
                case -1:
                    String str15 = str9;
                    i3 = i4;
                    ecv ecvVar2 = ecvVar;
                    Long l9 = l6;
                    egxVar = egxVar2;
                    dsyVar = dsyVar2;
                    dteVar = dteVar3;
                    l5 = l5;
                    num = num13;
                    l = l8;
                    num2 = num12;
                    str = str14;
                    str2 = str13;
                    str3 = str12;
                    num3 = num11;
                    num4 = num10;
                    l2 = l7;
                    str4 = str11;
                    num5 = num9;
                    str5 = str10;
                    str6 = str15;
                    l3 = l9;
                    ecvVar = ecvVar2;
                    eizVar = eizVar2;
                    z = false;
                    egxVar2 = egxVar;
                    dsyVar2 = dsyVar;
                    str9 = str6;
                    str10 = str5;
                    num9 = num5;
                    str11 = str4;
                    l7 = l2;
                    num10 = num4;
                    num11 = num3;
                    str12 = str3;
                    str13 = str2;
                    str14 = str;
                    num12 = num2;
                    l8 = l;
                    num13 = num;
                    dteVar3 = dteVar;
                    z2 = z;
                    eizVar2 = eizVar;
                    l6 = l3;
                    break;
                case 0:
                    num6 = num7;
                    String str16 = str9;
                    ecv ecvVar3 = ecvVar;
                    Long l10 = l6;
                    egxVar = egxVar2;
                    Long l11 = (Long) acmVarP.i(dfxVar, 0, bya.b, l10);
                    i3 = i4 | 1;
                    dsyVar = dsyVar2;
                    ecvVar = ecvVar3;
                    l5 = l5;
                    eizVar = eizVar2;
                    z = z2;
                    dteVar = dteVar3;
                    num = num13;
                    l = l8;
                    num2 = num12;
                    str = str14;
                    str2 = str13;
                    str3 = str12;
                    num3 = num11;
                    num4 = num10;
                    l2 = l7;
                    str4 = str11;
                    num5 = num9;
                    str5 = str10;
                    str6 = str16;
                    l3 = l11;
                    num7 = num6;
                    egxVar2 = egxVar;
                    dsyVar2 = dsyVar;
                    str9 = str6;
                    str10 = str5;
                    num9 = num5;
                    str11 = str4;
                    l7 = l2;
                    num10 = num4;
                    num11 = num3;
                    str12 = str3;
                    str13 = str2;
                    str14 = str;
                    num12 = num2;
                    l8 = l;
                    num13 = num;
                    dteVar3 = dteVar;
                    z2 = z;
                    eizVar2 = eizVar;
                    l6 = l3;
                    break;
                case 1:
                    ecv ecvVar4 = ecvVar;
                    String str17 = str9;
                    i3 = i4 | 2;
                    dsyVar = (dsy) acmVarP.i(dfxVar, 1, dsw.b, dsyVar2);
                    ecvVar = ecvVar4;
                    l5 = l5;
                    num7 = num7;
                    eizVar = eizVar2;
                    z = z2;
                    dteVar = dteVar3;
                    num = num13;
                    l = l8;
                    num2 = num12;
                    str = str14;
                    str2 = str13;
                    str3 = str12;
                    num3 = num11;
                    num4 = num10;
                    l2 = l7;
                    str4 = str11;
                    num5 = num9;
                    str5 = str10;
                    str6 = str17;
                    l3 = l6;
                    egxVar = egxVar2;
                    egxVar2 = egxVar;
                    dsyVar2 = dsyVar;
                    str9 = str6;
                    str10 = str5;
                    num9 = num5;
                    str11 = str4;
                    l7 = l2;
                    num10 = num4;
                    num11 = num3;
                    str12 = str3;
                    str13 = str2;
                    str14 = str;
                    num12 = num2;
                    l8 = l;
                    num13 = num;
                    dteVar3 = dteVar;
                    z2 = z;
                    eizVar2 = eizVar;
                    l6 = l3;
                    break;
                case 2:
                    num6 = num7;
                    String str18 = (String) acmVarP.i(dfxVar, 2, dnh.b, str9);
                    i3 = i4 | 4;
                    l3 = l6;
                    dsyVar = dsyVar2;
                    ecvVar = ecvVar;
                    l5 = l5;
                    egxVar = egxVar2;
                    eizVar = eizVar2;
                    z = z2;
                    dteVar = dteVar3;
                    num = num13;
                    l = l8;
                    num2 = num12;
                    str = str14;
                    str2 = str13;
                    str3 = str12;
                    num3 = num11;
                    num4 = num10;
                    l2 = l7;
                    str4 = str11;
                    num5 = num9;
                    str5 = str10;
                    str6 = str18;
                    num7 = num6;
                    egxVar2 = egxVar;
                    dsyVar2 = dsyVar;
                    str9 = str6;
                    str10 = str5;
                    num9 = num5;
                    str11 = str4;
                    l7 = l2;
                    num10 = num4;
                    num11 = num3;
                    str12 = str3;
                    str13 = str2;
                    str14 = str;
                    num12 = num2;
                    l8 = l;
                    num13 = num;
                    dteVar3 = dteVar;
                    z2 = z;
                    eizVar2 = eizVar;
                    l6 = l3;
                    break;
                case 3:
                    num6 = num7;
                    String str19 = (String) acmVarP.i(dfxVar, 3, dnh.b, str10);
                    i3 = i4 | 8;
                    l3 = l6;
                    str6 = str9;
                    ecvVar = ecvVar;
                    l5 = l5;
                    egxVar = egxVar2;
                    dsyVar = dsyVar2;
                    eizVar = eizVar2;
                    z = z2;
                    dteVar = dteVar3;
                    num = num13;
                    l = l8;
                    num2 = num12;
                    str = str14;
                    str2 = str13;
                    str3 = str12;
                    num3 = num11;
                    num4 = num10;
                    l2 = l7;
                    str4 = str11;
                    num5 = num9;
                    str5 = str19;
                    num7 = num6;
                    egxVar2 = egxVar;
                    dsyVar2 = dsyVar;
                    str9 = str6;
                    str10 = str5;
                    num9 = num5;
                    str11 = str4;
                    l7 = l2;
                    num10 = num4;
                    num11 = num3;
                    str12 = str3;
                    str13 = str2;
                    str14 = str;
                    num12 = num2;
                    l8 = l;
                    num13 = num;
                    dteVar3 = dteVar;
                    z2 = z;
                    eizVar2 = eizVar;
                    l6 = l3;
                    break;
                case 4:
                    num6 = num7;
                    Integer num14 = (Integer) acmVarP.i(dfxVar, 4, bqj.b, num9);
                    i3 = i4 | 16;
                    l3 = l6;
                    str5 = str10;
                    ecvVar = ecvVar;
                    l5 = l5;
                    egxVar = egxVar2;
                    str6 = str9;
                    eizVar = eizVar2;
                    dsyVar = dsyVar2;
                    z = z2;
                    dteVar = dteVar3;
                    num = num13;
                    l = l8;
                    num2 = num12;
                    str = str14;
                    str2 = str13;
                    str3 = str12;
                    num3 = num11;
                    num4 = num10;
                    l2 = l7;
                    str4 = str11;
                    num5 = num14;
                    num7 = num6;
                    egxVar2 = egxVar;
                    dsyVar2 = dsyVar;
                    str9 = str6;
                    str10 = str5;
                    num9 = num5;
                    str11 = str4;
                    l7 = l2;
                    num10 = num4;
                    num11 = num3;
                    str12 = str3;
                    str13 = str2;
                    str14 = str;
                    num12 = num2;
                    l8 = l;
                    num13 = num;
                    dteVar3 = dteVar;
                    z2 = z;
                    eizVar2 = eizVar;
                    l6 = l3;
                    break;
                case 5:
                    num6 = num7;
                    String str20 = (String) acmVarP.i(dfxVar, 5, dnh.b, str11);
                    i3 = i4 | 32;
                    l3 = l6;
                    num5 = num9;
                    ecvVar = ecvVar;
                    l5 = l5;
                    egxVar = egxVar2;
                    str5 = str10;
                    eizVar = eizVar2;
                    str6 = str9;
                    z = z2;
                    dsyVar = dsyVar2;
                    dteVar = dteVar3;
                    num = num13;
                    l = l8;
                    num2 = num12;
                    str = str14;
                    str2 = str13;
                    str3 = str12;
                    num3 = num11;
                    num4 = num10;
                    l2 = l7;
                    str4 = str20;
                    num7 = num6;
                    egxVar2 = egxVar;
                    dsyVar2 = dsyVar;
                    str9 = str6;
                    str10 = str5;
                    num9 = num5;
                    str11 = str4;
                    l7 = l2;
                    num10 = num4;
                    num11 = num3;
                    str12 = str3;
                    str13 = str2;
                    str14 = str;
                    num12 = num2;
                    l8 = l;
                    num13 = num;
                    dteVar3 = dteVar;
                    z2 = z;
                    eizVar2 = eizVar;
                    l6 = l3;
                    break;
                case 6:
                    num6 = num7;
                    Long l12 = (Long) acmVarP.i(dfxVar, 6, bya.b, l7);
                    i3 = i4 | 64;
                    l3 = l6;
                    str4 = str11;
                    ecvVar = ecvVar;
                    l5 = l5;
                    egxVar = egxVar2;
                    num5 = num9;
                    eizVar = eizVar2;
                    str5 = str10;
                    z = z2;
                    str6 = str9;
                    dteVar = dteVar3;
                    dsyVar = dsyVar2;
                    num = num13;
                    l = l8;
                    num2 = num12;
                    str = str14;
                    str2 = str13;
                    str3 = str12;
                    num3 = num11;
                    num4 = num10;
                    l2 = l12;
                    num7 = num6;
                    egxVar2 = egxVar;
                    dsyVar2 = dsyVar;
                    str9 = str6;
                    str10 = str5;
                    num9 = num5;
                    str11 = str4;
                    l7 = l2;
                    num10 = num4;
                    num11 = num3;
                    str12 = str3;
                    str13 = str2;
                    str14 = str;
                    num12 = num2;
                    l8 = l;
                    num13 = num;
                    dteVar3 = dteVar;
                    z2 = z;
                    eizVar2 = eizVar;
                    l6 = l3;
                    break;
                case 7:
                    num6 = num7;
                    Integer num15 = (Integer) acmVarP.i(dfxVar, 7, bqj.b, num10);
                    i3 = i4 | 128;
                    l3 = l6;
                    l2 = l7;
                    ecvVar = ecvVar;
                    l5 = l5;
                    egxVar = egxVar2;
                    str4 = str11;
                    eizVar = eizVar2;
                    num5 = num9;
                    z = z2;
                    str5 = str10;
                    dteVar = dteVar3;
                    str6 = str9;
                    num = num13;
                    dsyVar = dsyVar2;
                    l = l8;
                    num2 = num12;
                    str = str14;
                    str2 = str13;
                    str3 = str12;
                    num3 = num11;
                    num4 = num15;
                    num7 = num6;
                    egxVar2 = egxVar;
                    dsyVar2 = dsyVar;
                    str9 = str6;
                    str10 = str5;
                    num9 = num5;
                    str11 = str4;
                    l7 = l2;
                    num10 = num4;
                    num11 = num3;
                    str12 = str3;
                    str13 = str2;
                    str14 = str;
                    num12 = num2;
                    l8 = l;
                    num13 = num;
                    dteVar3 = dteVar;
                    z2 = z;
                    eizVar2 = eizVar;
                    l6 = l3;
                    break;
                case 8:
                    num6 = num7;
                    Integer num16 = (Integer) acmVarP.i(dfxVar, 8, bqj.b, num11);
                    i3 = i4 | 256;
                    l3 = l6;
                    num4 = num10;
                    ecvVar = ecvVar;
                    l5 = l5;
                    egxVar = egxVar2;
                    l2 = l7;
                    eizVar = eizVar2;
                    str4 = str11;
                    z = z2;
                    num5 = num9;
                    dteVar = dteVar3;
                    str5 = str10;
                    num = num13;
                    str6 = str9;
                    l = l8;
                    dsyVar = dsyVar2;
                    num2 = num12;
                    str = str14;
                    str2 = str13;
                    str3 = str12;
                    num3 = num16;
                    num7 = num6;
                    egxVar2 = egxVar;
                    dsyVar2 = dsyVar;
                    str9 = str6;
                    str10 = str5;
                    num9 = num5;
                    str11 = str4;
                    l7 = l2;
                    num10 = num4;
                    num11 = num3;
                    str12 = str3;
                    str13 = str2;
                    str14 = str;
                    num12 = num2;
                    l8 = l;
                    num13 = num;
                    dteVar3 = dteVar;
                    z2 = z;
                    eizVar2 = eizVar;
                    l6 = l3;
                    break;
                case 9:
                    num6 = num7;
                    String str21 = (String) acmVarP.i(dfxVar, 9, dnh.b, str12);
                    i3 = i4 | 512;
                    l3 = l6;
                    num3 = num11;
                    ecvVar = ecvVar;
                    l5 = l5;
                    egxVar = egxVar2;
                    num4 = num10;
                    eizVar = eizVar2;
                    l2 = l7;
                    z = z2;
                    str4 = str11;
                    dteVar = dteVar3;
                    num5 = num9;
                    num = num13;
                    str5 = str10;
                    l = l8;
                    str6 = str9;
                    num2 = num12;
                    dsyVar = dsyVar2;
                    str = str14;
                    str2 = str13;
                    str3 = str21;
                    num7 = num6;
                    egxVar2 = egxVar;
                    dsyVar2 = dsyVar;
                    str9 = str6;
                    str10 = str5;
                    num9 = num5;
                    str11 = str4;
                    l7 = l2;
                    num10 = num4;
                    num11 = num3;
                    str12 = str3;
                    str13 = str2;
                    str14 = str;
                    num12 = num2;
                    l8 = l;
                    num13 = num;
                    dteVar3 = dteVar;
                    z2 = z;
                    eizVar2 = eizVar;
                    l6 = l3;
                    break;
                case 10:
                    num6 = num7;
                    String str22 = (String) acmVarP.i(dfxVar, 10, dnh.b, str13);
                    i3 = i4 | 1024;
                    l3 = l6;
                    str3 = str12;
                    ecvVar = ecvVar;
                    l5 = l5;
                    egxVar = egxVar2;
                    num3 = num11;
                    eizVar = eizVar2;
                    num4 = num10;
                    z = z2;
                    l2 = l7;
                    dteVar = dteVar3;
                    str4 = str11;
                    num = num13;
                    num5 = num9;
                    l = l8;
                    str5 = str10;
                    num2 = num12;
                    str6 = str9;
                    str = str14;
                    str2 = str22;
                    dsyVar = dsyVar2;
                    num7 = num6;
                    egxVar2 = egxVar;
                    dsyVar2 = dsyVar;
                    str9 = str6;
                    str10 = str5;
                    num9 = num5;
                    str11 = str4;
                    l7 = l2;
                    num10 = num4;
                    num11 = num3;
                    str12 = str3;
                    str13 = str2;
                    str14 = str;
                    num12 = num2;
                    l8 = l;
                    num13 = num;
                    dteVar3 = dteVar;
                    z2 = z;
                    eizVar2 = eizVar;
                    l6 = l3;
                    break;
                case 11:
                    Integer num17 = num7;
                    String str23 = (String) acmVarP.i(dfxVar, 11, dnh.b, str14);
                    i3 = i4 | 2048;
                    l3 = l6;
                    str2 = str13;
                    ecvVar = ecvVar;
                    l5 = l5;
                    egxVar = egxVar2;
                    str3 = str12;
                    eizVar = eizVar2;
                    num3 = num11;
                    z = z2;
                    num4 = num10;
                    dteVar = dteVar3;
                    l2 = l7;
                    num = num13;
                    str4 = str11;
                    l = l8;
                    num5 = num9;
                    num2 = num12;
                    str = str23;
                    str5 = str10;
                    num7 = num17;
                    str6 = str9;
                    dsyVar = dsyVar2;
                    egxVar2 = egxVar;
                    dsyVar2 = dsyVar;
                    str9 = str6;
                    str10 = str5;
                    num9 = num5;
                    str11 = str4;
                    l7 = l2;
                    num10 = num4;
                    num11 = num3;
                    str12 = str3;
                    str13 = str2;
                    str14 = str;
                    num12 = num2;
                    l8 = l;
                    num13 = num;
                    dteVar3 = dteVar;
                    z2 = z;
                    eizVar2 = eizVar;
                    l6 = l3;
                    break;
                case 12:
                    Integer num18 = num7;
                    Integer num19 = (Integer) acmVarP.i(dfxVar, 12, bqj.b, num12);
                    i3 = i4 | 4096;
                    l3 = l6;
                    str = str14;
                    ecvVar = ecvVar;
                    l5 = l5;
                    egxVar = egxVar2;
                    str2 = str13;
                    eizVar = eizVar2;
                    str3 = str12;
                    z = z2;
                    num3 = num11;
                    dteVar = dteVar3;
                    num4 = num10;
                    num = num13;
                    l2 = l7;
                    l = l8;
                    num2 = num19;
                    str4 = str11;
                    num7 = num18;
                    num5 = num9;
                    str5 = str10;
                    str6 = str9;
                    dsyVar = dsyVar2;
                    egxVar2 = egxVar;
                    dsyVar2 = dsyVar;
                    str9 = str6;
                    str10 = str5;
                    num9 = num5;
                    str11 = str4;
                    l7 = l2;
                    num10 = num4;
                    num11 = num3;
                    str12 = str3;
                    str13 = str2;
                    str14 = str;
                    num12 = num2;
                    l8 = l;
                    num13 = num;
                    dteVar3 = dteVar;
                    z2 = z;
                    eizVar2 = eizVar;
                    l6 = l3;
                    break;
                case 13:
                    Integer num20 = num7;
                    Long l13 = (Long) acmVarP.i(dfxVar, 13, bya.b, l8);
                    i3 = i4 | 8192;
                    l3 = l6;
                    num2 = num12;
                    ecvVar = ecvVar;
                    l5 = l5;
                    egxVar = egxVar2;
                    str = str14;
                    eizVar = eizVar2;
                    str2 = str13;
                    z = z2;
                    str3 = str12;
                    dteVar = dteVar3;
                    num3 = num11;
                    num = num13;
                    l = l13;
                    num4 = num10;
                    num7 = num20;
                    l2 = l7;
                    str4 = str11;
                    num5 = num9;
                    str5 = str10;
                    str6 = str9;
                    dsyVar = dsyVar2;
                    egxVar2 = egxVar;
                    dsyVar2 = dsyVar;
                    str9 = str6;
                    str10 = str5;
                    num9 = num5;
                    str11 = str4;
                    l7 = l2;
                    num10 = num4;
                    num11 = num3;
                    str12 = str3;
                    str13 = str2;
                    str14 = str;
                    num12 = num2;
                    l8 = l;
                    num13 = num;
                    dteVar3 = dteVar;
                    z2 = z;
                    eizVar2 = eizVar;
                    l6 = l3;
                    break;
                case 14:
                    Integer num21 = num7;
                    Integer num22 = (Integer) acmVarP.i(dfxVar, 14, bqj.b, num13);
                    i3 = i4 | 16384;
                    l3 = l6;
                    l = l8;
                    eizVar = eizVar2;
                    l5 = l5;
                    egxVar = egxVar2;
                    num2 = num12;
                    z = z2;
                    str = str14;
                    dteVar = dteVar3;
                    num = num22;
                    str2 = str13;
                    num7 = num21;
                    str3 = str12;
                    num3 = num11;
                    num4 = num10;
                    l2 = l7;
                    str4 = str11;
                    num5 = num9;
                    str5 = str10;
                    str6 = str9;
                    dsyVar = dsyVar2;
                    egxVar2 = egxVar;
                    dsyVar2 = dsyVar;
                    str9 = str6;
                    str10 = str5;
                    num9 = num5;
                    str11 = str4;
                    l7 = l2;
                    num10 = num4;
                    num11 = num3;
                    str12 = str3;
                    str13 = str2;
                    str14 = str;
                    num12 = num2;
                    l8 = l;
                    num13 = num;
                    dteVar3 = dteVar;
                    z2 = z;
                    eizVar2 = eizVar;
                    l6 = l3;
                    break;
                case 15:
                    Integer num23 = num7;
                    dte dteVar4 = (dte) acmVarP.i(dfxVar, 15, dtc.b, dteVar3);
                    i3 = i4 | 32768;
                    l3 = l6;
                    num = num13;
                    eizVar = eizVar2;
                    l5 = l5;
                    egxVar = egxVar2;
                    l = l8;
                    z = z2;
                    dteVar = dteVar4;
                    num2 = num12;
                    num7 = num23;
                    str = str14;
                    str2 = str13;
                    str3 = str12;
                    num3 = num11;
                    num4 = num10;
                    l2 = l7;
                    str4 = str11;
                    num5 = num9;
                    str5 = str10;
                    str6 = str9;
                    dsyVar = dsyVar2;
                    egxVar2 = egxVar;
                    dsyVar2 = dsyVar;
                    str9 = str6;
                    str10 = str5;
                    num9 = num5;
                    str11 = str4;
                    l7 = l2;
                    num10 = num4;
                    num11 = num3;
                    str12 = str3;
                    str13 = str2;
                    str14 = str;
                    num12 = num2;
                    l8 = l;
                    num13 = num;
                    dteVar3 = dteVar;
                    z2 = z;
                    eizVar2 = eizVar;
                    l6 = l3;
                    break;
                case 16:
                    i3 = i4 | 65536;
                    eizVar = (eiz) acmVarP.i(dfxVar, 16, eix.b, eizVar2);
                    l3 = l6;
                    z = z2;
                    l5 = l5;
                    num7 = num7;
                    egxVar = egxVar2;
                    dteVar = dteVar3;
                    num = num13;
                    l = l8;
                    num2 = num12;
                    str = str14;
                    str2 = str13;
                    str3 = str12;
                    num3 = num11;
                    num4 = num10;
                    l2 = l7;
                    str4 = str11;
                    num5 = num9;
                    str5 = str10;
                    str6 = str9;
                    dsyVar = dsyVar2;
                    egxVar2 = egxVar;
                    dsyVar2 = dsyVar;
                    str9 = str6;
                    str10 = str5;
                    num9 = num5;
                    str11 = str4;
                    l7 = l2;
                    num10 = num4;
                    num11 = num3;
                    str12 = str3;
                    str13 = str2;
                    str14 = str;
                    num12 = num2;
                    l8 = l;
                    num13 = num;
                    dteVar3 = dteVar;
                    z2 = z;
                    eizVar2 = eizVar;
                    l6 = l3;
                    break;
                case 17:
                    Integer num24 = num7;
                    i3 = i4 | 131072;
                    l5 = (Long) acmVarP.i(dfxVar, 17, bya.b, l5);
                    l3 = l6;
                    eizVar = eizVar2;
                    num7 = num24;
                    egxVar = egxVar2;
                    z = z2;
                    dteVar = dteVar3;
                    num = num13;
                    l = l8;
                    num2 = num12;
                    str = str14;
                    str2 = str13;
                    str3 = str12;
                    num3 = num11;
                    num4 = num10;
                    l2 = l7;
                    str4 = str11;
                    num5 = num9;
                    str5 = str10;
                    str6 = str9;
                    dsyVar = dsyVar2;
                    egxVar2 = egxVar;
                    dsyVar2 = dsyVar;
                    str9 = str6;
                    str10 = str5;
                    num9 = num5;
                    str11 = str4;
                    l7 = l2;
                    num10 = num4;
                    num11 = num3;
                    str12 = str3;
                    str13 = str2;
                    str14 = str;
                    num12 = num2;
                    l8 = l;
                    num13 = num;
                    dteVar3 = dteVar;
                    z2 = z;
                    eizVar2 = eizVar;
                    l6 = l3;
                    break;
                case 18:
                    l4 = l5;
                    i = i4 | 262144;
                    ejuVar = (eju) acmVarP.i(dfxVar, 18, ejs.b, ejuVar);
                    i3 = i;
                    l3 = l6;
                    eizVar = eizVar2;
                    l5 = l4;
                    egxVar = egxVar2;
                    z = z2;
                    dteVar = dteVar3;
                    num = num13;
                    l = l8;
                    num2 = num12;
                    str = str14;
                    str2 = str13;
                    str3 = str12;
                    num3 = num11;
                    num4 = num10;
                    l2 = l7;
                    str4 = str11;
                    num5 = num9;
                    str5 = str10;
                    str6 = str9;
                    dsyVar = dsyVar2;
                    egxVar2 = egxVar;
                    dsyVar2 = dsyVar;
                    str9 = str6;
                    str10 = str5;
                    num9 = num5;
                    str11 = str4;
                    l7 = l2;
                    num10 = num4;
                    num11 = num3;
                    str12 = str3;
                    str13 = str2;
                    str14 = str;
                    num12 = num2;
                    l8 = l;
                    num13 = num;
                    dteVar3 = dteVar;
                    z2 = z;
                    eizVar2 = eizVar;
                    l6 = l3;
                    break;
                case 19:
                    l4 = l5;
                    dte dteVar5 = (dte) acmVarP.i(dfxVar, 19, dtc.b, dteVar2);
                    i = i4 | Opcodes.ASM8;
                    dteVar2 = dteVar5;
                    i3 = i;
                    l3 = l6;
                    eizVar = eizVar2;
                    l5 = l4;
                    egxVar = egxVar2;
                    z = z2;
                    dteVar = dteVar3;
                    num = num13;
                    l = l8;
                    num2 = num12;
                    str = str14;
                    str2 = str13;
                    str3 = str12;
                    num3 = num11;
                    num4 = num10;
                    l2 = l7;
                    str4 = str11;
                    num5 = num9;
                    str5 = str10;
                    str6 = str9;
                    dsyVar = dsyVar2;
                    egxVar2 = egxVar;
                    dsyVar2 = dsyVar;
                    str9 = str6;
                    str10 = str5;
                    num9 = num5;
                    str11 = str4;
                    l7 = l2;
                    num10 = num4;
                    num11 = num3;
                    str12 = str3;
                    str13 = str2;
                    str14 = str;
                    num12 = num2;
                    l8 = l;
                    num13 = num;
                    dteVar3 = dteVar;
                    z2 = z;
                    eizVar2 = eizVar;
                    l6 = l3;
                    break;
                case 20:
                    l4 = l5;
                    i = i4 | 1048576;
                    efjVar = (efj) acmVarP.i(dfxVar, 20, efh.b, efjVar);
                    i3 = i;
                    l3 = l6;
                    eizVar = eizVar2;
                    l5 = l4;
                    egxVar = egxVar2;
                    z = z2;
                    dteVar = dteVar3;
                    num = num13;
                    l = l8;
                    num2 = num12;
                    str = str14;
                    str2 = str13;
                    str3 = str12;
                    num3 = num11;
                    num4 = num10;
                    l2 = l7;
                    str4 = str11;
                    num5 = num9;
                    str5 = str10;
                    str6 = str9;
                    dsyVar = dsyVar2;
                    egxVar2 = egxVar;
                    dsyVar2 = dsyVar;
                    str9 = str6;
                    str10 = str5;
                    num9 = num5;
                    str11 = str4;
                    l7 = l2;
                    num10 = num4;
                    num11 = num3;
                    str12 = str3;
                    str13 = str2;
                    str14 = str;
                    num12 = num2;
                    l8 = l;
                    num13 = num;
                    dteVar3 = dteVar;
                    z2 = z;
                    eizVar2 = eizVar;
                    l6 = l3;
                    break;
                case 21:
                    l4 = l5;
                    i = i4 | 2097152;
                    num8 = (Integer) acmVarP.i(dfxVar, 21, bqj.b, num8);
                    i3 = i;
                    l3 = l6;
                    eizVar = eizVar2;
                    l5 = l4;
                    egxVar = egxVar2;
                    z = z2;
                    dteVar = dteVar3;
                    num = num13;
                    l = l8;
                    num2 = num12;
                    str = str14;
                    str2 = str13;
                    str3 = str12;
                    num3 = num11;
                    num4 = num10;
                    l2 = l7;
                    str4 = str11;
                    num5 = num9;
                    str5 = str10;
                    str6 = str9;
                    dsyVar = dsyVar2;
                    egxVar2 = egxVar;
                    dsyVar2 = dsyVar;
                    str9 = str6;
                    str10 = str5;
                    num9 = num5;
                    str11 = str4;
                    l7 = l2;
                    num10 = num4;
                    num11 = num3;
                    str12 = str3;
                    str13 = str2;
                    str14 = str;
                    num12 = num2;
                    l8 = l;
                    num13 = num;
                    dteVar3 = dteVar;
                    z2 = z;
                    eizVar2 = eizVar;
                    l6 = l3;
                    break;
                case 22:
                    l4 = l5;
                    list = (List) acmVarP.i(dfxVar, 22, (btd) bttVarArr[22].getValue(), list);
                    i2 = 4194304;
                    i3 = i4 | i2;
                    l3 = l6;
                    eizVar = eizVar2;
                    l5 = l4;
                    egxVar = egxVar2;
                    z = z2;
                    dteVar = dteVar3;
                    num = num13;
                    l = l8;
                    num2 = num12;
                    str = str14;
                    str2 = str13;
                    str3 = str12;
                    num3 = num11;
                    num4 = num10;
                    l2 = l7;
                    str4 = str11;
                    num5 = num9;
                    str5 = str10;
                    str6 = str9;
                    dsyVar = dsyVar2;
                    egxVar2 = egxVar;
                    dsyVar2 = dsyVar;
                    str9 = str6;
                    str10 = str5;
                    num9 = num5;
                    str11 = str4;
                    l7 = l2;
                    num10 = num4;
                    num11 = num3;
                    str12 = str3;
                    str13 = str2;
                    str14 = str;
                    num12 = num2;
                    l8 = l;
                    num13 = num;
                    dteVar3 = dteVar;
                    z2 = z;
                    eizVar2 = eizVar;
                    l6 = l3;
                    break;
                case 23:
                    l4 = l5;
                    str7 = (String) acmVarP.i(dfxVar, 23, dnh.b, str7);
                    i2 = 8388608;
                    i3 = i4 | i2;
                    l3 = l6;
                    eizVar = eizVar2;
                    l5 = l4;
                    egxVar = egxVar2;
                    z = z2;
                    dteVar = dteVar3;
                    num = num13;
                    l = l8;
                    num2 = num12;
                    str = str14;
                    str2 = str13;
                    str3 = str12;
                    num3 = num11;
                    num4 = num10;
                    l2 = l7;
                    str4 = str11;
                    num5 = num9;
                    str5 = str10;
                    str6 = str9;
                    dsyVar = dsyVar2;
                    egxVar2 = egxVar;
                    dsyVar2 = dsyVar;
                    str9 = str6;
                    str10 = str5;
                    num9 = num5;
                    str11 = str4;
                    l7 = l2;
                    num10 = num4;
                    num11 = num3;
                    str12 = str3;
                    str13 = str2;
                    str14 = str;
                    num12 = num2;
                    l8 = l;
                    num13 = num;
                    dteVar3 = dteVar;
                    z2 = z;
                    eizVar2 = eizVar;
                    l6 = l3;
                    break;
                case 24:
                    l4 = l5;
                    dvuVar = (dvu) acmVarP.i(dfxVar, 24, dvs.b, dvuVar);
                    i2 = Http2Connection.OKHTTP_CLIENT_WINDOW_SIZE;
                    i3 = i4 | i2;
                    l3 = l6;
                    eizVar = eizVar2;
                    l5 = l4;
                    egxVar = egxVar2;
                    z = z2;
                    dteVar = dteVar3;
                    num = num13;
                    l = l8;
                    num2 = num12;
                    str = str14;
                    str2 = str13;
                    str3 = str12;
                    num3 = num11;
                    num4 = num10;
                    l2 = l7;
                    str4 = str11;
                    num5 = num9;
                    str5 = str10;
                    str6 = str9;
                    dsyVar = dsyVar2;
                    egxVar2 = egxVar;
                    dsyVar2 = dsyVar;
                    str9 = str6;
                    str10 = str5;
                    num9 = num5;
                    str11 = str4;
                    l7 = l2;
                    num10 = num4;
                    num11 = num3;
                    str12 = str3;
                    str13 = str2;
                    str14 = str;
                    num12 = num2;
                    l8 = l;
                    num13 = num;
                    dteVar3 = dteVar;
                    z2 = z;
                    eizVar2 = eizVar;
                    l6 = l3;
                    break;
                case 25:
                    l4 = l5;
                    egxVar2 = (egx) acmVarP.i(dfxVar, 25, egv.b, egxVar2);
                    i2 = 33554432;
                    i3 = i4 | i2;
                    l3 = l6;
                    eizVar = eizVar2;
                    l5 = l4;
                    egxVar = egxVar2;
                    z = z2;
                    dteVar = dteVar3;
                    num = num13;
                    l = l8;
                    num2 = num12;
                    str = str14;
                    str2 = str13;
                    str3 = str12;
                    num3 = num11;
                    num4 = num10;
                    l2 = l7;
                    str4 = str11;
                    num5 = num9;
                    str5 = str10;
                    str6 = str9;
                    dsyVar = dsyVar2;
                    egxVar2 = egxVar;
                    dsyVar2 = dsyVar;
                    str9 = str6;
                    str10 = str5;
                    num9 = num5;
                    str11 = str4;
                    l7 = l2;
                    num10 = num4;
                    num11 = num3;
                    str12 = str3;
                    str13 = str2;
                    str14 = str;
                    num12 = num2;
                    l8 = l;
                    num13 = num;
                    dteVar3 = dteVar;
                    z2 = z;
                    eizVar2 = eizVar;
                    l6 = l3;
                    break;
                case 26:
                    l4 = l5;
                    ecvVar = (ecv) acmVarP.i(dfxVar, 26, ect.b, ecvVar);
                    i2 = 67108864;
                    i3 = i4 | i2;
                    l3 = l6;
                    eizVar = eizVar2;
                    l5 = l4;
                    egxVar = egxVar2;
                    z = z2;
                    dteVar = dteVar3;
                    num = num13;
                    l = l8;
                    num2 = num12;
                    str = str14;
                    str2 = str13;
                    str3 = str12;
                    num3 = num11;
                    num4 = num10;
                    l2 = l7;
                    str4 = str11;
                    num5 = num9;
                    str5 = str10;
                    str6 = str9;
                    dsyVar = dsyVar2;
                    egxVar2 = egxVar;
                    dsyVar2 = dsyVar;
                    str9 = str6;
                    str10 = str5;
                    num9 = num5;
                    str11 = str4;
                    l7 = l2;
                    num10 = num4;
                    num11 = num3;
                    str12 = str3;
                    str13 = str2;
                    str14 = str;
                    num12 = num2;
                    l8 = l;
                    num13 = num;
                    dteVar3 = dteVar;
                    z2 = z;
                    eizVar2 = eizVar;
                    l6 = l3;
                    break;
                case 27:
                    l4 = l5;
                    num7 = (Integer) acmVarP.i(dfxVar, 27, bqj.b, num7);
                    i2 = 134217728;
                    i3 = i4 | i2;
                    l3 = l6;
                    eizVar = eizVar2;
                    l5 = l4;
                    egxVar = egxVar2;
                    z = z2;
                    dteVar = dteVar3;
                    num = num13;
                    l = l8;
                    num2 = num12;
                    str = str14;
                    str2 = str13;
                    str3 = str12;
                    num3 = num11;
                    num4 = num10;
                    l2 = l7;
                    str4 = str11;
                    num5 = num9;
                    str5 = str10;
                    str6 = str9;
                    dsyVar = dsyVar2;
                    egxVar2 = egxVar;
                    dsyVar2 = dsyVar;
                    str9 = str6;
                    str10 = str5;
                    num9 = num5;
                    str11 = str4;
                    l7 = l2;
                    num10 = num4;
                    num11 = num3;
                    str12 = str3;
                    str13 = str2;
                    str14 = str;
                    num12 = num2;
                    l8 = l;
                    num13 = num;
                    dteVar3 = dteVar;
                    z2 = z;
                    eizVar2 = eizVar;
                    l6 = l3;
                    break;
                case 28:
                    l4 = l5;
                    str8 = (String) acmVarP.i(dfxVar, 28, dnh.b, str8);
                    i2 = 268435456;
                    i3 = i4 | i2;
                    l3 = l6;
                    eizVar = eizVar2;
                    l5 = l4;
                    egxVar = egxVar2;
                    z = z2;
                    dteVar = dteVar3;
                    num = num13;
                    l = l8;
                    num2 = num12;
                    str = str14;
                    str2 = str13;
                    str3 = str12;
                    num3 = num11;
                    num4 = num10;
                    l2 = l7;
                    str4 = str11;
                    num5 = num9;
                    str5 = str10;
                    str6 = str9;
                    dsyVar = dsyVar2;
                    egxVar2 = egxVar;
                    dsyVar2 = dsyVar;
                    str9 = str6;
                    str10 = str5;
                    num9 = num5;
                    str11 = str4;
                    l7 = l2;
                    num10 = num4;
                    num11 = num3;
                    str12 = str3;
                    str13 = str2;
                    str14 = str;
                    num12 = num2;
                    l8 = l;
                    num13 = num;
                    dteVar3 = dteVar;
                    z2 = z;
                    eizVar2 = eizVar;
                    l6 = l3;
                    break;
                case 29:
                    l4 = l5;
                    ehyVar = (ehy) acmVarP.i(dfxVar, 29, ehw.b, ehyVar);
                    i2 = 536870912;
                    i3 = i4 | i2;
                    l3 = l6;
                    eizVar = eizVar2;
                    l5 = l4;
                    egxVar = egxVar2;
                    z = z2;
                    dteVar = dteVar3;
                    num = num13;
                    l = l8;
                    num2 = num12;
                    str = str14;
                    str2 = str13;
                    str3 = str12;
                    num3 = num11;
                    num4 = num10;
                    l2 = l7;
                    str4 = str11;
                    num5 = num9;
                    str5 = str10;
                    str6 = str9;
                    dsyVar = dsyVar2;
                    egxVar2 = egxVar;
                    dsyVar2 = dsyVar;
                    str9 = str6;
                    str10 = str5;
                    num9 = num5;
                    str11 = str4;
                    l7 = l2;
                    num10 = num4;
                    num11 = num3;
                    str12 = str3;
                    str13 = str2;
                    str14 = str;
                    num12 = num2;
                    l8 = l;
                    num13 = num;
                    dteVar3 = dteVar;
                    z2 = z;
                    eizVar2 = eizVar;
                    l6 = l3;
                    break;
                default:
                    throw new bsd(iF);
            }
        }
        ecv ecvVar5 = ecvVar;
        Long l14 = l5;
        Long l15 = l6;
        dsy dsyVar3 = dsyVar2;
        String str24 = str9;
        egx egxVar3 = egxVar2;
        acmVarP._bp(dfxVar);
        return new efz(i3, l15, dsyVar3, str24, str10, num9, str11, l7, num10, num11, str12, str13, str14, num12, l8,
                num13, dteVar3, eizVar2, l14, ejuVar, dteVar2, efjVar, num8, list, str7, dvuVar, egxVar3, ecvVar5, num7,
                str8, ehyVar);
    }

    @Override // me.hd.wauxv.obf.btd
    public final void c(avt avtVar, Object obj) {
        efz efzVar = (efz) obj;
        dfx dfxVar = descriptor;
        acn acnVarO = avtVar.o(dfxVar);
        IHasGetValue[] bttVarArr = efz.a;
        bya byaVar = bya.b;
        acnVarO.m(dfxVar, 0, byaVar, efzVar.b);
        acnVarO.m(dfxVar, 1, dsw.b, efzVar.c);
        dnh dnhVar = dnh.b;
        acnVarO.m(dfxVar, 2, dnhVar, efzVar.d);
        acnVarO.m(dfxVar, 3, dnhVar, efzVar.e);
        bqj bqjVar = bqj.b;
        acnVarO.m(dfxVar, 4, bqjVar, efzVar.f);
        acnVarO.m(dfxVar, 5, dnhVar, efzVar.g);
        acnVarO.m(dfxVar, 6, byaVar, efzVar.h);
        acnVarO.m(dfxVar, 7, bqjVar, efzVar.i);
        acnVarO.m(dfxVar, 8, bqjVar, efzVar.j);
        acnVarO.m(dfxVar, 9, dnhVar, efzVar.k);
        acnVarO.m(dfxVar, 10, dnhVar, efzVar.l);
        acnVarO.m(dfxVar, 11, dnhVar, efzVar.m);
        acnVarO.m(dfxVar, 12, bqjVar, efzVar.n);
        acnVarO.m(dfxVar, 13, byaVar, efzVar.o);
        acnVarO.m(dfxVar, 14, bqjVar, efzVar.p);
        dtc dtcVar = dtc.b;
        acnVarO.m(dfxVar, 15, dtcVar, efzVar.q);
        acnVarO.m(dfxVar, 16, eix.b, efzVar.r);
        acnVarO.m(dfxVar, 17, byaVar, efzVar.s);
        acnVarO.m(dfxVar, 18, ejs.b, efzVar.t);
        acnVarO.m(dfxVar, 19, dtcVar, efzVar.u);
        acnVarO.m(dfxVar, 20, efh.b, efzVar.v);
        acnVarO.m(dfxVar, 21, bqjVar, efzVar.w);
        acnVarO.m(dfxVar, 22, (btd) bttVarArr[22].getValue(), efzVar.x);
        acnVarO.m(dfxVar, 23, dnhVar, efzVar.y);
        acnVarO.m(dfxVar, 24, dvs.b, efzVar.z);
        acnVarO.m(dfxVar, 25, egv.b, efzVar.aa);
        acnVarO.m(dfxVar, 26, ect.b, efzVar.ab);
        acnVarO.m(dfxVar, 27, bqjVar, efzVar.ac);
        acnVarO.m(dfxVar, 28, dnhVar, efzVar.ad);
        acnVarO.m(dfxVar, 29, ehw.b, efzVar.ae);
        acnVarO.a(dfxVar);
    }

    @Override // me.hd.wauxv.obf.bgx
    public final btd[] d() {
        IHasGetValue[] bttVarArr = efz.a;
        bya byaVar = bya.b;
        btd btdVarT = aye.t(byaVar);
        btd btdVarT2 = aye.t(dsw.b);
        dnh dnhVar = dnh.b;
        btd btdVarT3 = aye.t(dnhVar);
        btd btdVarT4 = aye.t(dnhVar);
        bqj bqjVar = bqj.b;
        btd btdVarT5 = aye.t(bqjVar);
        btd btdVarT6 = aye.t(dnhVar);
        btd btdVarT7 = aye.t(byaVar);
        btd btdVarT8 = aye.t(bqjVar);
        btd btdVarT9 = aye.t(bqjVar);
        btd btdVarT10 = aye.t(dnhVar);
        btd btdVarT11 = aye.t(dnhVar);
        btd btdVarT12 = aye.t(dnhVar);
        btd btdVarT13 = aye.t(bqjVar);
        btd btdVarT14 = aye.t(byaVar);
        btd btdVarT15 = aye.t(bqjVar);
        dtc dtcVar = dtc.b;
        return new btd[] { btdVarT, btdVarT2, btdVarT3, btdVarT4, btdVarT5, btdVarT6, btdVarT7, btdVarT8, btdVarT9,
                btdVarT10, btdVarT11, btdVarT12, btdVarT13, btdVarT14, btdVarT15, aye.t(dtcVar), aye.t(eix.b),
                aye.t(byaVar), aye.t(ejs.b), aye.t(dtcVar), aye.t(efh.b), aye.t(bqjVar),
                aye.t((btd) bttVarArr[22].getValue()), aye.t(dnhVar), aye.t(dvs.b), aye.t(egv.b), aye.t(ect.b),
                aye.t(bqjVar), aye.t(dnhVar), aye.t(ehw.b) };
    }

    @Override // me.hd.wauxv.obf.btd
    public final dfx getDescriptor() {
        return descriptor;
    }
}
