package me.hd.wauxv.obf;

/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
/* JADX INFO: compiled from: r8-map-id-b9de5da7d0413052737328a4e696e1bcc3145db8f6a41e1e318485e124198cd6 */
/* JADX INFO: loaded from: classes.dex */
public final class ekk {
    public static final ekk a;
    public static final ekk aa;
    public static final ekk ab;
    public static final ekk ac;
    public static final ekk ad;
    public static final ekk ae;
    public static final ekk af;
    public static final ekk ag;
    public static final ekk ah;
    public static final ekk ai;
    public static final ekk aj;
    public static final ekk ak;
    public static final ekk al;
    public static final ekk am;
    public static final ekk an;
    public static final ekk ao;
    public static final ekk ap;
    public static final ekk aq;
    public static final ekk ar;
    public static final ekk as;
    public static final ekk at;
    public static final ekk au;
    public static final ekk av;
    public static final ekk aw;
    public static final ekk ax;
    public static final ekk ay;
    public static final ekk az;
    public static final ekk b;
    public static final ekk ba;
    public static final ekk bb;
    public static final ekk bc;
    public static final ekk bd;
    public static final ekk be;
    public static final ekk bf;
    public static final ekk bg;
    public static final ekk bh;
    public static final ekk bi;
    public static final ekk bj;
    public static final ekk bk;
    public static final ekk bl;
    public static final ekk bm;
    public static final ekk bn;
    public static final ekk bo;
    public static final ekk bp;
    public static final ekk bq;
    public static final ekk br;
    public static final ekk bs;
    public static final ekk bt;
    public static final ekk bu;
    public static final ekk bv;
    public static final ekk bw;
    public static final ekk bx;
    public static final ekk by;
    public static final ekk bz;
    public static final ekk c;
    public static final ekk ca;
    public static final ekk cb;
    public static final ekk cc;
    public static final ekk cd;
    public static final ekk ce;
    public static final ekk cf;
    public static final ekk cg;
    public static final ekk ch;
    public static final ekk ci;
    public static final ekk cj;
    public static final ekk ck;
    public static final ekk cl;
    public static final ekk cm;
    public static final ekk cn;
    public static final ekk co;
    public static final /* synthetic */ ekk[] cp;
    public static final ekk d;
    public static final ekk e;
    public static final ekk f;
    public static final ekk g;
    public static final ekk h;
    public static final ekk i;
    public static final ekk j;
    public static final ekk k;
    public static final ekk l;
    public static final ekk m;
    public static final ekk n;
    public static final ekk o;
    public static final ekk p;
    public static final ekk q;
    public static final ekk r;
    public static final ekk s;
    public static final ekk t;
    public static final ekk u;
    public static final ekk v;
    public static final ekk w;
    public static final ekk x;
    public static final ekk y;
    public static final ekk z;

    static {
        ekk ekkVar = new ekk("WHITESPACE", 0);
        a = ekkVar;
        ekk ekkVar2 = new ekk("NEWLINE", 1);
        b = ekkVar2;
        ekk ekkVar3 = new ekk("UNKNOWN", 2);
        c = ekkVar3;
        ekk ekkVar4 = new ekk("EOF", 3);
        d = ekkVar4;
        ekk ekkVar5 = new ekk("LONG_COMMENT_COMPLETE", 4);
        e = ekkVar5;
        ekk ekkVar6 = new ekk("LONG_COMMENT_INCOMPLETE", 5);
        f = ekkVar6;
        ekk ekkVar7 = new ekk("LINE_COMMENT", 6);
        g = ekkVar7;
        ekk ekkVar8 = new ekk("DIV", 7);
        h = ekkVar8;
        ekk ekkVar9 = new ekk("MULT", 8);
        i = ekkVar9;
        ekk ekkVar10 = new ekk("IDENTIFIER", 9);
        j = ekkVar10;
        ekk ekkVar11 = new ekk("INTEGER_LITERAL", 10);
        k = ekkVar11;
        ekk ekkVar12 = new ekk("DOT", 11);
        l = ekkVar12;
        ekk ekkVar13 = new ekk("MINUS", 12);
        m = ekkVar13;
        ekk ekkVar14 = new ekk("STRING", 13);
        n = ekkVar14;
        ekk ekkVar15 = new ekk("CHARACTER_LITERAL", 14);
        o = ekkVar15;
        ekk ekkVar16 = new ekk("LPAREN", 15);
        p = ekkVar16;
        ekk ekkVar17 = new ekk("RPAREN", 16);
        q = ekkVar17;
        ekk ekkVar18 = new ekk("LBRACE", 17);
        r = ekkVar18;
        ekk ekkVar19 = new ekk("RBRACE", 18);
        s = ekkVar19;
        ekk ekkVar20 = new ekk("LBRACK", 19);
        t = ekkVar20;
        ekk ekkVar21 = new ekk("RBRACK", 20);
        u = ekkVar21;
        ekk ekkVar22 = new ekk("SEMICOLON", 21);
        v = ekkVar22;
        ekk ekkVar23 = new ekk("COMMA", 22);
        w = ekkVar23;
        ekk ekkVar24 = new ekk("EQ", 23);
        x = ekkVar24;
        ekk ekkVar25 = new ekk("GT", 24);
        y = ekkVar25;
        ekk ekkVar26 = new ekk("LT", 25);
        z = ekkVar26;
        ekk ekkVar27 = new ekk("NOT", 26);
        aa = ekkVar27;
        ekk ekkVar28 = new ekk("COMP", 27);
        ab = ekkVar28;
        ekk ekkVar29 = new ekk("QUESTION", 28);
        ac = ekkVar29;
        ekk ekkVar30 = new ekk("COLON", 29);
        ad = ekkVar30;
        ekk ekkVar31 = new ekk("AND", 30);
        ae = ekkVar31;
        ekk ekkVar32 = new ekk("OR", 31);
        af = ekkVar32;
        ekk ekkVar33 = new ekk("PLUS", 32);
        ag = ekkVar33;
        ekk ekkVar34 = new ekk("XOR", 33);
        ah = ekkVar34;
        ekk ekkVar35 = new ekk("MOD", 34);
        ai = ekkVar35;
        ekk ekkVar36 = new ekk("FLOATING_POINT_LITERAL", 35);
        aj = ekkVar36;
        ekk ekkVar37 = new ekk("VAR", 36);
        ak = ekkVar37;
        ekk ekkVar38 = new ekk("SEALED", 37);
        al = ekkVar38;
        ekk ekkVar39 = new ekk("PERMITS", 38);
        am = ekkVar39;
        ekk ekkVar40 = new ekk("ABSTRACT", 39);
        an = ekkVar40;
        ekk ekkVar41 = new ekk("ASSERT", 40);
        ao = ekkVar41;
        ekk ekkVar42 = new ekk("BOOLEAN", 41);
        ap = ekkVar42;
        ekk ekkVar43 = new ekk("BYTE", 42);
        aq = ekkVar43;
        ekk ekkVar44 = new ekk("CHAR", 43);
        ar = ekkVar44;
        ekk ekkVar45 = new ekk("CLASS", 44);
        as = ekkVar45;
        ekk ekkVar46 = new ekk("DO", 45);
        at = ekkVar46;
        ekk ekkVar47 = new ekk("DOUBLE", 46);
        au = ekkVar47;
        ekk ekkVar48 = new ekk("FINAL", 47);
        av = ekkVar48;
        ekk ekkVar49 = new ekk("FLOAT", 48);
        aw = ekkVar49;
        ekk ekkVar50 = new ekk("FOR", 49);
        ax = ekkVar50;
        ekk ekkVar51 = new ekk("IF", 50);
        ay = ekkVar51;
        ekk ekkVar52 = new ekk("INT", 51);
        az = ekkVar52;
        ekk ekkVar53 = new ekk("LONG", 52);
        ba = ekkVar53;
        ekk ekkVar54 = new ekk("NEW", 53);
        bb = ekkVar54;
        ekk ekkVar55 = new ekk("PUBLIC", 54);
        bc = ekkVar55;
        ekk ekkVar56 = new ekk("PRIVATE", 55);
        bd = ekkVar56;
        ekk ekkVar57 = new ekk("PROTECTED", 56);
        be = ekkVar57;
        ekk ekkVar58 = new ekk("PACKAGE", 57);
        bf = ekkVar58;
        ekk ekkVar59 = new ekk("RETURN", 58);
        bg = ekkVar59;
        ekk ekkVar60 = new ekk("STATIC", 59);
        bh = ekkVar60;
        ekk ekkVar61 = new ekk("SHORT", 60);
        bi = ekkVar61;
        ekk ekkVar62 = new ekk("SUPER", 61);
        bj = ekkVar62;
        ekk ekkVar63 = new ekk("SWITCH", 62);
        bk = ekkVar63;
        ekk ekkVar64 = new ekk("ELSE", 63);
        bl = ekkVar64;
        ekk ekkVar65 = new ekk("VOLATILE", 64);
        bm = ekkVar65;
        ekk ekkVar66 = new ekk("SYNCHRONIZED", 65);
        bn = ekkVar66;
        ekk ekkVar67 = new ekk("STRICTFP", 66);
        bo = ekkVar67;
        ekk ekkVar68 = new ekk("GOTO", 67);
        bp = ekkVar68;
        ekk ekkVar69 = new ekk("CONTINUE", 68);
        bq = ekkVar69;
        ekk ekkVar70 = new ekk("BREAK", 69);
        br = ekkVar70;
        ekk ekkVar71 = new ekk("TRANSIENT", 70);
        bs = ekkVar71;
        ekk ekkVar72 = new ekk("VOID", 71);
        bt = ekkVar72;
        ekk ekkVar73 = new ekk("TRY", 72);
        bu = ekkVar73;
        ekk ekkVar74 = new ekk("CATCH", 73);
        bv = ekkVar74;
        ekk ekkVar75 = new ekk("FINALLY", 74);
        bw = ekkVar75;
        ekk ekkVar76 = new ekk("WHILE", 75);
        bx = ekkVar76;
        ekk ekkVar77 = new ekk("CASE", 76);
        by = ekkVar77;
        ekk ekkVar78 = new ekk("DEFAULT", 77);
        bz = ekkVar78;
        ekk ekkVar79 = new ekk("CONST", 78);
        ca = ekkVar79;
        ekk ekkVar80 = new ekk("ENUM", 79);
        cb = ekkVar80;
        ekk ekkVar81 = new ekk("EXTENDS", 80);
        cc = ekkVar81;
        ekk ekkVar82 = new ekk("IMPLEMENTS", 81);
        cd = ekkVar82;
        ekk ekkVar83 = new ekk("IMPORT", 82);
        ce = ekkVar83;
        ekk ekkVar84 = new ekk("INSTANCEOF", 83);
        cf = ekkVar84;
        ekk ekkVar85 = new ekk("INTERFACE", 84);
        cg = ekkVar85;
        ekk ekkVar86 = new ekk("NATIVE", 85);
        ch = ekkVar86;
        ekk ekkVar87 = new ekk("THIS", 86);
        ci = ekkVar87;
        ekk ekkVar88 = new ekk("THROW", 87);
        cj = ekkVar88;
        ekk ekkVar89 = new ekk("THROWS", 88);
        ck = ekkVar89;
        ekk ekkVar90 = new ekk("AT", 89);
        cl = ekkVar90;
        ekk ekkVar91 = new ekk("TRUE", 90);
        cm = ekkVar91;
        ekk ekkVar92 = new ekk("FALSE", 91);
        cn = ekkVar92;
        ekk ekkVar93 = new ekk("NULL", 92);
        co = ekkVar93;
        cp = new ekk[]{ekkVar, ekkVar2, ekkVar3, ekkVar4, ekkVar5, ekkVar6, ekkVar7, ekkVar8, ekkVar9, ekkVar10, ekkVar11, ekkVar12, ekkVar13, ekkVar14, ekkVar15, ekkVar16, ekkVar17, ekkVar18, ekkVar19, ekkVar20, ekkVar21, ekkVar22, ekkVar23, ekkVar24, ekkVar25, ekkVar26, ekkVar27, ekkVar28, ekkVar29, ekkVar30, ekkVar31, ekkVar32, ekkVar33, ekkVar34, ekkVar35, ekkVar36, ekkVar37, ekkVar38, ekkVar39, ekkVar40, ekkVar41, ekkVar42, ekkVar43, ekkVar44, ekkVar45, ekkVar46, ekkVar47, ekkVar48, ekkVar49, ekkVar50, ekkVar51, ekkVar52, ekkVar53, ekkVar54, ekkVar55, ekkVar56, ekkVar57, ekkVar58, ekkVar59, ekkVar60, ekkVar61, ekkVar62, ekkVar63, ekkVar64, ekkVar65, ekkVar66, ekkVar67, ekkVar68, ekkVar69, ekkVar70, ekkVar71, ekkVar72, ekkVar73, ekkVar74, ekkVar75, ekkVar76, ekkVar77, ekkVar78, ekkVar79, ekkVar80, ekkVar81, ekkVar82, ekkVar83, ekkVar84, ekkVar85, ekkVar86, ekkVar87, ekkVar88, ekkVar89, ekkVar90, ekkVar91, ekkVar92, ekkVar93};
    }

    public static ekk valueOf(String str) {
        return (ekk) Enum.valueOf(ekk.class, str);
    }

    public static ekk[] values() {
        return (ekk[]) cp.clone();
    }
}
